-- PostgreSQL v1 business schema. No historical database import.
CREATE TABLE "users" ("id" bigserial,"username" varchar(64) NOT NULL,"nickname" varchar(64) NOT NULL DEFAULT '',"email" varchar(254) NOT NULL DEFAULT '',"password_hash" text NOT NULL,"avatar_data" bytea,"avatar_mime" varchar(32) NOT NULL DEFAULT '',"avatar_updated_at" timestamptz,"totp_enabled" boolean NOT NULL DEFAULT false,"totp_secret" bytea,"totp_last_counter" bigint NOT NULL DEFAULT 0,"totp_failed_attempts" bigint NOT NULL DEFAULT 0,"totp_locked_until" timestamptz,"passkey_user_handle" bytea,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_users_passkey_user_handle" ON "users" ("passkey_user_handle");
CREATE INDEX IF NOT EXISTS "idx_users_totp_locked_until" ON "users" ("totp_locked_until");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_users_username" ON "users" ("username");
CREATE TABLE "sessions" ("id" bigserial,"token_hash" varchar(64) NOT NULL,"user_id" bigint NOT NULL,"expires_at" timestamptz NOT NULL,"created_at" timestamptz,PRIMARY KEY ("id"),CONSTRAINT "fk_sessions_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS "idx_sessions_expires_at" ON "sessions" ("expires_at");
CREATE INDEX IF NOT EXISTS "idx_sessions_user_id" ON "sessions" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_sessions_token_hash" ON "sessions" ("token_hash");
CREATE TABLE "login_challenges" ("id" bigserial,"token_hash" varchar(64) NOT NULL,"user_id" bigint NOT NULL,"username" varchar(254) NOT NULL,"ip" varchar(64),"attempts" bigint NOT NULL DEFAULT 0,"expires_at" timestamptz NOT NULL,"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_login_challenges_expires_at" ON "login_challenges" ("expires_at");
CREATE INDEX IF NOT EXISTS "idx_login_challenges_user_id" ON "login_challenges" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_login_challenges_token_hash" ON "login_challenges" ("token_hash");
CREATE TABLE "two_factor_enrollments" ("user_id" bigserial,"secret_cipher" bytea,"expires_at" timestamptz NOT NULL,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("user_id"));
CREATE INDEX IF NOT EXISTS "idx_two_factor_enrollments_expires_at" ON "two_factor_enrollments" ("expires_at");
CREATE TABLE "two_factor_recovery_codes" ("id" bigserial,"user_id" bigint NOT NULL,"code_hash" text NOT NULL,"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_two_factor_recovery_codes_user_id" ON "two_factor_recovery_codes" ("user_id");
CREATE TABLE "passkey_credentials" ("id" bigserial,"user_id" bigint NOT NULL,"credential_id" bytea NOT NULL,"name" varchar(64) NOT NULL,"credential_json" bytea NOT NULL,"last_used_at" timestamptz,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_passkey_credentials_credential_id" ON "passkey_credentials" ("credential_id");
CREATE INDEX IF NOT EXISTS "idx_passkey_credentials_user_id" ON "passkey_credentials" ("user_id");
CREATE TABLE "web_authn_ceremonies" ("id" bigserial,"token_hash" varchar(64) NOT NULL,"user_id" bigint NOT NULL DEFAULT 0,"kind" varchar(16) NOT NULL,"name" varchar(64) NOT NULL DEFAULT '',"session_json" bytea NOT NULL,"rp_id" varchar(253) NOT NULL,"origin" varchar(512) NOT NULL,"expires_at" timestamptz NOT NULL,"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_web_authn_ceremonies_expires_at" ON "web_authn_ceremonies" ("expires_at");
CREATE INDEX IF NOT EXISTS "idx_web_authn_ceremonies_user_id" ON "web_authn_ceremonies" ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_web_authn_ceremonies_token_hash" ON "web_authn_ceremonies" ("token_hash");
CREATE TABLE "settings" ("key" varchar(128),"value" text NOT NULL,"updated_at" timestamptz,PRIMARY KEY ("key"));
CREATE TABLE "image_update_policies" ("node_id" varchar(64),"version" bigint NOT NULL,"enabled" boolean NOT NULL,"interval_hours" bigint NOT NULL DEFAULT 6,"next_run_at" timestamptz,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("node_id"));
CREATE INDEX IF NOT EXISTS "idx_image_update_policies_next_run_at" ON "image_update_policies" ("next_run_at");
CREATE INDEX IF NOT EXISTS "idx_image_update_policies_enabled" ON "image_update_policies" ("enabled");
CREATE TABLE "image_update_registry_credentials" ("node_id" varchar(64),"registry" varchar(512),"credential_id" bigint NOT NULL,PRIMARY KEY ("node_id","registry"));
CREATE INDEX IF NOT EXISTS "idx_image_update_registry_credentials_credential_id" ON "image_update_registry_credentials" ("credential_id");
CREATE TABLE "cleanup_policies" ("node_id" varchar(64),"version" bigint NOT NULL,"enabled" boolean NOT NULL,"config_json" text NOT NULL,"authorized_by" bigint,"authorized_at" timestamptz,"next_run_at" timestamptz,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("node_id"));
CREATE INDEX IF NOT EXISTS "idx_cleanup_policies_next_run_at" ON "cleanup_policies" ("next_run_at");
CREATE INDEX IF NOT EXISTS "idx_cleanup_policies_enabled" ON "cleanup_policies" ("enabled");
CREATE TABLE "cleanup_runs" ("id" varchar(64),"node_id" varchar(64) NOT NULL,"node_name" text,"policy_version" bigint,"policy_json" text,"trigger" text,"scheduled_for" timestamptz,"task_id" varchar(64),"user_id" bigint,"authorized_by" bigint,"status" varchar(32),"message" text,"result_json" text,"started_at" timestamptz,"finished_at" timestamptz,"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_cleanup_runs_status" ON "cleanup_runs" ("status");
CREATE INDEX IF NOT EXISTS "idx_cleanup_runs_task_id" ON "cleanup_runs" ("task_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_cleanup_occurrence" ON "cleanup_runs" ("node_id","scheduled_for");
CREATE INDEX IF NOT EXISTS "idx_cleanup_runs_node_id" ON "cleanup_runs" ("node_id");
CREATE TABLE "nodes" ("id" varchar(64),"name" varchar(128) NOT NULL,"connection_type" varchar(16) NOT NULL,"endpoint" varchar(1024) NOT NULL,"tls_mode" varchar(16) NOT NULL DEFAULT 'required',"tls_credential_id" bigint,"allowed_bind_roots_json" text NOT NULL DEFAULT '[]',"enabled" boolean NOT NULL DEFAULT true,"engine_id" varchar(128),"engine_version" varchar(64),"status" varchar(16) NOT NULL DEFAULT 'unknown',"last_error" text,"last_latency_ms" bigint,"last_checked_at" timestamptz,"agent_version" varchar(64),"agent_connected_at" timestamptz,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_nodes_engine_id" ON "nodes" ("engine_id");
CREATE INDEX IF NOT EXISTS "idx_nodes_tls_credential_id" ON "nodes" ("tls_credential_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_nodes_name" ON "nodes" ("name");
CREATE TABLE "agent_enrollments" ("node_id" varchar(64),"token_hash" varchar(64) NOT NULL,"expires_at" timestamptz NOT NULL,"consumed_at" timestamptz,"last_error" text,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("node_id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_agent_enrollments_token_hash" ON "agent_enrollments" ("token_hash");
CREATE TABLE "agent_credentials" ("node_id" varchar(64),"secret_hash" varchar(64) NOT NULL,"revoked_at" timestamptz,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("node_id"));
CREATE TABLE "node_groups" ("id" bigserial,"name" varchar(128) NOT NULL,"description" varchar(512) NOT NULL DEFAULT '',"is_default" boolean NOT NULL DEFAULT false,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_node_groups_is_default" ON "node_groups" ("is_default");
CREATE TABLE "node_group_nodes" ("group_id" bigint,"node_id" varchar(64),"created_at" timestamptz,PRIMARY KEY ("group_id","node_id"));
CREATE INDEX IF NOT EXISTS "idx_node_group_nodes_node_id" ON "node_group_nodes" ("node_id");
CREATE INDEX IF NOT EXISTS "idx_node_group_nodes_group_id" ON "node_group_nodes" ("group_id");
CREATE TABLE "docker_tls_credentials" ("id" bigserial,"name" varchar(128) NOT NULL,"ca_ciphertext" bytea,"certificate_ciphertext" bytea,"private_key_ciphertext" bytea,"fingerprint" varchar(64),"created_at" timestamptz,"updated_at" timestamptz,"last_used_at" timestamptz,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_docker_tls_credentials_name" ON "docker_tls_credentials" ("name");
CREATE TABLE "docker_tls_credential_nodes" ("credential_id" bigint,"node_id" varchar(64),PRIMARY KEY ("credential_id","node_id"));
CREATE TABLE "git_credential_nodes" ("credential_id" bigint,"node_id" varchar(64),PRIMARY KEY ("credential_id","node_id"));
CREATE TABLE "registry_credential_nodes" ("credential_id" bigint,"node_id" varchar(64),PRIMARY KEY ("credential_id","node_id"));
CREATE TABLE "delivery_projects" ("id" bigserial,"node_id" varchar(64) NOT NULL DEFAULT 'local',"name" varchar(128) NOT NULL,"deployment_name" varchar(128) NOT NULL,"git_clone_url" text,"git_credential_id" bigint,"git_ref_type" varchar(16),"git_ref" text,"compose_files_json" text,"environment_file" text,"reconcile_mode" varchar(16) NOT NULL DEFAULT 'manual',"sync_interval_seconds" bigint NOT NULL DEFAULT 300,"desired_commit" varchar(64),"observed_commit" varchar(64),"active_commit" varchar(64),"active_release_id" bigint,"auto_rollback" boolean,"deployment_timeout" bigint NOT NULL DEFAULT 120,"webhook_id" varchar(64),"webhook_secret" bytea,"webhook_enabled" boolean,"last_sync_at" timestamptz,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_delivery_projects_last_sync_at" ON "delivery_projects" ("last_sync_at");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_delivery_webhook_id" ON "delivery_projects" ("webhook_id") WHERE webhook_id <> '';
CREATE INDEX IF NOT EXISTS "idx_delivery_projects_active_release_id" ON "delivery_projects" ("active_release_id");
CREATE INDEX IF NOT EXISTS "idx_delivery_projects_git_credential_id" ON "delivery_projects" ("git_credential_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_delivery_projects_name" ON "delivery_projects" ("name");
CREATE INDEX IF NOT EXISTS "idx_delivery_projects_node_id" ON "delivery_projects" ("node_id");
CREATE TABLE "delivery_project_nodes" ("project_id" bigint,"node_id" varchar(64),"created_at" timestamptz,PRIMARY KEY ("project_id","node_id"));
CREATE TABLE "delivery_project_registry_credentials" ("project_id" bigint,"credential_id" bigint,PRIMARY KEY ("project_id","credential_id"));
CREATE TABLE "delivery_target_states" ("project_id" bigint,"node_id" varchar(64),"active_release_id" bigint,"observed_commit" varchar(64),"health_summary" text,"updated_at" timestamptz,PRIMARY KEY ("project_id","node_id"));
CREATE INDEX IF NOT EXISTS "idx_delivery_target_states_active_release_id" ON "delivery_target_states" ("active_release_id");
CREATE TABLE "git_credentials" ("id" bigserial,"name" varchar(128) NOT NULL,"auth_type" varchar(32) NOT NULL,"username" varchar(256),"secret_ciphertext" bytea,"private_key_ciphertext" bytea,"passphrase_ciphertext" bytea,"known_hosts_ciphertext" bytea,"ca_ciphertext" bytea,"fingerprint" varchar(64),"created_at" timestamptz,"updated_at" timestamptz,"last_used_at" timestamptz,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_git_credentials_name" ON "git_credentials" ("name");
CREATE TABLE "delivery_project_git_credentials" ("id" bigserial,"project_id" bigint NOT NULL,"name" varchar(128) NOT NULL,"auth_type" varchar(32) NOT NULL,"username" varchar(256),"secret_ciphertext" bytea,"private_key_ciphertext" bytea,"passphrase_ciphertext" bytea,"known_hosts_ciphertext" bytea,"ca_ciphertext" bytea,"fingerprint" varchar(64),"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_delivery_project_git_credentials_project_id" ON "delivery_project_git_credentials" ("project_id");
CREATE TABLE "registry_credentials" ("id" bigserial,"name" varchar(128) NOT NULL,"server_address" varchar(512) NOT NULL,"auth_type" varchar(32) NOT NULL,"username" varchar(256),"secret_ciphertext" bytea,"fingerprint" varchar(64),"created_at" timestamptz,"updated_at" timestamptz,"last_used_at" timestamptz,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_registry_credentials_name" ON "registry_credentials" ("name");
CREATE TABLE "delivery_releases" ("id" bigserial,"project_id" bigint NOT NULL,"repository_url" text,"git_ref" text,"commit_sha" varchar(64) NOT NULL,"commit_message" text,"commit_author" text,"config_hash" varchar(64),"image_references" text,"task_id" varchar(36),"status" varchar(32) NOT NULL,"trigger_type" varchar(32) NOT NULL,"trigger_actor" text,"previous_release_id" bigint,"worktree_path" text,"compose_files_json" text,"environment_file" text,"approved_by" bigint,"approved_at" timestamptz,"started_at" timestamptz,"finished_at" timestamptz,"failure_reason" text,"health_summary" text,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_delivery_releases_approved_by" ON "delivery_releases" ("approved_by");
CREATE INDEX IF NOT EXISTS "idx_delivery_releases_previous_release_id" ON "delivery_releases" ("previous_release_id");
CREATE INDEX IF NOT EXISTS "idx_delivery_releases_status" ON "delivery_releases" ("status");
CREATE INDEX IF NOT EXISTS "idx_delivery_releases_task_id" ON "delivery_releases" ("task_id");
CREATE INDEX IF NOT EXISTS "idx_delivery_releases_config_hash" ON "delivery_releases" ("config_hash");
CREATE INDEX IF NOT EXISTS "idx_delivery_releases_commit_sha" ON "delivery_releases" ("commit_sha");
CREATE INDEX IF NOT EXISTS "idx_delivery_releases_project_id" ON "delivery_releases" ("project_id");
CREATE TABLE "delivery_release_deployments" ("id" bigserial,"release_id" bigint NOT NULL,"node_id" varchar(64) NOT NULL,"node_name" varchar(128) NOT NULL,"task_id" varchar(36),"status" varchar(32) NOT NULL,"previous_release_id" bigint,"failure_reason" text,"rollback_result" varchar(32),"health_summary" text,"started_at" timestamptz,"finished_at" timestamptz,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_delivery_release_deployments_previous_release_id" ON "delivery_release_deployments" ("previous_release_id");
CREATE INDEX IF NOT EXISTS "idx_delivery_release_deployments_status" ON "delivery_release_deployments" ("status");
CREATE INDEX IF NOT EXISTS "idx_delivery_release_deployments_task_id" ON "delivery_release_deployments" ("task_id");
CREATE INDEX IF NOT EXISTS "idx_delivery_release_deployments_node_id" ON "delivery_release_deployments" ("node_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_release_node" ON "delivery_release_deployments" ("release_id","node_id");
CREATE INDEX IF NOT EXISTS "idx_delivery_release_deployments_release_id" ON "delivery_release_deployments" ("release_id");
CREATE TABLE "delivery_deployment_attempts" ("id" bigserial,"deployment_id" bigint NOT NULL,"operation" varchar(32) NOT NULL,"target_release_id" bigint NOT NULL,"task_id" varchar(36),"status" varchar(32) NOT NULL,"failure_reason" text,"health_summary" text,"started_at" timestamptz,"finished_at" timestamptz,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_delivery_deployment_attempts_status" ON "delivery_deployment_attempts" ("status");
CREATE INDEX IF NOT EXISTS "idx_delivery_deployment_attempts_task_id" ON "delivery_deployment_attempts" ("task_id");
CREATE INDEX IF NOT EXISTS "idx_delivery_deployment_attempts_target_release_id" ON "delivery_deployment_attempts" ("target_release_id");
CREATE INDEX IF NOT EXISTS "idx_delivery_deployment_attempts_operation" ON "delivery_deployment_attempts" ("operation");
CREATE INDEX IF NOT EXISTS "idx_delivery_deployment_attempts_deployment_id" ON "delivery_deployment_attempts" ("deployment_id");
CREATE TABLE "git_webhook_deliveries" ("id" bigserial,"format" varchar(16) NOT NULL,"hook_id" varchar(64) NOT NULL,"delivery_id" varchar(128) NOT NULL,"event" varchar(64),"repository" text,"git_ref" text,"commit_sha" varchar(64),"status" varchar(32) NOT NULL,"failure_reason" text,"created_at" timestamptz,"processed_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_git_webhook_deliveries_created_at" ON "git_webhook_deliveries" ("created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_hook_delivery" ON "git_webhook_deliveries" ("hook_id","delivery_id");
CREATE TABLE "tasks" ("id" varchar(36),"scope" varchar(24) NOT NULL DEFAULT 'node',"node_id" varchar(64) NOT NULL DEFAULT '',"node_name" varchar(128),"type" varchar(64) NOT NULL,"name" text NOT NULL,"status" varchar(16) NOT NULL,"progress" bigint NOT NULL DEFAULT 0,"message" text,"created_at" timestamptz,"started_at" timestamptz,"finished_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_tasks_status" ON "tasks" ("status");
CREATE INDEX IF NOT EXISTS "idx_tasks_node_id" ON "tasks" ("node_id");
CREATE INDEX IF NOT EXISTS "idx_tasks_scope" ON "tasks" ("scope");
CREATE TABLE "task_logs" ("id" bigserial,"task_id" varchar(36) NOT NULL,"level" varchar(16) NOT NULL DEFAULT 'info',"message" text NOT NULL,"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_task_logs_created_at" ON "task_logs" ("created_at");
CREATE INDEX IF NOT EXISTS "idx_task_logs_task_id" ON "task_logs" ("task_id");
CREATE TABLE "task_steps" ("task_id" varchar(36),"step_id" varchar(128),"status" varchar(128) NOT NULL,"current" bigint NOT NULL DEFAULT 0,"total" bigint NOT NULL DEFAULT 0,"progress" bigint NOT NULL DEFAULT 0,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("task_id","step_id"));
CREATE TABLE "audit_logs" ("id" bigserial,"scope" varchar(24) NOT NULL DEFAULT 'node',"node_id" varchar(64) NOT NULL DEFAULT '',"node_name" varchar(128),"user_id" bigint,"action" varchar(64) NOT NULL,"resource_type" varchar(64),"resource_name" text,"ip" varchar(64),"result" varchar(16) NOT NULL,"task_id" varchar(36),"release_id" bigint,"source" varchar(24),"run_id" varchar(64),"operation_id" varchar(64),"binding_id" varchar(64),"external_user_id" text,"chat_id" text,"details" text,"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_audit_logs_operation_id" ON "audit_logs" ("operation_id");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_run_id" ON "audit_logs" ("run_id");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_source" ON "audit_logs" ("source");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_release_id" ON "audit_logs" ("release_id");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_task_id" ON "audit_logs" ("task_id");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_action" ON "audit_logs" ("action");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_user_id" ON "audit_logs" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_node_id" ON "audit_logs" ("node_id");
CREATE INDEX IF NOT EXISTS "idx_audit_logs_scope" ON "audit_logs" ("scope");
CREATE TABLE "file_revisions" ("id" bigserial,"node_id" varchar(64) NOT NULL,"container_id" varchar(128) NOT NULL,"path" text NOT NULL,"hash" varchar(64) NOT NULL,"ciphertext" bytea NOT NULL,"user_id" bigint,"baseline" boolean,"state" varchar(16) NOT NULL,"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_file_revisions_created_at" ON "file_revisions" ("created_at");
CREATE INDEX IF NOT EXISTS "idx_file_revisions_state" ON "file_revisions" ("state");
CREATE INDEX IF NOT EXISTS "idx_file_revision" ON "file_revisions" ("node_id","container_id","path");
CREATE TABLE "login_logs" ("id" bigserial,"username" varchar(64) NOT NULL,"ip" varchar(64),"success" boolean,"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE TABLE "notification_channels" ("id" varchar(64),"name" text,"provider" text,"enabled" boolean,"version" bigint,"config_json" text,"secret_ciphertext" bytea,"last_error" text,"last_sent_at" timestamptz,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE TABLE "notification_rules" ("id" varchar(64),"name" text,"enabled" boolean,"version" bigint,"config_json" text,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE TABLE "notification_events" ("id" varchar(64),"type" text,"severity" text,"node_id" text,"dedupe_key" text,"data_json" text,"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_notification_events_created_at" ON "notification_events" ("created_at");
CREATE INDEX IF NOT EXISTS "idx_notification_events_dedupe_key" ON "notification_events" ("dedupe_key");
CREATE INDEX IF NOT EXISTS "idx_notification_events_node_id" ON "notification_events" ("node_id");
CREATE INDEX IF NOT EXISTS "idx_notification_events_type" ON "notification_events" ("type");
CREATE TABLE "notification_reads" ("user_id" bigint,"event_id" varchar(64),"read_at" timestamptz,PRIMARY KEY ("user_id","event_id"));
CREATE TABLE "notification_deliveries" ("id" varchar(64),"channel_id" text,"rule_id" text,"batch_key" text,"event_ids_json" text,"status" text,"reason" text,"attempts" bigint,"due_at" timestamptz,"lease_until" timestamptz,"provider_message_id" text,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_notification_deliveries_lease_until" ON "notification_deliveries" ("lease_until");
CREATE INDEX IF NOT EXISTS "idx_notification_deliveries_due_at" ON "notification_deliveries" ("due_at");
CREATE INDEX IF NOT EXISTS "idx_notification_deliveries_status" ON "notification_deliveries" ("status");
CREATE INDEX IF NOT EXISTS "idx_notification_deliveries_batch_key" ON "notification_deliveries" ("batch_key");
CREATE INDEX IF NOT EXISTS "idx_notification_deliveries_channel_id" ON "notification_deliveries" ("channel_id");
CREATE TABLE "notification_bindings" ("id" varchar(64),"channel_id" text,"user_id" bigint,"code_hash" varchar(64),"external_user_id" text,"external_name" text,"chat_id" text,"status" text,"expires_at" timestamptz,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_notification_bindings_status" ON "notification_bindings" ("status");
CREATE INDEX IF NOT EXISTS "idx_notification_bindings_external_user_id" ON "notification_bindings" ("external_user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_notification_bindings_code_hash" ON "notification_bindings" ("code_hash");
CREATE INDEX IF NOT EXISTS "idx_notification_bindings_user_id" ON "notification_bindings" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_notification_bindings_channel_id" ON "notification_bindings" ("channel_id");
CREATE TABLE "notification_incomings" ("key" varchar(256),"created_at" timestamptz,PRIMARY KEY ("key"));
CREATE INDEX IF NOT EXISTS "idx_notification_incomings_created_at" ON "notification_incomings" ("created_at");
CREATE TABLE "notification_chats" ("channel_id" varchar(64),"chat_id" varchar(128),"name" text,"private" boolean,"updated_at" timestamptz,PRIMARY KEY ("channel_id","chat_id"));
CREATE TABLE "notification_actions" ("token_hash" varchar(64),"operation_id" text,"binding_id" text,"channel_id" text,"chat_id" text,"expires_at" timestamptz,"consumed_at" timestamptz,PRIMARY KEY ("token_hash"));
CREATE INDEX IF NOT EXISTS "idx_notification_actions_expires_at" ON "notification_actions" ("expires_at");
CREATE INDEX IF NOT EXISTS "idx_notification_actions_operation_id" ON "notification_actions" ("operation_id");
CREATE TABLE "ai_runs" ("task_progress" bigint NOT NULL DEFAULT 0,"task_status" text,"predecessor_id" varchar(64),"conversation_id" varchar(64),"revision" bigint NOT NULL DEFAULT 1,"phase" varchar(32),"target_source" varchar(32),"actor_json" jsonb NOT NULL DEFAULT '{}',"input_json" jsonb NOT NULL DEFAULT '{}',"resume_json" jsonb NOT NULL DEFAULT '{}',"resume_target" text,"config_hash" text,"iterations" bigint NOT NULL DEFAULT 0,"reads" bigint NOT NULL DEFAULT 0,"operations" bigint NOT NULL DEFAULT 0,"lease_owner" varchar(64),"lease_until" timestamptz,"id" varchar(64),"user_id" bigint,"node_id" text,"model" text,"node_ids_json" jsonb NOT NULL DEFAULT '[]',"source" text,"event_id" text,"question" text,"status" text,"result_json" jsonb NOT NULL DEFAULT '{}',"error" text,"tokens" bigint,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_ai_runs_created_at" ON "ai_runs" ("created_at");
CREATE INDEX IF NOT EXISTS "idx_ai_runs_status" ON "ai_runs" ("status");
CREATE INDEX IF NOT EXISTS "idx_ai_runs_event_id" ON "ai_runs" ("event_id");
CREATE INDEX IF NOT EXISTS "idx_ai_runs_node_id" ON "ai_runs" ("node_id");
CREATE INDEX IF NOT EXISTS "idx_ai_runs_user_id" ON "ai_runs" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_ai_runs_lease_until" ON "ai_runs" ("lease_until");
CREATE INDEX IF NOT EXISTS "idx_ai_runs_conversation_id" ON "ai_runs" ("conversation_id");
CREATE TABLE "ai_operations" ("step_id" varchar(64),"confirmations_json" jsonb NOT NULL DEFAULT '[]',"confirmed_json" jsonb NOT NULL DEFAULT '{}',"snapshot_ciphertext" bytea,"decision_key" varchar(64),"decision_hash" varchar(64),"verification_json" jsonb NOT NULL DEFAULT '{}',"id" varchar(64),"run_id" text,"requested_by" bigint,"approved_by" bigint,"node_id" text,"action" text,"resource_id" text,"title" text,"impact" text,"parameters_json" jsonb NOT NULL DEFAULT '{}',"snapshot_json" jsonb NOT NULL DEFAULT '{}',"snapshot_hash" text,"status" text,"task_id" text,"result" text,"approval_source" text,"expires_at" timestamptz,"created_at" timestamptz,"updated_at" timestamptz,"binding_id" text,"external_user_id" text,"chat_id" text,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_ai_operations_expires_at" ON "ai_operations" ("expires_at");
CREATE INDEX IF NOT EXISTS "idx_ai_operations_task_id" ON "ai_operations" ("task_id");
CREATE INDEX IF NOT EXISTS "idx_ai_operations_status" ON "ai_operations" ("status");
CREATE INDEX IF NOT EXISTS "idx_ai_operations_node_id" ON "ai_operations" ("node_id");
CREATE INDEX IF NOT EXISTS "idx_ai_operations_run_id" ON "ai_operations" ("run_id");
CREATE INDEX IF NOT EXISTS "idx_ai_operations_step_id" ON "ai_operations" ("step_id");
CREATE TABLE "ai_conversations" ("chat_sent_seq" bigint NOT NULL DEFAULT 0,"chat_lease_until" timestamptz,"id" varchar(64),"user_id" bigint NOT NULL,"title" text,"source" varchar(16) NOT NULL,"chat_key" varchar(64),"binding_id" varchar(64),"chat_id" text,"current_run_id" varchar(64),"context_json" jsonb NOT NULL DEFAULT '{}',"revision" bigint NOT NULL DEFAULT 1,"event_seq" bigint NOT NULL DEFAULT 0,"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_ai_conversations_updated_at" ON "ai_conversations" ("updated_at");
CREATE INDEX IF NOT EXISTS "idx_ai_conversations_created_at" ON "ai_conversations" ("created_at");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_ai_chat_key" ON "ai_conversations" ("chat_key") WHERE chat_key <> '';
CREATE INDEX IF NOT EXISTS "idx_ai_conversations_user_id" ON "ai_conversations" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_ai_conversations_chat_lease_until" ON "ai_conversations" ("chat_lease_until");
CREATE TABLE "ai_messages" ("id" varchar(64),"conversation_id" varchar(64) NOT NULL,"run_id" varchar(64),"role" varchar(16),"content" text,"request_key" varchar(64),"request_hash" varchar(64),"metadata_json" jsonb NOT NULL DEFAULT '{}',"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_ai_messages_created_at" ON "ai_messages" ("created_at");
CREATE INDEX IF NOT EXISTS "idx_ai_messages_run_id" ON "ai_messages" ("run_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_ai_message_request" ON "ai_messages" ("conversation_id","request_key") WHERE request_key <> '';
CREATE INDEX IF NOT EXISTS "idx_ai_messages_conversation_id" ON "ai_messages" ("conversation_id");
CREATE TABLE "a_iplan_steps" ("id" varchar(64),"run_id" varchar(64) NOT NULL,"position" bigint NOT NULL,"title" text,"node_id" varchar(64),"action" varchar(64),"resource_id" text,"parameters_json" jsonb NOT NULL DEFAULT '{}',"depends_json" jsonb NOT NULL DEFAULT '[]',"expected" text,"status" varchar(32),"operation_id" varchar(64),"created_at" timestamptz,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_a_iplan_steps_status" ON "a_iplan_steps" ("status");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_ai_plan_position" ON "a_iplan_steps" ("run_id","position");
CREATE INDEX IF NOT EXISTS "idx_a_iplan_steps_run_id" ON "a_iplan_steps" ("run_id");
CREATE TABLE "ai_interactions" ("id" varchar(64),"run_id" varchar(64) NOT NULL,"revision" bigint,"kind" varchar(32),"prompt" text,"options_json" jsonb NOT NULL DEFAULT '[]',"multiple" boolean,"interrupt_id" text,"state_json" jsonb NOT NULL DEFAULT '{}',"status" varchar(16),"answer_json" jsonb NOT NULL DEFAULT '{}',"request_key" varchar(64),"expires_at" timestamptz,"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_ai_interactions_expires_at" ON "ai_interactions" ("expires_at");
CREATE INDEX IF NOT EXISTS "idx_ai_interactions_status" ON "ai_interactions" ("status");
CREATE INDEX IF NOT EXISTS "idx_ai_interactions_run_id" ON "ai_interactions" ("run_id");
CREATE TABLE "ai_checkpoints" ("id" varchar(128),"run_id" varchar(64),"revision" bigint,"framework_version" varchar(32),"workflow_version" varchar(32),"format_version" bigint,"ciphertext" bytea,"updated_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_ai_checkpoints_run_id" ON "ai_checkpoints" ("run_id");
CREATE TABLE "ai_tool_calls" ("id" varchar(64),"run_id" varchar(64) NOT NULL,"call_key" varchar(128) NOT NULL,"name" varchar(64),"arguments_hash" varchar(64),"arguments_json" jsonb NOT NULL DEFAULT '{}',"result" text,"status" varchar(32),"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE UNIQUE INDEX IF NOT EXISTS "idx_ai_tool_call" ON "ai_tool_calls" ("run_id","call_key");
CREATE INDEX IF NOT EXISTS "idx_ai_tool_calls_run_id" ON "ai_tool_calls" ("run_id");
CREATE TABLE "ai_workflow_events" ("id" bigserial,"conversation_id" varchar(64) NOT NULL,"seq" bigint NOT NULL,"run_id" varchar(64),"type" varchar(64),"payload_json" jsonb NOT NULL DEFAULT '{}',"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_ai_workflow_events_run_id" ON "ai_workflow_events" ("run_id");
CREATE UNIQUE INDEX IF NOT EXISTS "idx_ai_event_seq" ON "ai_workflow_events" ("conversation_id","seq");
CREATE INDEX IF NOT EXISTS "idx_ai_workflow_events_conversation_id" ON "ai_workflow_events" ("conversation_id");
CREATE TABLE "ai_compose_drafts" ("id" varchar(64),"run_id" varchar(64),"node_id" varchar(64),"project" text,"base_revision" text,"content_hash" varchar(64),"ciphertext" bytea,"preview_json" jsonb NOT NULL DEFAULT '{}',"created_at" timestamptz,PRIMARY KEY ("id"));
CREATE INDEX IF NOT EXISTS "idx_ai_compose_drafts_run_id" ON "ai_compose_drafts" ("run_id");
CREATE UNIQUE INDEX idx_users_email_lower ON users (lower(email)) WHERE email <> '';
CREATE UNIQUE INDEX idx_node_groups_name_lower ON node_groups (lower(name));
INSERT INTO node_groups (name, description, is_default, created_at, updated_at) VALUES ('Default', '', true, now(), now());
