import { useEffect, useState } from 'react'
import { useLocation } from '@tanstack/react-router'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { MoreHorizontal, Plus, Send } from 'lucide-react'
import { Button } from '../../components/ui/button'
import { Input } from '../../components/ui/input'
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '../../components/ui/sheet'
import { Tabs, TabsList, TabsTrigger } from '../../components/ui/tabs'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '../../components/ui/dropdown-menu'
import { Badge } from '../../components/ui/badge'
import { api } from '../../lib/api'
import { useI18n } from '../../lib/i18n'
import { useDateTime } from '../../lib/time-zone'
import type { DockerNode, NodeGroup } from '../../lib/nodes'
import { confirmDialog } from '../../stores/dialog'
import { Check, Choice, ErrorText, Field } from './common'
import { channelPlatforms, hasMissingRecipients, toggle, useOpsText } from './helpers'
import { ChannelEditor } from './channel-editor'
import type { Catalog, Channel, Delivery, Rule, RuleConfig } from './types'

const newRule = (timeZone: string): RuleConfig => ({ events: [], severities: [], node_ids: [], group_ids: [], projects: [], channel_ids: [], channel_targets: {}, fallback_id: '', fallback_chat_id: '', mode: 'immediate', timezone: timeZone, digest_hour: 9, quiet_start: '', quiet_end: '', recovery: true, template: '' })
export function NotificationSettings() {
 const t = useOpsText(), client = useQueryClient(), { formatDateTime } = useDateTime(), { language } = useI18n(), platforms = channelPlatforms(language)
 const hash = useLocation({ select: location => location.hash }), requestedTab = new URLSearchParams(hash.split('?')[1] || '').get('tab'), initialTab = requestedTab === 'rules' || requestedTab === 'deliveries' ? requestedTab : 'channels'
 const [subscribeChannel, setSubscribeChannel] = useState<Channel | undefined>()
 const [tab, setTab] = useState(initialTab), [editing, setEditing] = useState<Channel | 'new' | null>(null), [ruleEdit, setRuleEdit] = useState<Rule | 'new' | null>(null)
 useEffect(() => setTab(initialTab), [initialTab])
 const channels = useQuery({ queryKey: ['notification-channels'], queryFn: () => api<Channel[]>('/notifications/channels'), refetchInterval: 10000 })
 const rules = useQuery({ queryKey: ['notification-rules'], queryFn: () => api<Rule[]>('/notifications/rules') })
 const deliveries = useQuery({ queryKey: ['notification-deliveries'], queryFn: () => api<Delivery[]>('/notifications/deliveries'), enabled: tab === 'deliveries', refetchInterval: 5000 })
 const action = useMutation({ mutationFn: ({ path, method = 'POST', body }: { path: string; method?: string; body?: unknown }) => api(path, { method, body: body ? JSON.stringify(body) : undefined }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['notification-channels'] }); void client.invalidateQueries({ queryKey: ['notification-rules'] }); void client.invalidateQueries({ queryKey: ['notification-deliveries'] }) } })
 const remove = async (path: string, name: string) => { if (await confirmDialog({ title: t(`删除 ${name}？`, `Delete ${name}?`), description: path.includes('/channels/') ? t('待发送消息将停止投递，渠道绑定将撤销。', 'Pending deliveries stop; channel identities are revoked.') : t('此规则的待发送消息将停止投递。', 'Pending deliveries for this rule will stop.'), danger: true, confirmLabel: t('删除', 'Delete') })) action.mutate({ path, method: 'DELETE' }) }
 return <section className="space-y-4">
  <div className="flex flex-wrap items-center justify-between gap-3"><Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="channels">{t('渠道', 'Channels')}</TabsTrigger><TabsTrigger value="rules">{t('通知规则', 'Rules')}</TabsTrigger><TabsTrigger value="deliveries">{t('发送记录', 'Deliveries')}</TabsTrigger></TabsList></Tabs>{tab !== 'deliveries' && <Button size="sm" onClick={() => tab === 'channels' ? setEditing('new') : (setSubscribeChannel(undefined), setRuleEdit('new'))}><Plus />{tab === 'channels' ? t('添加通知渠道', 'Add channel') : t('添加规则', 'Add rule')}</Button>}</div>
  <p className="text-sm text-muted-foreground">{t('站内事件始终保留。通过规则选择外部渠道和通知频率。', 'Events remain available in your inbox. Rules select external destinations and delivery frequency.')}</p>
  <ErrorText error={action.error || channels.error || rules.error || deliveries.error} />
  {tab === 'channels' && <div className="divide-y border-y">{channels.data?.map(row => <div key={row.id} className="flex items-center gap-3 py-3"><Send className="size-4 shrink-0 text-muted-foreground" /><div className="min-w-0 flex-1"><button onClick={() => setEditing(row)} className="truncate font-medium hover:underline">{row.name}</button><p className="text-xs text-muted-foreground">{platforms.find(([id]) => id === row.provider)?.[1]} · {t('通知', 'Notifications')} · {row.last_error || (row.last_sent_at ? formatDateTime(row.last_sent_at) : t('尚未发送', 'No deliveries yet'))}</p></div><Badge variant={row.enabled ? 'secondary' : 'outline'}>{row.enabled ? t('启用', 'Enabled') : t('停用', 'Paused')}</Badge><DropdownMenu><DropdownMenuTrigger render={<Button variant="ghost" size="icon-sm" aria-label={t('渠道操作', 'Channel actions')}><MoreHorizontal /></Button>} /><DropdownMenuContent><DropdownMenuItem onClick={() => setEditing(row)}>{t('编辑', 'Edit')}</DropdownMenuItem><DropdownMenuItem onClick={() => row.provider === 'feishu_app' ? setEditing(row) : action.mutate({ path: `/notifications/channels/${row.id}/test` })}>{t('发送测试', 'Send test')}</DropdownMenuItem><DropdownMenuItem onClick={() => action.mutate({ path: `/notifications/channels/${row.id}`, method: 'PUT', body: { name: row.name, provider: row.provider, enabled: !row.enabled, version: row.version, config: row.config } })}>{row.enabled ? t('暂停', 'Pause') : t('启用', 'Enable')}</DropdownMenuItem><DropdownMenuItem onClick={() => { void remove(`/notifications/channels/${row.id}`, row.name) }}>{t('删除', 'Delete')}</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>)}{channels.data?.length === 0 && <p className="py-10 text-center text-sm text-muted-foreground">{t('添加第一个渠道，接收重要事件。', 'Add your first channel to receive important events.')}</p>}</div>}
  {tab === 'rules' && <div className="divide-y border-y">{rules.data?.map(row => <div key={row.id} className="flex items-center gap-3 py-3"><div className="min-w-0 flex-1"><button className="font-medium hover:underline" onClick={() => setRuleEdit(row)}>{row.name}</button><p className="text-xs text-muted-foreground">{row.config.events.length} {t('种事件', 'events')} · {row.config.mode} · {row.config.channel_ids.map(id => channels.data?.find(c => c.id === id)?.name).join(', ')}</p>{channels.data && hasMissingRecipients(row.config, channels.data) && <p className="text-xs text-destructive">{t('接收目标已失效，请编辑规则。', 'A recipient was removed. Edit this rule.')}</p>}</div><Badge variant="outline">{row.enabled ? t('启用', 'Enabled') : t('停用', 'Paused')}</Badge><DropdownMenu><DropdownMenuTrigger render={<Button variant="ghost" size="icon-sm" aria-label={t('规则操作', 'Rule actions')}><MoreHorizontal /></Button>} /><DropdownMenuContent><DropdownMenuItem onClick={() => setRuleEdit(row)}>{t('编辑', 'Edit')}</DropdownMenuItem><DropdownMenuItem onClick={() => action.mutate({ path: `/notifications/rules/${row.id}`, method: 'PUT', body: { name: row.name, enabled: !row.enabled, version: row.version, config: row.config } })}>{row.enabled ? t('暂停', 'Pause') : t('启用', 'Enable')}</DropdownMenuItem><DropdownMenuItem onClick={() => { void remove(`/notifications/rules/${row.id}`, row.name) }}>{t('删除', 'Delete')}</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>)}{rules.data?.length === 0 && <p className="py-10 text-center text-sm text-muted-foreground">{t('使用预设创建规则，也可以自选事件。', 'Start with a preset or choose your own events.')}</p>}</div>}
  {tab === 'deliveries' && <div className="divide-y border-y">{deliveries.data?.map(row => <div key={row.id} className="flex flex-wrap items-center gap-3 py-3 text-sm"><span className="flex-1">{channels.data?.find(c => c.id === row.channel_id)?.name || row.channel_id}<span className="block text-xs text-muted-foreground">{formatDateTime(row.created_at)}{row.chat_id ? ` · ${channels.data?.find(channel => channel.id === row.channel_id)?.config.targets?.find(target => target.chat_id === row.chat_id)?.name || row.chat_id}` : ''} · {row.reason || `${row.attempts} ${t('次尝试', 'attempts')}`}</span></span><Badge variant="outline">{row.status}</Badge>{['failed', 'suppressed', 'sent'].includes(row.status) && <Button size="sm" variant="ghost" disabled={action.isPending} onClick={() => action.mutate({ path: `/notifications/deliveries/${row.id}/resend` })}>{t('重发', 'Resend')}</Button>}</div>)}</div>}
  <Sheet open={editing !== null} onOpenChange={open => { if (!open) setEditing(null) }}><SheetContent className="w-full gap-0 data-[side=right]:w-full sm:max-w-xl"><SheetHeader className="border-b"><SheetTitle>{t('配置通知渠道', 'Configure channel')}</SheetTitle><SheetDescription>{t('配置凭证、接收目标和通知订阅。', 'Configure credentials, recipients and notification subscriptions.')}</SheetDescription></SheetHeader>{editing && <ChannelEditor key={editing === 'new' ? 'new' : editing.id} row={editing === 'new' ? undefined : editing} onDone={() => setEditing(null)} onSubscribe={channel => { setSubscribeChannel(channel); setEditing(null); setTab('rules'); setRuleEdit('new') }} />}</SheetContent></Sheet>
  <Sheet open={ruleEdit !== null} onOpenChange={open => { if (!open) setRuleEdit(null) }}><SheetContent className="w-full gap-0 data-[side=right]:w-full sm:max-w-xl"><SheetHeader className="border-b"><SheetTitle>{t('通知规则', 'Notification rule')}</SheetTitle><SheetDescription>{t('选择事件、目标和降噪方式', 'Choose events, destinations and noise controls')}</SheetDescription></SheetHeader>{ruleEdit && <RuleEditor key={ruleEdit === 'new' ? 'new' : ruleEdit.id} row={ruleEdit === 'new' ? undefined : ruleEdit} channels={channels.data || []} initialChannel={subscribeChannel} onDone={() => setRuleEdit(null)} />}</SheetContent></Sheet>
 </section>
}
function RuleEditor({ row, channels, initialChannel, onDone }: { row?: Rule; channels: Channel[]; initialChannel?: Channel; onDone: () => void }) {
 const t = useOpsText(), { timeZone } = useDateTime(), client = useQueryClient()
 const [preset, setPreset] = useState('custom'), [name, setName] = useState(row?.name || ''), [enabled, setEnabled] = useState(row?.enabled ?? true), [cfg, setCfg] = useState<RuleConfig>(() => row?.config || { ...newRule(timeZone), ...(initialChannel ? { channel_ids: [initialChannel.id], channel_targets: initialChannel.provider === 'feishu_app' ? { [initialChannel.id]: (initialChannel.config.targets || []).map(target => target.chat_id) } : {} } : {}) })
 const update = <K extends keyof RuleConfig>(key: K, value: RuleConfig[K]) => setCfg(prev => ({ ...prev, [key]: value }))
 const fallback = channels.find(channel => channel.id === cfg.fallback_id)
 const invalidRecipients = hasMissingRecipients(cfg, channels)
 const selectChannel = (channel: Channel) => setCfg(previous => {
  const selected = !previous.channel_ids.includes(channel.id), channelTargets = { ...previous.channel_targets }
  if (selected && channel.provider === 'feishu_app') channelTargets[channel.id] = (channel.config.targets || []).map(target => target.chat_id)
  else delete channelTargets[channel.id]
  return { ...previous, channel_ids: toggle(previous.channel_ids, channel.id), channel_targets: channelTargets, ...(selected && previous.fallback_id === channel.id ? { fallback_id: '', fallback_chat_id: '' } : {}) }
 })
 const catalog = useQuery({ queryKey: ['notification-catalog'], queryFn: () => api<Catalog>('/notifications/catalog') })
 const nodes = useQuery({ queryKey: ['nodes'], queryFn: () => api<DockerNode[]>('/nodes') }), groups = useQuery({ queryKey: ['node-groups'], queryFn: () => api<NodeGroup[]>('/node-groups') })
 const save = useMutation({ mutationFn: () => api(`/notifications/rules${row ? `/${row.id}` : ''}`, { method: row ? 'PUT' : 'POST', body: JSON.stringify({ name, enabled, version: row?.version || 0, config: cfg }) }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['notification-rules'] }); onDone() } })
 return <form className="space-y-4 overflow-y-auto p-5" onSubmit={e => { e.preventDefault(); save.mutate() }}>
 <Field label={t('规则名称', 'Rule name')}><Input value={name} onChange={e => setName(e.target.value)} required /></Field>
 <Choice label={t('使用预设', 'Use preset')} value={preset} options={[[ 'custom', t('自定义', 'Custom') ], ['security', t('账户安全', 'Account security')], ['important', t('重要异常', 'Important incidents')], ['images', t('镜像更新', 'Image updates')], ['delivery', t('发布动态', 'Delivery updates')], ['cleanup', t('清理报告', 'Cleanup reports')]]} onChange={key => { setPreset(key); if (catalog.data?.presets[key]) { update('events', catalog.data.presets[key]); if (!name) setName(key) } }} />
 <details open><summary className="mb-2 cursor-pointer text-sm font-medium">{t('事件', 'Events')} · {cfg.events.length}</summary><div className="grid gap-2 sm:grid-cols-2">{catalog.data?.events.map(e => <Check key={e.type} label={t(e.title, e.title_en)} checked={cfg.events.includes(e.type)} onChange={() => update('events', toggle(cfg.events, e.type))} />)}</div></details>
 <Field label={t('目标渠道', 'Destinations')}><div className="space-y-3">{channels.map(channel => <div key={channel.id} className="space-y-2"><Check label={channel.name} checked={cfg.channel_ids.includes(channel.id)} onChange={() => selectChannel(channel)} />{channel.provider === 'feishu_app' && cfg.channel_ids.includes(channel.id) && <div role="group" aria-label={t(`${channel.name} 接收目标`, `${channel.name} recipients`)} className="space-y-2 border-l pl-4">{channel.config.targets?.map(target => <Check key={target.chat_id} label={target.name} checked={cfg.channel_targets?.[channel.id]?.includes(target.chat_id) || false} onChange={() => update('channel_targets', { ...cfg.channel_targets, [channel.id]: toggle(cfg.channel_targets?.[channel.id] || [], target.chat_id) })} />)}{cfg.channel_targets?.[channel.id]?.filter(id => !channel.config.targets?.some(target => target.chat_id === id)).map(id => <Check key={id} label={t(`目标已失效：${id}`, `Missing recipient: ${id}`)} checked onChange={() => update('channel_targets', { ...cfg.channel_targets, [channel.id]: (cfg.channel_targets?.[channel.id] || []).filter(value => value !== id) })} />)}{!channel.config.targets?.length && <p className="text-xs text-destructive">{t('请先为此渠道配置接收目标。', 'Configure recipients for this channel first.')}</p>}</div>}</div>)}</div></Field>
 {invalidRecipients && <p role="alert" className="text-sm text-destructive">{t('请选择有效接收目标；已移除的目标需要更新。', 'Select valid recipients and update any removed targets.')}</p>}
 <Choice label={t('备用渠道', 'Fallback destination')} value={cfg.fallback_id || 'none'} options={[[ 'none', t('无', 'None') ], ...channels.filter(channel => !cfg.channel_ids.includes(channel.id)).map(channel => [channel.id, channel.name] as [string, string])]} onChange={value => setCfg(previous => ({ ...previous, fallback_id: value === 'none' ? '' : value, fallback_chat_id: '' }))} />
 {fallback?.provider === 'feishu_app' && <Choice label={t('备用接收目标', 'Fallback recipient')} value={cfg.fallback_chat_id || 'none'} options={[[ 'none', t('选择目标', 'Select recipient') ], ...(fallback.config.targets || []).map(target => [target.chat_id, target.name] as [string, string])]} onChange={value => update('fallback_chat_id', value === 'none' ? '' : value)} />}
 <Choice label={t('发送频率', 'Frequency')} value={cfg.mode} options={[[ 'immediate', t('即时', 'Immediate') ], [ 'merge', t('五分钟合并', 'Merge over 5 minutes') ], [ 'daily', t('每日摘要', 'Daily digest') ]]} onChange={v => update('mode', v)} />
 <Field label={t('摘要时区', 'Digest timezone')}><Input value={cfg.timezone} onChange={e => update('timezone', e.target.value)} /></Field>{cfg.mode === 'daily' && <Field label={t('摘要小时（0–23）', 'Digest hour (0–23)')}><Input type="number" min={0} max={23} value={cfg.digest_hour} onChange={e => update('digest_hour', Number(e.target.value))} /></Field>}
 <details className="space-y-3"><summary className="cursor-pointer text-sm">{t('范围、静默和模板', 'Scope, quiet hours and template')}</summary>
 <Field label={t('严重程度（不选为全部）', 'Severity (none = all)')}><div className="flex flex-wrap gap-3">{['info', 'warning', 'error', 'critical'].map(v => <Check key={v} label={v} checked={cfg.severities.includes(v)} onChange={() => update('severities', toggle(cfg.severities, v))} />)}</div></Field>
 <Field label={t('节点（不选为全部）', 'Nodes (none = all)')}><div className="space-y-2">{nodes.data?.map(n => <Check key={n.id} label={n.name} checked={cfg.node_ids.includes(n.id)} onChange={() => update('node_ids', toggle(cfg.node_ids, n.id))} />)}</div></Field>
 <Field label={t('节点组（与节点范围取并集）', 'Node groups (combined with selected nodes)')}><div className="space-y-2">{groups.data?.map(g => <Check key={g.id} label={g.name} checked={cfg.group_ids.includes(g.id)} onChange={() => update('group_ids', cfg.group_ids.includes(g.id) ? cfg.group_ids.filter(id => id !== g.id) : [...cfg.group_ids, g.id])} />)}</div></Field>
 <Field label={t('项目名称（逗号分隔）', 'Project names (comma separated)')}><Input value={cfg.projects.join(',')} onChange={e => update('projects', e.target.value.split(',').map(v => v.trim()).filter(Boolean))} /></Field>
 <div className="grid grid-cols-2 gap-3"><Field label={t('静默开始', 'Quiet start')}><Input type="time" value={cfg.quiet_start} onChange={e => update('quiet_start', e.target.value)} /></Field><Field label={t('静默结束', 'Quiet end')}><Input type="time" value={cfg.quiet_end} onChange={e => update('quiet_end', e.target.value)} /></Field></div>
 <Field label={t('临时静默至', 'Mute until')} hint={t('严重安全事件和待审批通知绕过静默。', 'Critical security events and approval requests bypass quiet periods.')}><Input type="datetime-local" value={cfg.muted_until ? new Date(new Date(cfg.muted_until).getTime() - new Date(cfg.muted_until).getTimezoneOffset() * 60000).toISOString().slice(0, 16) : ''} onChange={e => update('muted_until', e.target.value ? new Date(e.target.value).toISOString() : null)} /></Field>
 <Check label={t('发送恢复通知', 'Send recovery notifications')} checked={cfg.recovery} onChange={v => update('recovery', v)} />
 <Field label={t('消息模板（可选）', 'Message template (optional)')} hint="{{title}} {{message}} {{node}} {{resource}} {{time}} {{url}}"><textarea className="min-h-24 rounded-md border bg-transparent p-2" maxLength={4000} value={cfg.template} onChange={e => update('template', e.target.value)} /></Field>
 </details><Check label={t('启用规则', 'Enable rule')} checked={enabled} onChange={setEnabled} /><ErrorText error={save.error || catalog.error} /><Button type="submit" disabled={save.isPending || !cfg.events.length || !cfg.channel_ids.length || enabled && !!invalidRecipients}>{t('保存规则', 'Save rule')}</Button>
 </form>
}
