import { useId, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Button } from '../../components/ui/button'
import { Input } from '../../components/ui/input'
import { Switch } from '../../components/ui/switch'
import { api, ApiError } from '../../lib/api'
import type { DockerNode } from '../../lib/nodes'
import { Check, Choice, ErrorText, Field } from './common'
import { toggle, useOpsText } from './helpers'
import type { AISettings as Settings, AIConnectionTestResult, Binding, Channel } from './types'
import { AIModels } from './ai-models'
import { AIConnectionTest } from './ai-connection-test'
import { ChatAIStatus } from './chat-ai-status'
export function AISettings() {
 const t = useOpsText()
 const query = useQuery({ queryKey: ['ai-settings'], queryFn: () => api<Settings>('/ai/settings') })
 return <div className="space-y-7"><p className="max-w-2xl text-sm text-muted-foreground">{t('内置助手只读取授权节点的脱敏信息。每项变更均需独立审批；关闭后待执行操作失效，运行中的任务请求取消。', 'The assistant reads redacted evidence on authorized nodes. Every change requires individual approval. Disabling AI invalidates pending operations and requests cancellation of running tasks.')}</p><ErrorText error={query.error} />{query.data && <SettingsForm initial={query.data} />}<Bindings settings={query.data} /></div>
}
function SettingSwitch({ label, hint, checked, onChange }: { label: string; hint?: string; checked: boolean; onChange: (checked: boolean) => void }) {
 const id = useId()
 return <div className="flex items-center justify-between gap-4"><div className="min-w-0 space-y-1"><label htmlFor={id} className="cursor-pointer text-sm font-medium">{label}</label>{hint && <p id={`${id}-hint`} className="text-xs text-muted-foreground">{hint}</p>}</div><Switch id={id} aria-describedby={hint ? `${id}-hint` : undefined} checked={checked} onCheckedChange={onChange} /></div>
}
function SettingsForm({ initial }: { initial: Settings }) {
 const t = useOpsText(), client = useQueryClient(), [cfg, setCfg] = useState(() => ({ ...initial, models: initial.models || (initial.model ? [initial.model] : []), allow_insecure: initial.allow_insecure ?? (initial.allow_private && initial.endpoint.startsWith('http://')) })), [key, setKey] = useState('')
 const update = <K extends keyof Settings>(name: K, value: Settings[K]) => { save.reset(); test.reset(); setCfg(prev => ({ ...prev, [name]: value })) }
 const nodes = useQuery({ queryKey: ['nodes'], queryFn: () => api<DockerNode[]>('/nodes') })
 const save = useMutation({ mutationFn: () => api<Settings>('/ai/settings', { method: 'PUT', body: JSON.stringify({ ...cfg, api_key: key }) }), onSuccess: result => { setKey(''); setCfg(result); test.reset(); client.setQueryData(['ai-settings'], result) } })
 const test = useMutation({ mutationFn: () => api<AIConnectionTestResult>('/ai/settings/test', { method: 'POST' }), onMutate: () => { save.reset() }, onSuccess: () => { void client.invalidateQueries({ queryKey: ['ai-settings'] }) } })
 const error = save.error || test.error
 const endpoint = cfg.endpoint.trim().replace(/\/+$/, '')
 const connectionChanged = key !== '' || cfg.endpoint !== initial.endpoint || cfg.protocol !== initial.protocol || cfg.model !== initial.model || cfg.allow_private !== initial.allow_private || cfg.allow_insecure !== Boolean(initial.allow_insecure)
 return <form className="max-w-2xl space-y-5" onSubmit={e => { e.preventDefault(); save.mutate() }}>
 <fieldset disabled={save.isPending || test.isPending} className="min-w-0 space-y-5">
 <div className="rounded-xl bg-muted/40 p-4"><SettingSwitch label={t('启用 AI 运维', 'Enable AI operations')} hint={t('保存后生效；启用前需添加模型并授权节点。', 'Takes effect after saving. Add a model and authorize nodes before enabling.')} checked={cfg.enabled} onChange={v => update('enabled', v)} /></div>
 <Field label={t('模型协议', 'Model protocol')} hint={t('仅支持 Responses API，模型服务需提供 /responses 接口。', 'Only the Responses API is supported. The model service must expose /responses.')}><p className="text-sm">Responses</p></Field>
 <Field label={t('服务地址', 'Service URL')} hint={t('填写 API 基础地址。是否包含 /v1 取决于服务提供方，SUMA 不会自动添加。', 'Enter the API base URL. Include /v1 only if required by the provider; SUMA does not add it automatically.')}><Input placeholder="https://api.example.com/v1" value={cfg.endpoint} onChange={e => update('endpoint', e.target.value)} /></Field>
 <details className="rounded-lg bg-muted/30 p-3 text-xs"><summary className="cursor-pointer font-medium">{t('什么时候需要 /v1？查看实际请求地址', 'When is /v1 needed? View request URLs')}</summary><div className="mt-3 space-y-2 text-muted-foreground"><p>{t('若服务文档给出的完整接口是 https://api.example.com/v1/responses，基础地址应填写 https://api.example.com/v1。若完整接口是 https://gateway.example.com/responses，则填写 https://gateway.example.com。已有 /v1 时不要重复添加，其他前缀（如 /api/v1）按服务文档保留。', 'If the full endpoint is https://api.example.com/v1/responses, enter https://api.example.com/v1. If it is https://gateway.example.com/responses, enter https://gateway.example.com. Keep required prefixes such as /api/v1 and include /v1 only once.')}<br />{t('不要填写 /responses 或 /models；SUMA 根据用途追加这些路径。遇到 404 时先核对基础地址。', 'Do not include /responses or /models; SUMA appends these paths. Check the base URL first if you receive a 404.')}</p><div className="space-y-1 rounded-md bg-muted px-2 py-2 font-mono"><p className="break-all">POST {endpoint}/responses</p><p className="break-all">GET {endpoint}/models</p></div></div></details>
 <Field label={t('API 密钥', 'API key')} hint={cfg.has_secret ? t('已配置，留空保留。', 'Configured; leave blank to retain.') : undefined}><Input type="password" autoComplete="new-password" value={key} onChange={e => { save.reset(); test.reset(); setKey(e.target.value) }} /></Field>
 <div className="space-y-4 rounded-xl border p-4"><SettingSwitch label={t('允许内部模型服务地址', 'Allow an internal model endpoint')} hint={t('允许连接内网或回环地址，例如自托管模型服务。', 'Allow private-network or loopback addresses, such as self-hosted model services.')} checked={cfg.allow_private} onChange={v => update('allow_private', v)} /><SettingSwitch label={t('允许不安全的 AI 连接（HTTP）', 'Allow insecure AI connections (HTTP)')} hint={t('默认关闭。开启后允许明文 HTTP，API 密钥和诊断内容可能被窃听；仅在可信网络中使用。内网 HTTP 需同时开启上方选项。HTTPS 仍校验证书。', 'Off by default. HTTP exposes API keys and diagnosis content to interception; use only on trusted networks. Private HTTP also requires the switch above. HTTPS certificates remain verified.')} checked={cfg.allow_insecure} onChange={v => update('allow_insecure', v)} /><details className="text-xs text-muted-foreground"><summary className="cursor-pointer">{t('HTTP 页面与 Request origin is not allowed', 'HTTP pages and Request origin is not allowed')}</summary><p className="mt-2">{t('同源 HTTP 页面可以使用 AI。此开关控制 SUMA 到模型服务的连接，不会解除页面来源校验。若出现 Request origin is not allowed，请检查反向代理是否保留浏览器访问的 Host 和端口，并核对 SUMA_BROWSER_ORIGIN（协议、主机、端口须与浏览器一致）。来源校验失败时请求尚未到达模型服务。', 'AI works from same-origin HTTP pages. This switch controls SUMA’s connection to the model service and retains browser origin checks. For Request origin is not allowed, preserve the browser-facing Host and port in your reverse proxy and check SUMA_BROWSER_ORIGIN (scheme, host and port must match the browser). The request has not yet reached the model service.')}</p></details></div>
 <AIModels value={cfg.models} connection={{ version: cfg.version, endpoint: cfg.endpoint, api_key: key, allow_private: cfg.allow_private, allow_insecure: cfg.allow_insecure }} onChange={models => { save.reset(); test.reset(); setCfg(previous => ({ ...previous, models, model: models.includes(previous.model) ? previous.model : models[0] || '' })) }} />
 <p className="text-xs text-muted-foreground">{t('新对话、通知渠道对话和自动诊断使用默认模型；工作台可为每轮消息切换模型。', 'New conversations, notification-channel chats and automatic diagnoses use the default model. Switch models per turn in the workbench.')}</p>
 {cfg.models.length > 0 && <Choice label={t('默认模型', 'Default model')} value={cfg.model} options={cfg.models.map(model => [model, model])} onChange={v => update('model', v)} />}
 <Field label={t('授权节点（必须明确选择）', 'Authorized nodes (select explicitly)')} hint={t('同时限制聊天查询范围；非白名单账号只能看到这些节点的安全状态和数量摘要。', 'Also limits chat queries; identities outside the allowlist see safe status and counts for these nodes only.')}><div className="space-y-2">{nodes.data?.map(n => <Check key={n.id} label={n.name} checked={cfg.node_ids.includes(n.id)} onChange={() => update('node_ids', toggle(cfg.node_ids, n.id))} />)}</div></Field>
 <details className="space-y-4"><summary className="cursor-pointer text-sm font-medium">{t('自动分析和用量限制', 'Automatic diagnosis and limits')}</summary>
 <Field label={t('自动分析事件（默认手动）', 'Automatic events (manual by default)')}><div className="space-y-2">{[['container.exited', t('容器异常退出', 'Unexpected exit')], ['container.oom', 'OOM'], ['container.unhealthy', t('健康检查失败', 'Unhealthy')], ['container.restart_loop', t('频繁重启', 'Restart loop')], ['node.offline', t('节点离线', 'Node offline')], ['task.failed', t('任务失败', 'Task failure')], ['image.check_failed', t('镜像检查失败', 'Image check failure')], ['cd.completed', t('发布结果', 'Delivery result')], ['cleanup.completed', t('清理结果', 'Cleanup result')]].map(([id, name]) => <Check key={id} label={name} checked={cfg.auto_events.includes(id)} onChange={() => update('auto_events', toggle(cfg.auto_events, id))} />)}</div></Field>
 <div className="grid gap-4 sm:grid-cols-2">{([['max_concurrent', t('并发诊断数', 'Concurrent diagnoses'), 1, 8], ['daily_auto_limit', t('每日自动诊断次数', 'Automatic diagnoses per day'), 1, 1000], ['max_tool_calls', t('每次只读工具上限', 'Read tool calls per diagnosis'), 1, 32], ['max_iterations', t('任务模型调用上限（跨恢复累计）', 'Model calls per task, including resumes'), 1, 256], ['max_operations', t('任务变更上限（跨恢复累计）', 'Operations per task, including resumes'), 1, 100], ['log_lines', t('日志行数（最近十五分钟）', 'Log lines (last 15 minutes)'), 1, 500], ['log_bytes', t('日志字节上限', 'Log byte limit'), 1024, 65536], ['approval_minutes', t('审批有效期（分钟）', 'Approval expiry (minutes)'), 1, 60]] as const).map(([name, label, min, max]) => <Field key={name} label={label}><Input type="number" min={min} max={max} value={cfg[name]} onChange={e => update(name, Number(e.target.value))} /></Field>)}</div>
 </details>
 <ErrorText error={save.error} />
 {error instanceof ApiError && error.code === 10007 && <p className="text-xs text-muted-foreground">{t('来源校验失败：请让反向代理保留原始 Host（含端口），并将 SUMA_BROWSER_ORIGIN 与浏览器地址保持一致。允许 HTTP 模型连接不能修复此错误。', 'Origin check failed: preserve the original Host (including the port) in your reverse proxy and match SUMA_BROWSER_ORIGIN to the browser address. Allowing HTTP model connections cannot resolve this error.')}</p>}
 <div className="flex flex-wrap items-center gap-3"><Button type="submit" disabled={save.isPending || test.isPending || (cfg.enabled && (!cfg.node_ids.length || !cfg.models.length))}>{save.isPending ? t('保存中…', 'Saving…') : t('保存 AI 设置', 'Save AI settings')}</Button><Button type="button" variant="outline" disabled={test.isPending || save.isPending || !initial.model || connectionChanged} onClick={() => test.mutate()}>{test.isPending ? t('测试中…', 'Testing…') : t('测试连接', 'Test connection')}</Button>{!test.data && !test.error && !test.isPending && <span className="text-xs text-muted-foreground" role="status">{connectionChanged ? t('连接已修改，保存后再测试', 'Connection changed; save before testing') : initial.tool_capable ? t('工具调用可用', 'Tool calling available') : t('尚未验证工具调用', 'Tool calling not verified')}</span>}{save.isSuccess && <span className="text-xs text-muted-foreground" role="status">{t('AI 设置已保存', 'AI settings saved')}</span>}</div>
 <AIConnectionTest result={test.data} error={test.error} pending={test.isPending} model={initial.model} />
 </fieldset></form>
}
function Bindings({ settings }: { settings?: Settings }) {
 const t = useOpsText(), client = useQueryClient(), [channel, setChannel] = useState(''), [code, setCode] = useState(''), [copied, setCopied] = useState(false), [copyError, setCopyError] = useState('')
 const channels = useQuery({ queryKey: ['notification-channels'], queryFn: () => api<Channel[]>('/notifications/channels') })
 const bindings = useQuery({ queryKey: ['notification-bindings'], queryFn: () => api<Binding[]>('/notification-bindings'), refetchInterval: 3000 })
 const eligible = (channels.data || []).filter(c => c.enabled && c.config.interactive)
 const selected = eligible.some(c => c.id === channel) ? channel : channel === '' && eligible.length === 1 ? eligible[0].id : 'none'
 const action = useMutation({ mutationFn: ({ path, method, body }: { path: string; method: string; body?: unknown }) => api<{ code?: string }>(path, { method, body: body ? JSON.stringify(body) : undefined }), onSuccess: (data, input) => { if (data?.code) { setCode(data.code); setCopied(false); setCopyError('') } else if (input.path.endsWith('/confirm')) setCode(''); void client.invalidateQueries({ queryKey: ['notification-bindings'] }) } })
 return <section className="max-w-2xl space-y-4 border-t pt-5"><h3 className="text-sm font-medium">{t('聊天账号绑定与操作白名单', 'Chat identity binding & operator allowlist')}</h3><p className="text-sm text-muted-foreground">{t('生成十分钟有效的一次性码 → 私聊机器人提交 /bind 绑定码 → 返回此处确认稳定平台 ID，加入操作白名单。白名单内的变更仍需逐项审核；撤销后立即恢复只读查询。', 'Generate a one-time code (10 minutes) → send /bind CODE privately → confirm the stable platform ID here to join the operator allowlist. Each change still requires review; revocation immediately restores read-only access.')}</p><p className="text-sm text-muted-foreground">{t('非白名单账号只能查询授权节点的状态和数量摘要，不能访问密钥、凭证、日志、配置、环境变量、任务输出、审批预览或变更操作。', 'Other identities can query status and counts on authorized nodes only. Keys, credentials, logs, configuration, environment values, task output, approval previews and changes are inaccessible.')}</p>
 <ChatAIStatus settings={settings} />
 {settings?.enabled && bindings.data?.some(binding => binding.channel_id === selected && binding.status === 'active') && <p role="status" className="text-sm text-emerald-600 dark:text-emerald-400">{t('此账号已绑定，可直接私聊当前机器人提问。每项变更仍需单独审批。', 'Your account is bound. Ask the selected bot directly in private chat. Each change still requires individual approval.')}</p>}
 <Choice label={t('聊天渠道', 'Chat channel')} value={selected} options={[[ 'none', t('请选择', 'Select') ], ...eligible.map(c => [c.id, c.name] as [string, string])]} onChange={v => { if (action.isPending) return; setChannel(v); setCode(''); setCopied(false); setCopyError('') }} />
 {!eligible.length && <p className="text-xs text-muted-foreground">{t('先在“通知渠道”启用并保存机器人的“聊天诊断和审批”，再生成绑定码。', 'Enable and save chat diagnosis and approvals on a bot in Notification channels before generating a binding code.')}</p>}
 <Button variant="outline" disabled={selected === 'none' || action.isPending} onClick={() => action.mutate({ path: '/notification-bindings', method: 'POST', body: { channel_id: selected } })}>{t('生成绑定码', 'Generate binding code')}</Button>{code && <div className="space-y-2 rounded-md border p-3"><p className="text-xs text-muted-foreground">{t('私聊当前机器人发送以下命令，然后返回此处确认身份。绑定码十分钟有效。', 'Send this command privately to the selected bot, then return here to confirm your identity. The code is valid for 10 minutes.')}</p><p className="break-all font-mono text-sm" role="status">/bind {code}</p><Button variant="ghost" size="sm" onClick={async () => { try { await navigator.clipboard.writeText(`/bind ${code}`); setCopied(true); setCopyError('') } catch { setCopyError(t('复制失败，请选中命令复制。', 'Copy failed. Select and copy the command.')) } }}>{copied ? t('已复制绑定命令', 'Binding command copied') : t('复制绑定命令', 'Copy binding command')}</Button><ErrorText error={copyError} /></div>}<ErrorText error={action.error || bindings.error} />
 <div className="divide-y border-y">{bindings.data?.filter(b => b.status !== 'revoked').map(b => <div key={b.id} className="flex flex-wrap items-center gap-3 py-3 text-sm"><div className="min-w-0 flex-1"><span>{channels.data?.find(c => c.id === b.channel_id)?.name}</span><p className="break-all text-xs text-muted-foreground">{b.external_user_id || t('等待私聊提交', 'Awaiting private message')} · {b.status === 'active' ? t('已绑定 · 操作白名单', 'Bound · Operator allowlist') : b.status === 'claimed' ? t('等待站内确认', 'Awaiting site confirmation') : t('等待私聊提交', 'Awaiting private message')}</p></div>{b.status === 'claimed' && <Button size="sm" disabled={action.isPending} onClick={() => action.mutate({ path: `/notification-bindings/${b.id}/confirm`, method: 'POST' })}>{t('确认并加入操作白名单', 'Confirm and allow operations')}</Button>}<Button size="sm" variant="ghost" disabled={action.isPending} onClick={() => action.mutate({ path: `/notification-bindings/${b.id}`, method: 'DELETE' })}>{t('撤销', 'Revoke')}</Button></div>)}</div>
 </section>
}
