import { useEffect, useState } from 'react'
import { useLocation } from '@tanstack/react-router'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { MoreHorizontal, Plus, Send } from 'lucide-react'
import { Button } from '../../components/ui/button'
import { Input } from '../../components/ui/input'
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '../../components/ui/sheet'
import { Tabs, TabsList, TabsTrigger } from '../../components/ui/tabs'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '../../components/ui/dropdown-menu'
import { Badge } from '../../components/ui/badge'
import { api } from '../../lib/api'
import { useI18n } from '../../lib/i18n'
import { useDateTime } from '../../lib/time-zone'
import type { DockerNode, NodeGroup } from '../../lib/nodes'
import { confirmDialog } from '../../stores/dialog'
import { Check, Choice, ErrorText, Field } from './common'
import { toggle, useOpsText } from './helpers'
import type { Catalog, Channel, ChannelConfig, Delivery, Rule, RuleConfig } from './types'

const platforms: [string, string][] = [['telegram', 'Telegram'], ['feishu_webhook', '飞书 / Feishu Webhook'], ['feishu_app', '飞书 / Feishu App'], ['webhook', 'Webhook']]
const newConfig = (language: string, timeZone: string): ChannelConfig => ({ endpoint: '', chat_id: '', app_id: '', language, timezone: timeZone, allow_private: false, interactive: false, public_url: '' })
const newRule = (timeZone: string): RuleConfig => ({ events: [], severities: [], node_ids: [], group_ids: [], projects: [], channel_ids: [], fallback_id: '', mode: 'immediate', timezone: timeZone, digest_hour: 9, quiet_start: '', quiet_end: '', recovery: true, template: '' })
export function NotificationSettings() {
 const t = useOpsText(), client = useQueryClient(), { formatDateTime } = useDateTime()
 const hash = useLocation({ select: location => location.hash }), requestedTab = new URLSearchParams(hash.split('?')[1] || '').get('tab'), initialTab = requestedTab === 'rules' || requestedTab === 'deliveries' ? requestedTab : 'channels'
 const [tab, setTab] = useState(initialTab), [editing, setEditing] = useState<Channel | 'new' | null>(null), [ruleEdit, setRuleEdit] = useState<Rule | 'new' | null>(null)
 useEffect(() => setTab(initialTab), [initialTab])
 const channels = useQuery({ queryKey: ['notification-channels'], queryFn: () => api<Channel[]>('/notifications/channels'), refetchInterval: 10000 })
 const rules = useQuery({ queryKey: ['notification-rules'], queryFn: () => api<Rule[]>('/notifications/rules') })
 const deliveries = useQuery({ queryKey: ['notification-deliveries'], queryFn: () => api<Delivery[]>('/notifications/deliveries'), enabled: tab === 'deliveries', refetchInterval: 5000 })
 const action = useMutation({ mutationFn: ({ path, method = 'POST', body }: { path: string; method?: string; body?: unknown }) => api(path, { method, body: body ? JSON.stringify(body) : undefined }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['notification-channels'] }); void client.invalidateQueries({ queryKey: ['notification-rules'] }); void client.invalidateQueries({ queryKey: ['notification-deliveries'] }) } })
 const remove = async (path: string, name: string) => { if (await confirmDialog({ title: t(`删除 ${name}？`, `Delete ${name}?`), description: path.includes('/channels/') ? t('待发送消息将停止投递，渠道绑定将撤销。', 'Pending deliveries stop; channel identities are revoked.') : t('此规则的待发送消息将停止投递。', 'Pending deliveries for this rule will stop.'), danger: true, confirmLabel: t('删除', 'Delete') })) action.mutate({ path, method: 'DELETE' }) }
 return <section className="space-y-4">
  <div className="flex flex-wrap items-center justify-between gap-3"><Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="channels">{t('渠道', 'Channels')}</TabsTrigger><TabsTrigger value="rules">{t('通知规则', 'Rules')}</TabsTrigger><TabsTrigger value="deliveries">{t('发送记录', 'Deliveries')}</TabsTrigger></TabsList></Tabs>{tab !== 'deliveries' && <Button size="sm" onClick={() => tab === 'channels' ? setEditing('new') : setRuleEdit('new')}><Plus />{tab === 'channels' ? t('添加通知渠道', 'Add channel') : t('添加规则', 'Add rule')}</Button>}</div>
  <p className="text-sm text-muted-foreground">{t('站内事件始终保留。通过规则选择外部渠道和通知频率。', 'Events remain available in your inbox. Rules select external destinations and delivery frequency.')}</p>
  <ErrorText error={action.error || channels.error || rules.error || deliveries.error} />
  {tab === 'channels' && <div className="divide-y border-y">{channels.data?.map(row => <div key={row.id} className="flex items-center gap-3 py-3"><Send className="size-4 shrink-0 text-muted-foreground" /><div className="min-w-0 flex-1"><button onClick={() => setEditing(row)} className="truncate font-medium hover:underline">{row.name}</button><p className="text-xs text-muted-foreground">{platforms.find(([id]) => id === row.provider)?.[1]} · {row.config.interactive ? t('通知、聊天与审批', 'Notifications, chat & approval') : t('通知', 'Notifications')} · {row.last_error || (row.last_sent_at ? formatDateTime(row.last_sent_at) : t('尚未发送', 'No deliveries yet'))}</p></div><Badge variant={row.enabled ? 'secondary' : 'outline'}>{row.enabled ? t('启用', 'Enabled') : t('停用', 'Paused')}</Badge><DropdownMenu><DropdownMenuTrigger render={<Button variant="ghost" size="icon-sm" aria-label={t('渠道操作', 'Channel actions')}><MoreHorizontal /></Button>} /><DropdownMenuContent><DropdownMenuItem onClick={() => setEditing(row)}>{t('编辑', 'Edit')}</DropdownMenuItem><DropdownMenuItem onClick={() => action.mutate({ path: `/notifications/channels/${row.id}/test` })}>{t('发送测试', 'Send test')}</DropdownMenuItem><DropdownMenuItem onClick={() => action.mutate({ path: `/notifications/channels/${row.id}`, method: 'PUT', body: { name: row.name, provider: row.provider, enabled: !row.enabled, version: row.version, config: row.config } })}>{row.enabled ? t('暂停', 'Pause') : t('启用', 'Enable')}</DropdownMenuItem><DropdownMenuItem onClick={() => { void remove(`/notifications/channels/${row.id}`, row.name) }}>{t('删除', 'Delete')}</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>)}{channels.data?.length === 0 && <p className="py-10 text-center text-sm text-muted-foreground">{t('添加第一个渠道，接收重要事件。', 'Add your first channel to receive important events.')}</p>}</div>}
  {tab === 'rules' && <div className="divide-y border-y">{rules.data?.map(row => <div key={row.id} className="flex items-center gap-3 py-3"><div className="min-w-0 flex-1"><button className="font-medium hover:underline" onClick={() => setRuleEdit(row)}>{row.name}</button><p className="text-xs text-muted-foreground">{row.config.events.length} {t('种事件', 'events')} · {row.config.mode} · {row.config.channel_ids.map(id => channels.data?.find(c => c.id === id)?.name).join(', ')}</p></div><Badge variant="outline">{row.enabled ? t('启用', 'Enabled') : t('停用', 'Paused')}</Badge><DropdownMenu><DropdownMenuTrigger render={<Button variant="ghost" size="icon-sm" aria-label={t('规则操作', 'Rule actions')}><MoreHorizontal /></Button>} /><DropdownMenuContent><DropdownMenuItem onClick={() => setRuleEdit(row)}>{t('编辑', 'Edit')}</DropdownMenuItem><DropdownMenuItem onClick={() => action.mutate({ path: `/notifications/rules/${row.id}`, method: 'PUT', body: { name: row.name, enabled: !row.enabled, version: row.version, config: row.config } })}>{row.enabled ? t('暂停', 'Pause') : t('启用', 'Enable')}</DropdownMenuItem><DropdownMenuItem onClick={() => { void remove(`/notifications/rules/${row.id}`, row.name) }}>{t('删除', 'Delete')}</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>)}{rules.data?.length === 0 && <p className="py-10 text-center text-sm text-muted-foreground">{t('使用预设创建规则，也可以自选事件。', 'Start with a preset or choose your own events.')}</p>}</div>}
  {tab === 'deliveries' && <div className="divide-y border-y">{deliveries.data?.map(row => <div key={row.id} className="flex flex-wrap items-center gap-3 py-3 text-sm"><span className="flex-1">{channels.data?.find(c => c.id === row.channel_id)?.name || row.channel_id}<span className="block text-xs text-muted-foreground">{formatDateTime(row.created_at)} · {row.reason || `${row.attempts} ${t('次尝试', 'attempts')}`}</span></span><Badge variant="outline">{row.status}</Badge>{['failed', 'suppressed', 'sent'].includes(row.status) && <Button size="sm" variant="ghost" disabled={action.isPending} onClick={() => action.mutate({ path: `/notifications/deliveries/${row.id}/resend` })}>{t('重发', 'Resend')}</Button>}</div>)}</div>}
  <Sheet open={editing !== null} onOpenChange={open => { if (!open) setEditing(null) }}><SheetContent className="w-full gap-0 sm:max-w-xl"><SheetHeader className="border-b"><SheetTitle>{t('配置通知渠道', 'Configure channel')}</SheetTitle><SheetDescription>{t('平台 → 必要信息 → 测试 → 订阅', 'Platform → Credentials → Test → Subscribe')}</SheetDescription></SheetHeader>{editing && <ChannelEditor key={editing === 'new' ? 'new' : editing.id} row={editing === 'new' ? undefined : editing} onDone={() => setEditing(null)} onSubscribe={() => { setEditing(null); setTab('rules'); setRuleEdit('new') }} />}</SheetContent></Sheet>
  <Sheet open={ruleEdit !== null} onOpenChange={open => { if (!open) setRuleEdit(null) }}><SheetContent className="w-full gap-0 sm:max-w-xl"><SheetHeader className="border-b"><SheetTitle>{t('通知规则', 'Notification rule')}</SheetTitle><SheetDescription>{t('选择事件、目标和降噪方式', 'Choose events, destinations and noise controls')}</SheetDescription></SheetHeader>{ruleEdit && <RuleEditor key={ruleEdit === 'new' ? 'new' : ruleEdit.id} row={ruleEdit === 'new' ? undefined : ruleEdit} channels={channels.data || []} onDone={() => setRuleEdit(null)} />}</SheetContent></Sheet>
 </section>
}
function ChannelEditor({ row, onDone, onSubscribe }: { row?: Channel; onDone: () => void; onSubscribe: () => void }) {
 const t = useOpsText(), { language } = useI18n(), { timeZone } = useDateTime(), client = useQueryClient()
 const [step, setStep] = useState(row ? 1 : 0), [provider, setProvider] = useState(row?.provider || 'telegram'), [name, setName] = useState(row?.name || ''), [enabled, setEnabled] = useState(row?.enabled ?? true), [cfg, setCfg] = useState<ChannelConfig>(row?.config || newConfig(language, timeZone)), [secret, setSecret] = useState(''), [signing, setSigning] = useState(''), [authorization, setAuthorization] = useState(''), [saved, setSaved] = useState<Channel | undefined>(row), [testMessage, setTestMessage] = useState('')
 const update = <K extends keyof ChannelConfig>(key: K, value: ChannelConfig[K]) => setCfg(prev => ({ ...prev, [key]: value }))
 const save = useMutation({ mutationFn: () => api<Channel>(`/notifications/channels${saved ? `/${saved.id}` : ''}`, { method: saved ? 'PUT' : 'POST', body: JSON.stringify({ name, provider, enabled, version: saved?.version || 0, config: cfg, secrets: { token: secret, signing_key: signing, authorization } }) }), onSuccess: result => { setSaved(result); setSecret(''); setSigning(''); setAuthorization(''); setStep(2); void client.invalidateQueries({ queryKey: ['notification-channels'] }) } })
 const test = useMutation({ mutationFn: (kind: string) => api(`/notifications/channels/${saved?.id}/${kind}`, { method: 'POST' }), onSuccess: (_, kind) => setTestMessage(kind === 'test' ? t('测试消息已发送', 'Test message sent') : t('凭证校验成功，请继续验证消息和审批回调。', 'Credentials verified. Continue testing messages and approval callbacks.')) })
 const chats = useQuery({ queryKey: ['notification-chats', saved?.id], queryFn: () => api<{ chat_id: string; name: string; private: boolean }[]>(`/notifications/channels/${saved?.id}/chats`), enabled: !!saved && cfg.interactive, refetchInterval: 5000 })
 return <div className="space-y-5 overflow-y-auto p-5">
  <div className="text-xs text-muted-foreground">{step + 1} / 3</div>
  {step === 0 ? <><Choice label={t('选择平台', 'Platform')} value={provider} options={platforms} onChange={setProvider} /><p className="text-sm text-muted-foreground">{t('Telegram 和飞书应用机器人支持聊天诊断与逐项审批；Webhook 用于发送通知。', 'Telegram and Feishu application bots support chat diagnosis and individual approvals. Webhooks deliver notifications.')}</p><Button onClick={() => setStep(1)}>{t('下一步', 'Next')}</Button></> : <>
   <Field label={t('渠道名称', 'Channel name')}><Input value={name} onChange={e => setName(e.target.value)} /></Field>
   <p className="text-xs text-muted-foreground">{platforms.find(([id]) => id === provider)?.[1]}</p>
   {provider === 'feishu_app' && <><FeishuPermissions /><Field label="App ID"><Input value={cfg.app_id} onChange={e => update('app_id', e.target.value)} placeholder="cli_…" autoComplete="off" /></Field></>}
   {(provider === 'telegram' || provider === 'feishu_app') && <Field label={provider === 'telegram' ? 'Bot Token' : 'App Secret'} hint={saved?.has_secrets ? t('密钥已配置；留空保留。', 'Secret configured; leave blank to retain.') : undefined}><Input type="password" autoComplete="new-password" value={secret} onChange={e => setSecret(e.target.value)} /></Field>}
   {(provider === 'webhook' || provider === 'feishu_webhook') && <><Field label="Webhook URL" hint={saved?.has_secrets ? t('地址已加密保存，留空保留。', 'URL is encrypted; leave blank to retain.') : undefined}><Input type="password" autoComplete="off" placeholder="https://…" value={cfg.endpoint} onChange={e => update('endpoint', e.target.value)} /></Field><Field label={t('签名密钥（可选）', 'Signing key (optional)')}><Input type="password" autoComplete="new-password" value={signing} onChange={e => setSigning(e.target.value)} /></Field></>}
   {provider === 'webhook' && <><Field label={t('Authorization（可选）', 'Authorization (optional)')}><Input type="password" autoComplete="new-password" value={authorization} onChange={e => setAuthorization(e.target.value)} /></Field><Check label={t('允许内部网络地址', 'Allow internal network destination')} checked={cfg.allow_private} onChange={v => update('allow_private', v)} /></>}
   {['telegram', 'feishu_app'].includes(provider) && <><Check label={t('启用聊天诊断和审批', 'Enable chat diagnosis and approvals')} checked={cfg.interactive} onChange={v => update('interactive', v)} /><p className="text-xs text-muted-foreground">{t('非白名单用户仅能查询安全状态和数量摘要。站内确认绑定后进入操作白名单，每项变更仍需审核；查询不会返回密钥、凭证或原始配置和日志。', 'Other users can query safe status and counts only. A site-confirmed binding joins the operator allowlist; every change still requires review. Guest queries never return keys, credentials, raw configuration or logs.')}</p><Field label={t('通知会话 ID', 'Notification chat ID')} hint={t('启用渠道后私聊机器人，或在群中 @ 机器人；已识别会话会显示在下方。绑定必须使用私聊。', 'Enable the channel, then message the bot privately or mention it in a group. Detected chats appear below. Identity binding requires a private chat.')}><Input value={cfg.chat_id} onChange={e => update('chat_id', e.target.value)} /></Field>{chats.data?.map(chat => <Button key={chat.chat_id} variant="ghost" className="w-full justify-start truncate" onClick={() => update('chat_id', chat.chat_id)}>{chat.name} · {chat.chat_id}</Button>)}</>}
   <details className="space-y-3"><summary className="cursor-pointer text-sm">{t('语言、时区与详情链接', 'Language, timezone and detail links')}</summary><Choice label={t('消息语言', 'Message language')} value={cfg.language} options={[[ 'zh-CN', '中文' ], [ 'en-US', 'English' ]]} onChange={v => update('language', v)} /><Field label={t('IANA 时区', 'IANA timezone')}><Input value={cfg.timezone} onChange={e => update('timezone', e.target.value)} /></Field><Field label={t('SUMA 公网地址（可选）', 'SUMA public URL (optional)')}><Input placeholder="https://suma.example.com" value={cfg.public_url} onChange={e => update('public_url', e.target.value)} /></Field></details>
   <Check label={t('启用此渠道（也可停用保存）', 'Enable channel (or save paused)')} checked={enabled} onChange={setEnabled} />
   <ErrorText error={save.error || test.error || chats.error} />
   <div className="flex flex-wrap gap-2"><Button disabled={save.isPending || !name} onClick={() => save.mutate()}>{t('保存并测试', 'Save and test')}</Button>{saved && <Button variant="outline" disabled={test.isPending} onClick={() => test.mutate('test')}>{t('发送测试消息', 'Send test message')}</Button>}{saved && ['feishu_app', 'telegram'].includes(provider) && <Button variant="outline" disabled={test.isPending} onClick={() => test.mutate('check')}>{t('检查凭证', 'Check credentials')}</Button>}</div>
   {testMessage && <p role="status" className="text-sm text-emerald-600 dark:text-emerald-400">{testMessage}</p>}
   {step === 2 && <div className="flex gap-2 border-t pt-4"><Button onClick={onSubscribe}>{t('选择通知订阅', 'Choose subscriptions')}</Button><Button variant="ghost" onClick={onDone}>{t('完成', 'Done')}</Button></div>}
  </>}
 </div>
}
function FeishuPermissions() {
 const t = useOpsText()
 return <div className="space-y-3 rounded-md border bg-muted/30 p-3 text-xs leading-5">
 <p className="font-medium">{t('飞书应用配置要求', 'Feishu application requirements')}</p>
 <p>{t('在开放平台创建企业自建应用，开启机器人能力并配置可用范围。权限以“应用身份”开通，发布新版本后生效。', 'Create an internal app, enable the bot and configure its visibility. Grant permissions as the application and publish a version for changes to take effect.')}</p>
 <ul className="list-disc space-y-1 pl-4"><li><code>im:message:send_as_bot</code> — {t('必需：以机器人身份发送通知和回复', 'Required: send notifications and replies as the bot')}</li><li><code>im:message.p2p_msg:readonly</code> — {t('聊天必需：接收用户发给机器人的私聊消息', 'Required for chat: receive private messages sent to the bot')}</li><li><code>im:message.group_at_msg:readonly</code> — {t('可选：接收群内 @ 此机器人的消息', 'Optional: receive group messages mentioning this bot')}</li></ul>
 <p>{t('事件与回调 → 使用长连接接收；事件订阅 im.message.receive_v1；回调订阅 card.action.trigger。不需要填写公网回调地址。', 'Events & callbacks → use a persistent connection. Subscribe to im.message.receive_v1 events and card.action.trigger callbacks. A public callback URL is unnecessary.')}</p>
 <p>{t('将机器人加入目标群，或先私聊机器人。普通群成员没有 SUMA 权限；聊天审批需要完成站内身份绑定。', 'Add the bot to the target group or message it privately first. Group membership grants no SUMA access; chat approval requires identity binding.')}</p>
 <a href="https://open.feishu.cn/document/server-docs/im-v1/message/create" target="_blank" rel="noreferrer" className="underline">{t('飞书发送消息与权限文档', 'Feishu message and permission documentation')}</a> · <a href="https://github.com/larksuite/oapi-sdk-go/blob/v3_main/doc/channel.zh.md" target="_blank" rel="noreferrer" className="underline">{t('官方长连接配置', 'Official connection setup')}</a>
 </div>
}
function RuleEditor({ row, channels, onDone }: { row?: Rule; channels: Channel[]; onDone: () => void }) {
 const t = useOpsText(), { timeZone } = useDateTime(), client = useQueryClient()
 const [preset, setPreset] = useState('custom'), [name, setName] = useState(row?.name || ''), [enabled, setEnabled] = useState(row?.enabled ?? true), [cfg, setCfg] = useState<RuleConfig>(row?.config || newRule(timeZone))
 const update = <K extends keyof RuleConfig>(key: K, value: RuleConfig[K]) => setCfg(prev => ({ ...prev, [key]: value }))
 const catalog = useQuery({ queryKey: ['notification-catalog'], queryFn: () => api<Catalog>('/notifications/catalog') })
 const nodes = useQuery({ queryKey: ['nodes'], queryFn: () => api<DockerNode[]>('/nodes') }), groups = useQuery({ queryKey: ['node-groups'], queryFn: () => api<NodeGroup[]>('/node-groups') })
 const save = useMutation({ mutationFn: () => api(`/notifications/rules${row ? `/${row.id}` : ''}`, { method: row ? 'PUT' : 'POST', body: JSON.stringify({ name, enabled, version: row?.version || 0, config: cfg }) }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['notification-rules'] }); onDone() } })
 return <form className="space-y-4 overflow-y-auto p-5" onSubmit={e => { e.preventDefault(); save.mutate() }}>
 <Field label={t('规则名称', 'Rule name')}><Input value={name} onChange={e => setName(e.target.value)} required /></Field>
 <Choice label={t('使用预设', 'Use preset')} value={preset} options={[[ 'custom', t('自定义', 'Custom') ], ['security', t('账户安全', 'Account security')], ['important', t('重要异常', 'Important incidents')], ['images', t('镜像更新', 'Image updates')], ['delivery', t('发布动态', 'Delivery updates')], ['cleanup', t('清理报告', 'Cleanup reports')]]} onChange={key => { setPreset(key); if (catalog.data?.presets[key]) { update('events', catalog.data.presets[key]); if (!name) setName(key) } }} />
 <details open><summary className="mb-2 cursor-pointer text-sm font-medium">{t('事件', 'Events')} · {cfg.events.length}</summary><div className="grid gap-2 sm:grid-cols-2">{catalog.data?.events.map(e => <Check key={e.type} label={t(e.title, e.title_en)} checked={cfg.events.includes(e.type)} onChange={() => update('events', toggle(cfg.events, e.type))} />)}</div></details>
 <Field label={t('目标渠道', 'Destinations')}><div className="space-y-2">{channels.map(c => <Check key={c.id} label={c.name} checked={cfg.channel_ids.includes(c.id)} onChange={() => update('channel_ids', toggle(cfg.channel_ids, c.id))} />)}</div></Field>
 <Choice label={t('备用渠道', 'Fallback destination')} value={cfg.fallback_id || 'none'} options={[[ 'none', t('无', 'None') ], ...channels.map(c => [c.id, c.name] as [string, string])]} onChange={v => update('fallback_id', v === 'none' ? '' : v)} />
 <Choice label={t('发送频率', 'Frequency')} value={cfg.mode} options={[[ 'immediate', t('即时', 'Immediate') ], [ 'merge', t('五分钟合并', 'Merge over 5 minutes') ], [ 'daily', t('每日摘要', 'Daily digest') ]]} onChange={v => update('mode', v)} />
 <Field label={t('摘要时区', 'Digest timezone')}><Input value={cfg.timezone} onChange={e => update('timezone', e.target.value)} /></Field>{cfg.mode === 'daily' && <Field label={t('摘要小时（0–23）', 'Digest hour (0–23)')}><Input type="number" min={0} max={23} value={cfg.digest_hour} onChange={e => update('digest_hour', Number(e.target.value))} /></Field>}
 <details className="space-y-3"><summary className="cursor-pointer text-sm">{t('范围、静默和模板', 'Scope, quiet hours and template')}</summary>
 <Field label={t('严重程度（不选为全部）', 'Severity (none = all)')}><div className="flex flex-wrap gap-3">{['info', 'warning', 'error', 'critical'].map(v => <Check key={v} label={v} checked={cfg.severities.includes(v)} onChange={() => update('severities', toggle(cfg.severities, v))} />)}</div></Field>
 <Field label={t('节点（不选为全部）', 'Nodes (none = all)')}><div className="space-y-2">{nodes.data?.map(n => <Check key={n.id} label={n.name} checked={cfg.node_ids.includes(n.id)} onChange={() => update('node_ids', toggle(cfg.node_ids, n.id))} />)}</div></Field>
 <Field label={t('节点组（与节点范围取并集）', 'Node groups (combined with selected nodes)')}><div className="space-y-2">{groups.data?.map(g => <Check key={g.id} label={g.name} checked={cfg.group_ids.includes(g.id)} onChange={() => update('group_ids', cfg.group_ids.includes(g.id) ? cfg.group_ids.filter(id => id !== g.id) : [...cfg.group_ids, g.id])} />)}</div></Field>
 <Field label={t('项目名称（逗号分隔）', 'Project names (comma separated)')}><Input value={cfg.projects.join(',')} onChange={e => update('projects', e.target.value.split(',').map(v => v.trim()).filter(Boolean))} /></Field>
 <div className="grid grid-cols-2 gap-3"><Field label={t('静默开始', 'Quiet start')}><Input type="time" value={cfg.quiet_start} onChange={e => update('quiet_start', e.target.value)} /></Field><Field label={t('静默结束', 'Quiet end')}><Input type="time" value={cfg.quiet_end} onChange={e => update('quiet_end', e.target.value)} /></Field></div>
 <Field label={t('临时静默至', 'Mute until')} hint={t('严重安全事件和待审批通知绕过静默。', 'Critical security events and approval requests bypass quiet periods.')}><Input type="datetime-local" value={cfg.muted_until ? new Date(new Date(cfg.muted_until).getTime() - new Date(cfg.muted_until).getTimezoneOffset() * 60000).toISOString().slice(0, 16) : ''} onChange={e => update('muted_until', e.target.value ? new Date(e.target.value).toISOString() : null)} /></Field>
 <Check label={t('发送恢复通知', 'Send recovery notifications')} checked={cfg.recovery} onChange={v => update('recovery', v)} />
 <Field label={t('消息模板（可选）', 'Message template (optional)')} hint="{{title}} {{message}} {{node}} {{resource}} {{time}} {{url}}"><textarea className="min-h-24 rounded-md border bg-transparent p-2" maxLength={4000} value={cfg.template} onChange={e => update('template', e.target.value)} /></Field>
 </details><Check label={t('启用规则', 'Enable rule')} checked={enabled} onChange={setEnabled} /><ErrorText error={save.error || catalog.error} /><Button type="submit" disabled={save.isPending || !cfg.events.length || !cfg.channel_ids.length}>{t('保存规则', 'Save rule')}</Button>
 </form>
}
