export interface ChannelTarget { chat_id: string; name: string }
export interface ConnectionStatus { state: 'stopped' | 'connecting' | 'connected' | 'reconnecting' | 'error'; error?: string }
export interface ChannelConfig { endpoint: string; chat_id: string; app_id: string; targets?: ChannelTarget[]; language: string; timezone: string; allow_private: boolean; interactive: boolean; public_url: string }
export interface Channel { id: string; name: string; provider: string; enabled: boolean; version: number; config: ChannelConfig; has_secrets: boolean; last_error?: string; last_sent_at?: string }
export interface RuleConfig { events: string[]; severities: string[]; node_ids: string[]; group_ids: number[]; projects: string[]; channel_ids: string[]; channel_targets?: Record<string, string[]>; fallback_chat_id?: string; fallback_id: string; mode: string; timezone: string; digest_hour: number; quiet_start: string; quiet_end: string; muted_until?: string | null; recovery: boolean; template: string }
export interface Rule { id: string; name: string; enabled: boolean; version: number; config: RuleConfig }
export interface Catalog { events: { type: string; category: string; title: string; title_en: string }[]; presets: Record<string, string[]> }
export interface Delivery { id: string; channel_id: string; chat_id?: string; status: string; reason: string; attempts: number; due_at: string; created_at: string }
export interface NotificationEvent { id: string; type: string; severity: string; time: string; node_id: string; node_name: string; resource_id: string; title: string; message: string; task_id: string; run_id: string; operation_id: string; read: boolean }
export interface Inbox { items: NotificationEvent[]; unread: number }
export interface Binding { id: string; channel_id: string; external_user_id: string; external_name: string; chat_id: string; status: string; expires_at: string }
export interface AISettings { version: number; enabled: boolean; protocol: 'responses'; endpoint: string; model: string; models: string[]; allow_private: boolean; allow_insecure: boolean; node_ids: string[]; auto_events: string[]; max_concurrent: number; daily_auto_limit: number; max_tool_calls: number; max_iterations: number; max_operations: number; log_lines: number; log_bytes: number; approval_minutes: number; has_secret: boolean; tool_capable: boolean }
export interface AIConnectionTestResult { text: boolean; tool_capable: boolean; summary_only?: boolean; model?: string; duration_ms?: number; text_response?: string; tool_failure?: 'request_failed' | 'not_called' | 'unexpected_call' | 'invalid_arguments'; tool_error?: string }
export interface Evidence { node_id?: string; source: string; resource: string; time: string; content: string; unavailable: boolean }
export interface AIRun { model?: string; id: string; event_id?: string; node_id: string; question: string; status: string; error: string; tokens: number; created_at: string; conversation_id: string; revision: number; phase: string; task_progress?: number; task_status?: string; target_node_ids: string[]; target_source: string; steps: AIPlanStep[]; interaction?: AIInteraction; result: { summary: string; evidence: Evidence[]; operation_ids: string[]; missing: string[] } }
export interface AIOperation { id: string; run_id: string; node_id: string; action: string; resource_id: string; title: string; impact: string; parameters: unknown; snapshot: { details: unknown; fingerprint: string }; review_token: string; status: string; task_id: string; result: string; expires_at: string; approval_source: string; confirmations: AIConfirmation[]; verification?: { satisfied: boolean; summary: string; evidence: Evidence[] } }

export interface AIConversationRecord { id: string; title: string; source: string; current_run_id: string; revision: number; event_seq: number; created_at: string; updated_at: string }
export interface AIConversationDetail extends AIConversationRecord { context: { node_ids?: string[]; resource_node_id?: string; resource_kind?: string; resource_id?: string }; messages: { id: string; run_id: string; role: string; content: string; created_at: string }[]; runs: AIRun[]; current_run?: AIRun }
export interface AIResourceOption { id: string; name: string; node_id: string; kind: string; detail?: string }
export interface AIInteraction { id: string; run_id: string; revision: number; kind: string; prompt: string; multiple: boolean; status: string; expires_at: string; options: AIResourceOption[] }
export interface AIPlanStep { id: string; position: number; title: string; node_id: string; action: string; resource_id: string; status: string; operation_id: string; expected: string }
export interface AIConfirmation { key: string; label: string; expected: string; warning?: string; checkbox?: boolean }
