export interface ChannelConfig { endpoint: string; chat_id: string; app_id: string; language: string; timezone: string; allow_private: boolean; interactive: boolean; public_url: string }
export interface Channel { id: string; name: string; provider: string; enabled: boolean; version: number; config: ChannelConfig; has_secrets: boolean; last_error?: string; last_sent_at?: string }
export interface RuleConfig { events: string[]; severities: string[]; node_ids: string[]; group_ids: number[]; projects: string[]; channel_ids: string[]; fallback_id: string; mode: string; timezone: string; digest_hour: number; quiet_start: string; quiet_end: string; muted_until?: string | null; recovery: boolean; template: string }
export interface Rule { id: string; name: string; enabled: boolean; version: number; config: RuleConfig }
export interface Catalog { events: { type: string; category: string; title: string; title_en: string }[]; presets: Record<string, string[]> }
export interface Delivery { id: string; channel_id: string; status: string; reason: string; attempts: number; due_at: string; created_at: string }
export interface NotificationEvent { id: string; type: string; severity: string; time: string; node_id: string; node_name: string; resource_id: string; title: string; message: string; task_id: string; run_id: string; operation_id: string; read: boolean }
export interface Inbox { items: NotificationEvent[]; unread: number }
export interface Binding { id: string; channel_id: string; external_user_id: string; external_name: string; chat_id: string; status: string; expires_at: string }
export interface AISettings { version: number; enabled: boolean; protocol: string; endpoint: string; model: string; allow_private: boolean; node_ids: string[]; auto_events: string[]; max_concurrent: number; daily_auto_limit: number; max_tool_calls: number; log_lines: number; log_bytes: number; approval_minutes: number; has_secret: boolean; tool_capable: boolean }
export interface Evidence { source: string; resource: string; time: string; content: string; unavailable: boolean }
export interface AIRun { id: string; event_id?: string; node_id: string; question: string; status: string; error: string; tokens: number; created_at: string; parent_id: string; result: { summary: string; evidence: Evidence[]; operation_ids: string[]; missing: string[] } }
export interface AIOperation { id: string; run_id: string; node_id: string; action: string; resource_id: string; title: string; impact: string; parameters: unknown; snapshot: { details: unknown; fingerprint: string }; review_token: string; status: string; task_id: string; result: string; expires_at: string; approval_source: string }
