import { useEffect, useState } from 'react'
import { Link, useLocation } from '@tanstack/react-router'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Sparkles } from 'lucide-react'
import { Button } from '../../components/ui/button'
import { Badge } from '../../components/ui/badge'
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '../../components/ui/sheet'
import { Tabs, TabsList, TabsTrigger } from '../../components/ui/tabs'
import { api } from '../../lib/api'
import { cn } from '../../lib/utils'
import { useDateTime } from '../../lib/time-zone'
import { useUIStore } from '../../stores/ui'
import { ResourceFrame } from '../../pages/images'
import { Check, ErrorText, Field } from './common'
import { useOpsText } from './helpers'
import type { AIOperation, Inbox } from './types'
import { AIConversation } from './conversation'
export function AIAnalyzeButton({ kind, id, nodeID }: { kind: string; id: string; nodeID?: string }) { const currentNodeID = useUIStore(s => s.currentNodeID), t = useOpsText(); return <Button size="sm" variant="ghost" nativeButton={false} render={<Link to="/ai-operations" hash={new URLSearchParams({ kind, resource: id, node: nodeID || currentNodeID }).toString()} />}><Sparkles />{t('交给 AI 分析', 'Analyze with AI')}</Button> }
export function AIWorkbench() {
 const t = useOpsText(), { formatDateTime } = useDateTime(), hash = useLocation({ select: l => l.hash }), source = new URLSearchParams(hash)
 const node = source.get('node') || '', [scopeNode, setScopeNode] = useState(''), [model, setModel] = useState(''), [selected, setSelected] = useState(source.get('run') || ''), [question, setQuestion] = useState(''), [tab, setTab] = useState(source.get('tab') || (hash && !hash.includes('=') ? 'operations' : 'diagnoses')), [operation, setOperation] = useState(source.get('operation') || (hash && !hash.includes('=') ? hash : ''))
 useEffect(() => { const p = new URLSearchParams(hash); if (p.get('run')) { setSelected(p.get('run')!); setTab('diagnoses') } if (p.get('kind')) { setSelected(''); setTab('diagnoses') } if (p.get('tab')) setTab(p.get('tab')!); if (p.get('operation') || hash && !hash.includes('=')) { setOperation(p.get('operation') || hash); setTab('operations') } }, [hash])
 const operations = useQuery({ queryKey: ['ai-operations'], queryFn: () => api<AIOperation[]>('/ai/operations'), refetchInterval: 2000 })
 const audits = useQuery({ queryKey: ['ai-audit'], queryFn: () => api<{ id: number; action: string; source: string; resource: string; result: string; created_at: string; operation_id: string; run_id: string; task_id: string; node_id: string; user_id: number }[]>('/ai/audit'), enabled: tab === 'audit', refetchInterval: 5000 })
 const pending = operations.data?.filter(o => o.status === 'awaiting_approval') || []
 return <ResourceFrame title={t('AI 工作台', 'AI workbench')} detail={t('跨节点对话、诊断和逐项操作审核', 'Conversations, diagnosis and individual review across nodes')} action={<Button variant="outline" nativeButton={false} render={<Link to="/settings" hash="ai" />}>{t('AI 设置', 'AI settings')}</Button>}>
 <div className="space-y-4"><Tabs value={tab} onValueChange={setTab}><TabsList><TabsTrigger value="diagnoses">{t('会话与诊断', 'Conversations')}</TabsTrigger><TabsTrigger value="operations">{t('操作审核', 'Operation review')} · {pending.length}</TabsTrigger><TabsTrigger value="audit">{t('审计记录', 'Audit history')}</TabsTrigger></TabsList></Tabs><ErrorText error={operations.error || audits.error} />
 {tab === 'diagnoses' && <AIConversation selected={selected} onSelect={setSelected} node={node} scopeNode={scopeNode} setScopeNode={setScopeNode} model={model} setModel={setModel} resourceKind={source.get('kind') || ''} resourceID={source.get('resource') || ''} operations={operations.data || []} renderOperation={op => <OperationRow op={op} onOpen={() => setOperation(op.id)} className="rounded-md px-3 py-2" />} question={question} setQuestion={setQuestion} />}
 {tab === 'operations' && <div className="divide-y border-y">{operations.data?.map(o => <OperationRow key={o.id} op={o} onOpen={() => setOperation(o.id)} />)}{operations.data?.length === 0 && <p className="py-10 text-center text-sm text-muted-foreground">{t('还没有操作提案', 'No operation proposals yet')}</p>}</div>}
 {tab === 'audit' && <div><div className="mb-3 flex flex-wrap justify-between gap-2 text-xs text-muted-foreground"><span>{t('全局审计日志中的 AI 记录', 'AI records from the global audit log')}</span><Link to="/audit-logs" className="underline">{t('查看全部审计日志', 'View all audit logs')}</Link></div><div className="divide-y border-y">{audits.data?.map(a => <div key={a.id} className="py-3 text-sm"><span>{a.action} · {a.resource} · {a.result}</span><p className="text-xs text-muted-foreground">{formatDateTime(a.created_at)} · {a.source} · {a.user_id ? `user ${a.user_id}` : t('访客', 'guest')} · {a.node_id} · {a.operation_id}</p>{(a.operation_id || a.run_id) && <Link to="/ai-operations" hash={new URLSearchParams(a.operation_id ? { operation: a.operation_id } : { run: a.run_id }).toString()} className="mr-3 text-xs underline">{t('查看 AI 记录', 'View AI record')}</Link>}{a.task_id && <Link to="/tasks" hash={a.task_id} className="text-xs underline">{t('查看任务', 'View task')}</Link>}</div>)}</div></div>}
 <Sheet open={!!operation} onOpenChange={open => { if (!open) setOperation('') }}><SheetContent className="w-full gap-0 sm:max-w-xl"><SheetHeader className="border-b"><SheetTitle>{t('操作完整预览', 'Full operation preview')}</SheetTitle><SheetDescription>{t('核对影响后单独批准此项操作。', 'Review the impact and approve this individual operation.')}</SheetDescription></SheetHeader>{operation && <OperationReview key={operation} id={operation} />}</SheetContent></Sheet>
 </div></ResourceFrame>
}
function OperationRow({ op, onOpen, className }: { op: AIOperation; onOpen: () => void; className?: string }) { const t = useOpsText(); return <button onClick={onOpen} className={cn('flex w-full flex-wrap items-center gap-3 py-3 text-left text-sm hover:bg-muted/40', className)}><div className="min-w-0 flex-1"><span className="font-medium">{op.title}</span><p className="break-all text-xs text-muted-foreground">{op.node_id} · {op.resource_id} · {op.id}</p></div><Badge variant="outline">{op.status === 'awaiting_approval' ? t('待审核', 'Awaiting approval') : op.status}</Badge></button> }
function OperationReview({ id }: { id: string }) {
 const t = useOpsText(), client = useQueryClient(), { formatDateTime } = useDateTime(), [confirmed, setConfirmed] = useState(false)
 const query = useQuery({ queryKey: ['ai-operation', id], queryFn: () => api<AIOperation>(`/ai/operations/${id}`), refetchInterval: 2000 })
 const decision = useMutation({ mutationFn: (approve: boolean) => api<AIOperation>(`/ai/operations/${id}/decision`, { method: 'POST', body: JSON.stringify({ approve, review_token: query.data?.review_token }) }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['ai-operation', id] }); void client.invalidateQueries({ queryKey: ['ai-operations'] }); void client.invalidateQueries({ queryKey: ['tasks'] }); void client.invalidateQueries({ queryKey: ['audit-logs'] }); void client.invalidateQueries({ queryKey: ['ai-audit'] }) } })
 const op = query.data
 return <div className="space-y-4 overflow-y-auto p-5"><ErrorText error={query.error || decision.error} />{op && <><Badge variant="outline">{op.status}</Badge><dl className="space-y-3 text-sm">{[[t('编号', 'Operation ID'), op.id], [t('节点', 'Node'), op.node_id], [t('资源', 'Resource'), op.resource_id], [t('动作', 'Action'), op.action], [t('有效期', 'Expires'), formatDateTime(op.expires_at)], [t('影响、风险与回退方式', 'Impact, risk and recovery'), op.impact]].map(([label, value]) => <div key={label}><dt className="text-xs text-muted-foreground">{label}</dt><dd className="break-all">{value}</dd></div>)}</dl><Field label={t('固定参数', 'Fixed parameters')}><pre className="overflow-auto whitespace-pre-wrap break-all rounded-md border p-3 text-xs">{JSON.stringify(op.parameters, null, 2)}</pre></Field><Field label={t('当前状态与冻结配置', 'Current state and frozen configuration')}><pre className="max-h-64 overflow-auto whitespace-pre-wrap break-all rounded-md border p-3 text-xs">{JSON.stringify(op.snapshot.details, null, 2)}</pre></Field><p className="text-xs text-muted-foreground">{t('目标、运行时或配置变化会使审批失效。失败后的重试和回滚必须重新审核。', 'Target, runtime or configuration changes invalidate approval. Retries and rollbacks need new reviews.')}</p>
 {op.status === 'awaiting_approval' && <><Check label={t('我已阅读完整预览并确认此项操作的影响', 'I have read the full preview and understand this operation’s impact')} checked={confirmed} onChange={setConfirmed} /><div className="flex gap-2"><Button disabled={!confirmed || decision.isPending || new Date(op.expires_at).getTime() <= Date.now()} onClick={() => decision.mutate(true)}>{t('批准并执行此项', 'Approve this operation')}</Button><Button variant="outline" disabled={decision.isPending} onClick={() => decision.mutate(false)}>{t('拒绝', 'Reject')}</Button></div></>}
 {op.result && <p className="whitespace-pre-wrap text-sm">{op.result}</p>}{op.task_id && <Button variant="outline" nativeButton={false} render={<Link to="/tasks" hash={op.task_id} />}>{t('查看执行任务', 'View execution task')}</Button>}</>}</div>
}
export function NotificationInbox() {
 const t = useOpsText(), client = useQueryClient(), { formatDateTime } = useDateTime()
 const query = useQuery({ queryKey: ['notification-inbox'], queryFn: () => api<Inbox>('/notifications/inbox'), refetchInterval: 5000 })
 const read = useMutation({ mutationFn: (id: string) => api(`/notifications/inbox/${id}/read`, { method: 'POST' }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['notification-inbox'] }) } })
 return <ResourceFrame title={t('站内消息', 'Inbox')} detail={`${query.data?.unread || 0} ${t('条未读', 'unread')}`} action={<Button variant="outline" nativeButton={false} render={<Link to="/settings" hash="notifications" />}>{t('通知设置', 'Notification settings')}</Button>}><div className="divide-y border-y"><ErrorText error={query.error || read.error} />{query.data?.items.map(e => <article key={e.id} className="space-y-2 py-4"><div className="flex flex-wrap items-start gap-3"><div className="min-w-0 flex-1"><h3 className={`text-sm ${e.read ? '' : 'font-semibold'}`}>{e.title}</h3><p className="text-xs text-muted-foreground">{formatDateTime(e.time)} · {e.node_name || e.node_id || t('全局', 'Global')} · {e.resource_id}</p></div><Badge variant="outline">{e.severity}</Badge>{!e.read && <Button size="sm" variant="ghost" disabled={read.isPending} onClick={() => read.mutate(e.id)}>{t('标为已读', 'Mark read')}</Button>}</div><p className="whitespace-pre-wrap break-words text-sm text-muted-foreground">{e.message}</p>{(e.run_id || e.operation_id) && <Link to="/ai-operations" hash={new URLSearchParams(e.run_id ? { run: e.run_id } : { operation: e.operation_id }).toString()} className="text-xs underline">{t('诊断与审核时间线', 'Diagnosis and review timeline')}</Link>}{e.task_id && <Link to="/tasks" hash={e.task_id} className="ml-3 text-xs underline">{t('查看任务', 'View task')}</Link>}</article>)}{query.data?.items.length === 0 && <p className="py-10 text-center text-sm text-muted-foreground">{t('暂无消息', 'Your inbox is empty')}</p>}</div></ResourceFrame>
}
