import { expect, test } from '@playwright/test'

for (const width of [390, 1440]) for (const language of ['en-US', 'zh-CN']) for (const theme of ['dark', 'light']) {
 test(`chat setup shows saved AI state and completes binding ${language} ${theme} ${width}`, async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.addInitScript(({ language, theme }) => { sessionStorage.setItem('suma-demo-session', '1'); localStorage.setItem('suma-language', language); localStorage.setItem('suma-theme', theme); localStorage.setItem('suma-node', 'local') }, { language, theme })
  await page.setViewportSize({ width, height: 950 })
  const zh = language === 'zh-CN'
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/settings#notifications')
  await page.getByRole('button', { name: zh ? '添加通知渠道' : 'Add channel', exact: true }).click()
  const sheet = page.getByRole('dialog', { name: zh ? '配置通知渠道' : 'Configure channel', exact: true })
  await sheet.getByLabel('App ID', { exact: true }).fill('cli_onboarding_demo')
  await sheet.getByLabel('App Secret', { exact: true }).fill('demo-only-secret')
  await sheet.getByText(zh ? 'AI 聊天与审批（可选）' : 'AI chat and approvals (optional)', { exact: true }).click()
  await sheet.getByRole('checkbox', { name: zh ? '启用聊天诊断和审批' : 'Enable chat diagnosis and approvals', exact: true }).check()
  await expect(sheet.getByRole('status', { name: zh ? 'AI 聊天就绪状态' : 'AI chat readiness', exact: true })).toContainText(zh ? 'AI 运维尚未启用' : 'AI operations are off')
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await sheet.screenshot({ path: `/tmp/suma-chat-onboarding-off-${language}-${theme}-${width}.png` })
  await sheet.getByRole('link', { name: zh ? '配置 AI 与身份绑定' : 'Configure AI and identity binding', exact: true }).click()
  await expect(sheet).not.toBeVisible()
  await expect(page).toHaveURL(/#ai$/)
  const snapshot = await page.evaluate(() => JSON.parse(sessionStorage.getItem('suma-demo-operations-v2') || '{}'))
  expect(snapshot.channels).toHaveLength(1)
  expect(snapshot.channels[0].config.interactive).toBe(true)
  expect(snapshot.settings.enabled).toBe(false)
  const readiness = page.getByRole('status', { name: zh ? 'AI 聊天就绪状态' : 'AI chat readiness', exact: true })
  await expect(readiness).toContainText(zh ? 'AI 运维尚未启用' : 'AI operations are off')
  await expect(page.getByRole('combobox', { name: zh ? '聊天渠道' : 'Chat channel', exact: true })).toContainText(zh ? '飞书机器人' : 'Feishu bot')
  await page.getByRole('button', { name: zh ? '配置模型' : 'Configure models', exact: true }).click()
  const models = page.getByRole('dialog', { name: zh ? '配置模型' : 'Configure models', exact: true })
  await models.getByLabel(zh ? '手动添加模型' : 'Add model IDs manually', { exact: true }).fill('onboarding-model')
  await models.getByRole('button', { name: zh ? '添加' : 'Add', exact: true }).click()
  await models.getByRole('button', { name: zh ? '应用' : 'Apply', exact: true }).click()
  await page.getByRole('checkbox', { name: 'homelab-01', exact: true }).check()
  await page.getByRole('switch', { name: zh ? '启用 AI 运维' : 'Enable AI operations', exact: true }).check()
  await expect(readiness).toContainText(zh ? 'AI 运维尚未启用' : 'AI operations are off')
  await page.getByRole('button', { name: zh ? '保存 AI 设置' : 'Save AI settings', exact: true }).click()
  await expect(readiness).toContainText(zh ? 'AI 运维已启用' : 'AI operations enabled')
  await expect(readiness).toContainText('onboarding-model')
  await page.getByRole('button', { name: zh ? '测试连接' : 'Test connection', exact: true }).click()
  await expect(page.getByText(zh ? '文本和工具调用通过' : 'Text and tool calling verified', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: zh ? '生成绑定码' : 'Generate binding code', exact: true }).click()
  const command = page.getByRole('status').filter({ hasText: /^\/bind / })
  await expect(command).toBeVisible()
  const expectedCommand = await command.textContent()
  await page.getByRole('button', { name: zh ? '复制绑定命令' : 'Copy binding command', exact: true }).click()
  await expect(page.getByRole('button', { name: zh ? '已复制绑定命令' : 'Binding command copied', exact: true })).toBeVisible()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(expectedCommand)
  await expect(page.getByRole('button', { name: zh ? '确认并加入操作白名单' : 'Confirm and allow operations', exact: true })).toHaveCount(0)
  // Stand in for the private platform message. Actual claiming/confirmation
  // and disabled-model behavior are covered by PostgreSQL service tests.
  await page.evaluate(() => {
   const state = JSON.parse(sessionStorage.getItem('suma-demo-operations-v2') || '{}')
   state.bindings[0].status = 'claimed'; state.bindings[0].external_user_id = 'demo-platform-user'; state.bindings[0].chat_id = 'oc_demo_private'
   sessionStorage.setItem('suma-demo-operations-v2', JSON.stringify(state))
  })
  await page.reload()
  await expect(page.getByText(zh ? '等待站内确认' : 'Awaiting site confirmation', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: zh ? '确认并加入操作白名单' : 'Confirm and allow operations', exact: true }).click()
  await expect(page.getByText(zh ? '此账号已绑定，可直接私聊当前机器人提问。' : 'Your account is bound. Ask the selected bot directly in private chat.', { exact: false })).toBeVisible()
  await expect(page.getByRole('button', { name: zh ? '确认并加入操作白名单' : 'Confirm and allow operations', exact: true })).toHaveCount(0)
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: `/tmp/suma-chat-onboarding-ready-${language}-${theme}-${width}.png` })
  expect(errors).toEqual([])
 })
}

test('failed channel save keeps chat draft and stops navigation to AI settings', async ({ page }) => {
 await page.addInitScript(() => { sessionStorage.setItem('suma-demo-session', '1'); localStorage.setItem('suma-language', 'en-US'); localStorage.setItem('suma-node', 'local') })
 await page.goto('/settings#notifications')
 await page.getByRole('button', { name: 'Add channel', exact: true }).click()
 const sheet = page.getByRole('dialog', { name: 'Configure channel', exact: true })
 await sheet.getByLabel('App ID', { exact: true }).fill('cli_onboarding_failure')
 await sheet.getByLabel('App Secret', { exact: true }).fill('demo-only-secret')
 await sheet.getByRole('button', { name: 'Save channel', exact: true }).click()
 await sheet.getByText('AI chat and approvals (optional)', { exact: true }).click()
 await sheet.getByRole('checkbox', { name: 'Enable chat diagnosis and approvals', exact: true }).check()
 const schema = (available: boolean) => page.evaluate(async available => {
  // @ts-expect-error Vite exposes the demo fixture module in the browser.
  const { setDemoNotificationSchemaAvailable } = await import('/src/features/operations/mock.ts')
  setDemoNotificationSchemaAvailable(available)
 }, available)
 await schema(false)
 await sheet.getByRole('link', { name: 'Configure AI and identity binding', exact: true }).click()
 await expect(sheet.getByRole('alert')).toContainText('schema needs an upgrade')
 await expect(page).toHaveURL(/#notifications$/)
 await expect(sheet.getByRole('checkbox', { name: 'Enable chat diagnosis and approvals', exact: true })).toBeChecked()
 const before = await page.evaluate(() => JSON.parse(sessionStorage.getItem('suma-demo-operations-v2') || '{}'))
 expect(before.channels[0].config.interactive).toBe(false)
 await schema(true)
 await sheet.getByRole('link', { name: 'Configure AI and identity binding', exact: true }).click()
 await expect(page).toHaveURL(/#ai$/)
 await expect(page.getByRole('combobox', { name: 'Chat channel', exact: true })).toContainText('Feishu bot')
})
