import { expect, test } from '@playwright/test'

test('recipient test reports save failures once and succeeds after schema upgrade', async ({ page }) => {
 await page.addInitScript(() => { sessionStorage.setItem('suma-demo-session','1');localStorage.setItem('suma-language','zh-CN');localStorage.setItem('suma-node','local') })
 await page.goto('/settings#notifications');await page.getByRole('button',{name:'添加通知渠道',exact:true}).click()
 const sheet=page.getByRole('dialog',{name:'配置通知渠道',exact:true})
 await sheet.getByLabel('App ID',{exact:true}).fill('cli_schema_ui');await sheet.getByLabel('App Secret',{exact:true}).fill('demo-only-secret')
 await sheet.getByRole('button',{name:'保存渠道',exact:true}).click()
 await sheet.getByRole('checkbox',{name:'私聊 · Admin',exact:true}).check()
 const schemaAvailable = (available: boolean) => page.evaluate(async available => {
  // @ts-expect-error Vite exposes the demo fixture module in the browser.
  const {setDemoNotificationSchemaAvailable}=await import('/src/features/operations/mock.ts')
  setDemoNotificationSchemaAvailable(available)
 },available)
 await schemaAvailable(false)
 await sheet.getByRole('button',{name:'发送测试消息',exact:true}).click()
 await expect(sheet.getByRole('alert')).toHaveCount(1)
 await expect(sheet.getByRole('alert')).toContainText('SUMA 数据库结构尚未升级')
 await expect(sheet.getByText('invalid field',{exact:false})).toHaveCount(0)
 await expect(sheet.getByRole('checkbox',{name:'私聊 · Admin',exact:true})).toBeChecked()
 let snapshot=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('suma-demo-operations-v2')||'{}'))
 expect(snapshot.channels[0].config.targets).toHaveLength(0);expect(snapshot.deliveries).toHaveLength(0)
 await schemaAvailable(true)
 await sheet.getByRole('button',{name:'发送测试消息',exact:true}).click()
 await expect(sheet.getByText('私聊 · Admin · 测试消息已发送',{exact:true})).toBeVisible()
 await expect(sheet.getByRole('alert')).toHaveCount(0)
 snapshot=await page.evaluate(()=>JSON.parse(sessionStorage.getItem('suma-demo-operations-v2')||'{}'))
 expect(snapshot.channels[0].config.targets).toHaveLength(1);expect(snapshot.deliveries).toHaveLength(1)
})

test('connected Feishu distinguishes missing events, storage failures and successful discovery', async ({ page }) => {
 await page.addInitScript(() => { sessionStorage.setItem('suma-demo-session','1');localStorage.setItem('suma-language','zh-CN');localStorage.setItem('suma-node','local') })
 await page.goto('/settings#notifications');await page.getByRole('button',{name:'添加通知渠道',exact:true}).click()
 const sheet=page.getByRole('dialog',{name:'配置通知渠道',exact:true})
 await sheet.getByLabel('App ID',{exact:true}).fill('cli_event_state');await sheet.getByLabel('App Secret',{exact:true}).fill('demo-only-secret')
 await sheet.getByRole('button',{name:'保存渠道',exact:true}).click();await expect(sheet.getByLabel('App Secret',{exact:true})).toHaveValue('')
 const reception = async (result: 'missing' | 'error' | 'discovered') => page.evaluate(async result => {
  // @ts-expect-error Vite exposes the demo modules in the browser.
  const {api}=await import('/src/lib/api.ts')
  // @ts-expect-error Vite exposes the demo modules in the browser.
  const {setDemoFeishuReception}=await import('/src/features/operations/mock.ts')
  const channels=await api('/notifications/channels'), channel=channels.find((item:{config:{app_id:string}})=>item.config.app_id==='cli_event_state')
  setDemoFeishuReception(channel.id,{connection:{state:'connected',message_count:result==='missing'?0:1,last_message_at:result==='missing'?undefined:'2026-10-08T04:00:00Z',last_message_result:result==='error'?'storage_error':result==='discovered'?'discovered':undefined,discovery_error:result==='error'?'Conversation storage failed':undefined},chats:result==='discovered'?[{chat_id:'oc_real_format',name:'Admin',private:true}]:[]})
 },result)
 await reception('missing')
 await expect(sheet.getByText('连接已建立，但尚未收到消息事件。请在飞书发布包含权限和“接收消息”订阅的新版本，确认生效后重新发消息。',{exact:true})).toBeVisible()
 await expect(sheet.getByRole('status',{name:'连接状态',exact:true})).toContainText('已连接')
 await reception('error')
 await expect(sheet.getByRole('alert')).toContainText('消息事件已收到，但保存会话失败')
 await expect(sheet.getByText('已收到 1 次消息事件',{exact:false})).toBeVisible()
 await reception('discovered')
 await expect(sheet.getByRole('checkbox',{name:'私聊 · Admin',exact:true})).toBeVisible()
 await expect(sheet.getByRole('checkbox',{name:'私聊 · Admin',exact:true})).not.toBeChecked()
 await expect(sheet.getByRole('alert')).toHaveCount(0)
 await expect(sheet.getByText('会话已识别。',{exact:true})).toBeVisible()
})

for (const width of [390, 1440]) for (const language of ['en-US', 'zh-CN']) for (const theme of ['dark', 'light']) {
 test(`Feishu single page ${language} ${theme} ${width}`, async ({ page }) => {
  await page.addInitScript(({ language, theme }) => { sessionStorage.setItem('suma-demo-session', '1'); localStorage.setItem('suma-language', language); localStorage.setItem('suma-theme', theme); localStorage.setItem('suma-node', 'local') }, { language, theme })
  await page.setViewportSize({ width, height: 900 })
  const zh = language === 'zh-CN', errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/settings#notifications'); await page.getByRole('button', { name: zh ? '添加通知渠道' : 'Add channel', exact: true }).click()
  const sheet = page.getByRole('dialog', { name: zh ? '配置通知渠道' : 'Configure channel', exact: true })
  await expect(sheet.getByRole('button', { name: zh ? '下一步' : 'Next', exact: true })).toHaveCount(0)
  await expect(sheet.getByLabel('App ID', { exact: true })).toBeVisible()
  await expect(sheet.getByText('im:message:send_as_bot', { exact: true })).toHaveCount(0)
  await sheet.getByLabel('App ID', { exact: true }).fill(`cli_responsive_${width}`)
  await sheet.getByLabel('App Secret', { exact: true }).fill('demo-only-secret')
  await sheet.getByRole('button', { name: zh ? '保存渠道' : 'Save channel', exact: true }).click()
  await expect(sheet.getByRole('status', { name: zh ? '连接状态' : 'Connection status' })).toContainText(zh ? '已连接' : 'Connected')
  await sheet.getByRole('checkbox', { name: zh ? '私聊 · Admin' : 'Private chat · Admin', exact: true }).check()
  await sheet.getByRole('checkbox', { name: zh ? '群聊 · Operations' : 'Group chat · Operations', exact: true }).check()
  await sheet.getByText(zh ? '飞书平台配置说明' : 'Feishu platform setup', { exact: true }).click()
  await expect(sheet.locator('pre').first()).toContainText('im:message.group_at_msg:readonly')
  await sheet.getByText(zh ? '飞书平台配置说明' : 'Feishu platform setup', { exact: true }).click()
  await sheet.getByText(zh ? '高级选项' : 'Advanced options', { exact: true }).click()
  await sheet.getByLabel(zh ? '手填会话 ID' : 'Manual chat ID', { exact: true }).fill('oc_manual')
  await sheet.getByLabel(zh ? '会话备注（可选）' : 'Recipient name (optional)', { exact: true }).fill(zh ? '值班群' : 'On-call group')
  await sheet.getByRole('button', { name: zh ? '添加接收目标' : 'Add recipient', exact: true }).click()
  await expect(sheet.getByRole('checkbox', { name: zh ? '值班群' : 'On-call group', exact: true })).toBeChecked()
  await sheet.getByText(zh ? '高级选项' : 'Advanced options', { exact: true }).click()
  await sheet.getByRole('button', { name: zh ? '发送测试消息' : 'Send test message', exact: true }).click()
  await expect(sheet.getByText(zh ? '私聊 · Admin · 测试消息已发送' : 'Private chat · Admin · Test message sent', { exact: true })).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(await sheet.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await sheet.getByLabel('App ID', { exact: true }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: `/tmp/suma-feishu-${language}-${theme}-${width}.png`, fullPage: true })
  expect(errors).toEqual([])
 })
}
