import { expect, test } from '@playwright/test'

for (const language of ['en-US', 'zh-CN']) for (const theme of ['dark', 'light']) for (const width of [390, 1440]) {
  test(`image update location ${language} ${theme} ${width}`, async ({ page }) => {
    const zh = language === 'zh-CN'
    await page.addInitScript(({ language, theme }) => {
      sessionStorage.setItem('suma-demo-session', '1')
      localStorage.setItem('suma-language', language)
      localStorage.setItem('suma-theme', theme)
      localStorage.setItem('suma-node', 'local')
    }, { language, theme })
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/settings')
    await expect(page.getByRole('tab', { name: zh ? '常规设置' : 'General settings', exact: true })).toBeVisible()
    await expect(page.getByRole('tab', { name: zh ? '镜像更新' : 'Image updates', exact: true })).toHaveCount(0)
    await page.goto('/images')
    await expect(page.getByRole('tab', { name: zh ? '本地镜像' : 'Local images', exact: true })).toHaveAttribute('aria-selected', 'true')
    await expect(page.getByRole('button', { name: zh ? '检查镜像更新' : 'Check image updates', exact: true }).first()).toBeVisible()
    await page.getByRole('tab', { name: zh ? '镜像更新' : 'Image updates', exact: true }).click()
    await expect(page).toHaveURL('/images#image-updates')
    await expect(page.getByRole('combobox', { name: zh ? '镜像检测节点' : 'Image detection node', exact: true })).toHaveCount(0)
    const enabled = page.getByRole('switch', { name: zh ? '启用定时检测' : 'Enable scheduled checks', exact: true })
    await expect(enabled).not.toBeChecked()
    await enabled.click()
    const interval = page.getByRole('combobox', { name: zh ? '检测间隔' : 'Check interval', exact: true })
    await interval.click()
    await page.getByRole('option', { name: zh ? '每 24 小时' : 'Every 24 hours', exact: true }).click()
    const registry = page.getByRole('combobox', { name: zh ? 'ghcr.io 仓库凭据' : 'ghcr.io credential', exact: true })
    await registry.click()
    await page.getByRole('option', { name: 'GHCR Demo', exact: true }).click()
    await page.getByRole('button', { name: zh ? '保存策略' : 'Save policy', exact: true }).click()
    await expect(page.getByText(zh ? '已保存' : 'Saved', { exact: true })).toBeVisible()
    const node = page.getByRole('combobox', { name: zh ? '当前 Docker 节点' : 'Current Docker node', exact: true })
    await node.click()
    await page.getByRole('option').filter({ hasText: 'edge-hk' }).click()
    await expect(node).toContainText('edge-hk')
    await expect(enabled).not.toBeChecked()
    await expect(interval).toContainText(zh ? '每 6 小时' : 'Every 6 hours')
    await expect(registry).toContainText(zh ? '匿名访问' : 'Anonymous')
    await node.click()
    await page.getByRole('option').filter({ hasText: 'homelab-01' }).click()
    await expect(enabled).toBeChecked()
    await expect(interval).toContainText(zh ? '每 24 小时' : 'Every 24 hours')
    await expect(registry).toContainText('GHCR Demo')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.screenshot({ path: `/tmp/suma-image-update-location-${language}-${theme}-${width}.png`, fullPage: true })
    await page.goto('/settings#image-updates')
    await expect(page).toHaveURL('/images#image-updates')
    await expect(enabled).toBeVisible()
    await page.goto('/settings')
    await page.getByRole('button', { name: zh ? '搜索或执行命令' : 'Search or run a command', exact: true }).click()
    const palette = page.getByRole('dialog', { name: zh ? '命令中心' : 'Command center', exact: true })
    await palette.getByRole('combobox').fill(zh ? '打开镜像更新' : 'Open image updates')
    await palette.getByRole('option').filter({ hasText: zh ? '打开镜像更新' : 'Open image updates' }).click()
    await expect(page).toHaveURL('/images#image-updates')
    await expect(enabled).toBeVisible()
  })
}
