import { expect, test, type Page } from '@playwright/test'
async function setup(page: Page, language = 'en-US', theme = 'dark') { await page.addInitScript(({ language, theme }) => { sessionStorage.setItem('suma-demo-session', '1'); localStorage.setItem('suma-language', language); localStorage.setItem('suma-theme', theme); localStorage.setItem('suma-node', 'local') }, { language, theme }) }
test('single-page Feishu setup discovers recipients and routes a notification rule', async ({ page }) => {
 await setup(page); await page.goto('/settings#notifications'); await page.getByRole('button', { name: 'Add channel', exact: true }).click()
 const sheet = page.getByRole('dialog', { name: 'Configure channel' })
 await expect(sheet.getByRole('combobox', { name: 'Platform' })).toContainText('Feishu application bot')
 await expect(sheet.getByRole('button', { name: 'Next', exact: true })).toHaveCount(0)
 await expect(sheet.getByLabel('Channel name', { exact: true })).toHaveValue('Feishu bot')
 await sheet.getByRole('combobox', { name: 'Platform' }).click()
 await expect(page.getByRole('option', { name: /Feishu Webhook/ })).toHaveCount(0)
 await page.getByRole('option', { name: 'Feishu application bot', exact: true }).click()
 await sheet.getByText('Feishu platform setup', { exact: true }).click()
 await expect(sheet.locator('pre').first()).toContainText('im:message:send_as_bot')
 await expect(sheet.locator('pre').first()).toContainText('im:message.p2p_msg:readonly')
 await expect(sheet.locator('pre').first()).toContainText('im:message.group_at_msg:readonly')
 await expect(sheet.getByText('card.action.trigger', { exact: true })).toHaveCount(0)
 await sheet.getByText('Feishu platform setup', { exact: true }).click()
 await sheet.getByLabel('Channel name', { exact: true }).fill('Ops notifications')
 await sheet.getByLabel('App ID', { exact: true }).fill('cli_demo')
 await sheet.getByLabel('App Secret', { exact: true }).fill('demo-only-secret')
 await sheet.getByRole('button', { name: 'Check credentials', exact: true }).click()
 await expect(sheet.getByText('Credentials verified. Connection and delivery are verified separately.', { exact: true })).toBeVisible()
 await expect(sheet.getByRole('status', { name: 'Connection status' })).toContainText('Connected')
 await expect(sheet.getByLabel('App Secret', { exact: true })).toHaveValue('')
 await sheet.getByRole('checkbox', { name: 'Private chat · Admin', exact: true }).check()
 await sheet.getByRole('checkbox', { name: 'Group chat · Operations', exact: true }).check()
 await sheet.getByLabel('Recipient name oc_demo_private', { exact: true }).fill('Admin')
 await sheet.getByLabel('Recipient name oc_demo_group', { exact: true }).fill('Ops team')
 await sheet.getByRole('combobox', { name: 'Test recipient' }).click()
 await page.getByRole('option', { name: 'Ops team', exact: true }).click()
 await sheet.getByRole('button', { name: 'Send test message', exact: true }).click()
 await expect(sheet.getByText('Ops team · Test message sent', { exact: true })).toBeVisible()
 await sheet.getByRole('combobox', { name: 'Test recipient' }).click(); await page.getByRole('option', { name: 'Admin', exact: true }).click()
 await expect(sheet.getByText('Admin · Test message sent', { exact: true })).toHaveCount(0)
 await sheet.getByText('AI chat and approvals (optional)', { exact: true }).click()
 await expect(sheet.getByRole('checkbox', { name: 'Enable chat diagnosis and approvals', exact: true })).not.toBeChecked()
 await sheet.getByRole('checkbox', { name: 'Enable chat diagnosis and approvals', exact: true }).check()
 await expect(sheet.getByRole('link', { name: 'Configure AI and identity binding' })).toBeVisible()
 await sheet.getByText('Feishu platform setup', { exact: true }).click()
 await expect(sheet.getByText('card.action.trigger', { exact: true })).toHaveCount(2)
 await expect(sheet.locator('pre').first()).toContainText('cardkit:card:write')
 await expect(sheet.locator('pre').first()).toContainText('im:message:update')
 await expect(sheet.getByText('AI replies stream into one card by default.', { exact: false })).toBeVisible()
 await sheet.getByRole('checkbox', { name: 'Enable chat diagnosis and approvals', exact: true }).uncheck()
 await sheet.getByRole('button', { name: 'Save channel', exact: true }).click()
 await sheet.getByRole('button', { name: 'Choose subscriptions', exact: true }).click()
 const rule = page.getByRole('dialog', { name: 'Notification rule' })
 await rule.getByLabel('Rule name', { exact: true }).fill('Security events')
 await rule.getByRole('combobox', { name: 'Use preset' }).click(); await page.getByRole('option', { name: 'Account security', exact: true }).click()
 await expect(rule.getByRole('checkbox', { name: 'Ops notifications', exact: true })).toBeChecked()
 await expect(rule.getByRole('checkbox', { name: 'Admin', exact: true })).toBeChecked()
 await rule.getByRole('checkbox', { name: 'Ops team', exact: true }).uncheck()
 await rule.getByRole('button', { name: 'Save rule', exact: true }).click(); await expect(rule).toBeHidden(); await expect(page.getByRole('button', { name: 'Security events', exact: true })).toBeVisible()
 const snapshot = await page.evaluate(() => JSON.parse(sessionStorage.getItem('suma-demo-operations-v2') || '{}'))
 expect(snapshot.channels).toHaveLength(1); expect(snapshot.channels[0].config.interactive).toBe(false)
 expect(snapshot.channels[0].config.targets).toHaveLength(2); expect(snapshot.deliveries).toHaveLength(1)
 expect(snapshot.deliveries[0].chat_id).toBe('oc_demo_group')
 expect(snapshot.rules[0].config.channel_targets[snapshot.channels[0].id]).toEqual(['oc_demo_private'])
 await page.getByRole('tab', { name: 'Deliveries', exact: true }).click()
 await expect(page.getByText('sent', { exact: true })).toBeVisible(); await expect(page.getByText(/Ops team/, { exact: false })).toBeVisible()
 await page.getByRole('tab', { name: 'Channels', exact: true }).click(); await page.getByRole('button', { name: 'Ops notifications', exact: true }).click()
 await expect(sheet.getByLabel('App Secret', { exact: true })).toHaveValue('')
 await sheet.getByRole('button', { name: 'Remove Admin', exact: true }).click()
 await sheet.getByRole('button', { name: 'Save channel', exact: true }).click(); await sheet.getByRole('button', { name: 'Done', exact: true }).click()
 await page.getByRole('tab', { name: 'Rules', exact: true }).click()
 await expect(page.getByText('A recipient was removed. Edit this rule.', { exact: true })).toBeVisible()
 await page.getByRole('button', { name: 'Security events', exact: true }).click()
 await expect(rule.getByRole('button', { name: 'Save rule', exact: true })).toBeDisabled()
 await rule.getByRole('checkbox', { name: 'Missing recipient: oc_demo_private', exact: true }).click(); await expect(rule.getByRole('checkbox', { name: 'Missing recipient: oc_demo_private', exact: true })).toHaveCount(0)
 await rule.getByRole('checkbox', { name: 'Ops team', exact: true }).check()
 await rule.getByRole('button', { name: 'Save rule', exact: true }).click(); await expect(rule).toBeHidden()
 await expect(page.getByText('A recipient was removed. Edit this rule.', { exact: true })).toHaveCount(0)
})

test('failed credential save preserves editable draft and does not test or create duplicates', async ({ page }) => {
 await setup(page); await page.goto('/settings#notifications'); await page.getByRole('button', { name: 'Add channel', exact: true }).click()
 const sheet = page.getByRole('dialog', { name: 'Configure channel' })
 await sheet.getByLabel('App ID', { exact: true }).fill('cli_unique'); await sheet.getByLabel('App Secret', { exact: true }).fill('demo-secret')
 await sheet.getByRole('button', { name: 'Save channel', exact: true }).click(); await sheet.getByRole('button', { name: 'Done', exact: true }).click()
 await page.getByRole('button', { name: 'Add channel', exact: true }).click()
 await sheet.getByLabel('App ID', { exact: true }).fill('cli_unique'); await sheet.getByLabel('App Secret', { exact: true }).fill('demo-secret')
 await sheet.getByRole('button', { name: 'Check credentials', exact: true }).click()
 await expect(sheet.getByRole('alert')).toContainText('One channel per Feishu application')
 await expect(sheet.getByLabel('App ID', { exact: true })).toHaveValue('cli_unique')
 await expect(sheet.getByText('Credentials verified.', { exact: false })).toHaveCount(0)
 await sheet.getByLabel('App ID', { exact: true }).fill('cli_corrected')
 await sheet.getByRole('button', { name: 'Check credentials', exact: true }).click()
 await expect(sheet.getByText('Credentials verified.', { exact: false })).toBeVisible()
 const snapshot = await page.evaluate(() => JSON.parse(sessionStorage.getItem('suma-demo-operations-v2') || '{}'))
 expect(snapshot.channels).toHaveLength(2); expect(snapshot.deliveries).toHaveLength(0)
})

test('AI diagnosis requires a full individual preview before execution and preserves audit', async ({ page }) => {
 await setup(page); await page.goto('/settings#ai'); await page.getByRole('switch', { name: 'Enable AI operations', exact: true }).check(); await page.getByRole('button', { name: 'Configure models', exact: true }).click(); const models = page.getByRole('dialog', { name: 'Configure models', exact: true }); await models.getByLabel('Add model IDs manually', { exact: true }).fill('demo-model'); await models.getByRole('button', { name: 'Add', exact: true }).click(); await models.getByRole('button', { name: 'Apply', exact: true }).click(); await page.getByRole('checkbox', { name: 'homelab-01', exact: true }).check(); await page.getByRole('button', { name: 'Save AI settings' }).click(); await page.getByRole('button', { name: 'Test connection' }).click(); await expect(page.getByText('Text and tool calling verified', { exact: true })).toBeVisible()
 await page.goto('/ai-operations'); await page.getByRole('textbox').fill('Why is redis restarting?'); await page.getByRole('button', { name: 'Start diagnosis', exact: true }).click(); const clarification = page.getByRole('form', { name: 'Provide task input', exact: true }); await clarification.getByRole('checkbox', { name: 'local · local', exact: true }).check(); await clarification.getByRole('button', { name: 'Confirm and continue', exact: true }).click(); await expect(page.getByText('Evidence suggests', { exact: false })).toBeVisible(); await page.getByRole('button', { name: /Restart redis-main/ }).click()
 const preview = page.getByRole('dialog', { name: 'Full operation preview' }); const operationID = await preview.locator('dl dd').first().textContent(); const approve = preview.getByRole('button', { name: 'Approve this operation', exact: true }); await expect(approve).toBeDisabled(); await expect(preview.getByText('Interrupts service.', { exact: false })).toBeVisible(); await preview.getByRole('checkbox', { name: 'I have read the full preview', exact: false }).check(); await approve.click(); await expect(preview.getByText('Completed: container restart verified', { exact: true }).first()).toBeVisible(); await expect(approve).toHaveCount(0); await preview.getByRole('button', { name: 'Close', exact: true }).click(); await page.getByRole('tab', { name: 'Audit history', exact: true }).click(); await expect(page.getByText('approved · redis-main', { exact: false })).toBeVisible(); await page.getByRole('link', { name: 'View all audit logs', exact: true }).click(); await expect(page.getByRole('tab', { name: 'All', exact: true })).toHaveAttribute('aria-selected', 'true'); await expect(page.getByText('ai.approved', { exact: true })).toBeVisible(); await expect(page.getByRole('link', { name: 'View AI record', exact: true })).toBeVisible(); await page.getByRole('tab', { name: 'Control plane', exact: true }).click(); await expect(page.getByText('ai.approved', { exact: true })).toHaveCount(0); await page.getByRole('tab', { name: 'Current node', exact: true }).click(); await expect(page.getByText('ai.approved', { exact: true })).toBeVisible(); await page.getByRole('link', { name: 'View AI record', exact: true }).click(); await expect(page.getByRole('dialog', { name: 'Full operation preview' })).toBeVisible()
 await page.goto(`/ai-operations#${operationID}`); await expect(page.getByRole('dialog', { name: 'Full operation preview' }).getByText('Completed: container restart verified', { exact: true }).first()).toBeVisible(); await page.goto('/notifications'); await expect(page.getByText('Container OOM', { exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Mark read', exact: true }).last().click(); await page.getByRole('link', { name: 'Diagnosis and review timeline', exact: true }).first().click(); await expect(page.getByText('Completed: container restart verified', { exact: true }).first()).toBeVisible()
})
test('global audit links open node and control-plane task details', async ({ page }) => {
 await setup(page); await page.goto('/audit-logs')
 await page.getByRole('row').filter({ has: page.getByText('image.pull', { exact: true }) }).getByRole('link', { name: 'View task', exact: true }).click()
 const linked = page.getByRole('region', { name: 'Linked task', exact: true })
 await expect(linked.getByRole('heading', { name: 'Pull ghcr.io/afteryuwei/gateway:1.8.2', exact: true })).toBeVisible(); await expect(linked.getByText('Docker operation completed successfully', { exact: true })).toBeVisible()
 await page.getByRole('button', { name: 'Close task details', exact: true }).click(); await expect(linked).toHaveCount(0)
 await page.goto('/audit-logs'); await page.getByRole('row').filter({ has: page.getByText('project.deploy', { exact: true }) }).getByRole('link', { name: 'View task', exact: true }).click()
 await expect(page.getByRole('tab', { name: 'Current node', exact: true })).toHaveAttribute('aria-selected', 'true'); await expect(linked.getByRole('heading', { name: 'Deploy gateway-prod release #184', exact: true })).toBeVisible(); await expect(linked.getByText('Control plane', { exact: false })).toBeVisible(); await expect(linked.getByText('Docker operation completed successfully', { exact: true })).toBeVisible()
})
for (const width of [390, 1440]) for (const language of ['en-US', 'zh-CN']) for (const theme of ['dark', 'light']) {
 test(`notification AI responsive ${language} ${theme} ${width}`, async ({ page }) => { await setup(page, language, theme); await page.setViewportSize({ width, height: 900 }); for (const path of ['/settings#notifications', '/settings#ai', '/ai-operations', '/audit-logs', '/tasks#task-pull-183', '/notifications']) { await page.goto(path); const zh = language === 'zh-CN'; if (path === '/settings#notifications') await expect(page.getByRole('button', { name: zh ? '添加通知渠道' : 'Add channel', exact: true })).toBeVisible(); else if (path === '/settings#ai') { await expect(page.getByRole('switch', { name: zh ? '启用 AI 运维' : 'Enable AI operations', exact: true })).toBeVisible(); await expect(page.getByRole('heading', { name: zh ? '聊天账号绑定与操作白名单' : 'Chat identity binding & operator allowlist', exact: true })).toBeVisible(); await expect(page.getByText(zh ? '非白名单账号只能查询授权节点的状态和数量摘要' : 'Other identities can query status and counts on authorized nodes only.', { exact: false })).toBeVisible() } else if (path === '/ai-operations') await expect(page.getByRole('button', { name: zh ? '发起诊断' : 'Start diagnosis', exact: true })).toBeVisible(); else if (path === '/audit-logs') { await expect(page.getByRole('tab', { name: zh ? '全部' : 'All', exact: true })).toHaveAttribute('aria-selected', 'true'); await expect(page.getByText('container.restart', { exact: true })).toBeVisible() } else if (path === '/tasks#task-pull-183') await expect(page.getByRole('region', { name: zh ? '关联任务' : 'Linked task', exact: true }).getByRole('heading', { name: 'Pull ghcr.io/afteryuwei/gateway:1.8.2', exact: true })).toBeVisible(); else await expect(page.getByText('Container OOM', { exact: true })).toBeVisible(); await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true) } await page.screenshot({ path: `/tmp/suma-notification-ai-${language}-${theme}-${width}.png`, fullPage: true })
})
}
