import { expect, test, type Page } from '@playwright/test'
async function setup(page: Page, language = 'en-US', theme = 'dark') { await page.addInitScript(({ language, theme }) => { sessionStorage.setItem('suma-demo-session', '1'); localStorage.setItem('suma-language', language); localStorage.setItem('suma-theme', theme); localStorage.setItem('suma-node', 'local') }, { language, theme }) }
test('single-page Feishu setup discovers recipients and routes a notification rule', async ({ page }) => {
 await setup(page); await page.goto('/settings#notifications'); await page.getByRole('button', { name: 'Add channel', exact: true }).click()
 const sheet = page.getByRole('dialog', { name: 'Configure channel' })
 await expect(sheet.getByRole('combobox', { name: 'Platform' })).toContainText('Feishu application bot')
 await expect(sheet.getByRole('button', { name: 'Next', exact: true })).toHaveCount(0)
 await expect(sheet.getByLabel('Channel name', { exact: true })).toHaveValue('Feishu bot')
 await sheet.getByRole('combobox', { name: 'Platform' }).click()
 await expect(page.getByRole('option', { name: /Feishu Webhook/ })).toHaveCount(0)
 await page.getByRole('option', { name: 'Feishu application bot', exact: true }).click()
 await sheet.getByText('Feishu platform setup', { exact: true }).click()
 await expect(sheet.locator('pre').first()).toContainText('im:message:send_as_bot')
 await expect(sheet.locator('pre').first()).toContainText('im:message.p2p_msg:readonly')
 await expect(sheet.locator('pre').first()).toContainText('im:message.group_at_msg:readonly')
 await expect(sheet.getByText('card.action.trigger', { exact: true })).toHaveCount(0)
 await sheet.getByText('Feishu platform setup', { exact: true }).click()
 await sheet.getByLabel('Channel name', { exact: true }).fill('Ops notifications')
 await sheet.getByLabel('App ID', { exact: true }).fill('cli_demo')
 await sheet.getByLabel('App Secret', { exact: true }).fill('demo-only-secret')
 await sheet.getByRole('button', { name: 'Check credentials', exact: true }).click()
 await expect(sheet.getByText('Credentials verified. Connection and delivery are verified separately.', { exact: true })).toBeVisible()
 await expect(sheet.getByRole('status', { name: 'Connection status' })).toContainText('Connected')
 await expect(sheet.getByLabel('App Secret', { exact: true })).toHaveValue('')
 await sheet.getByRole('checkbox', { name: 'Private chat · Admin', exact: true }).check()
 await sheet.getByRole('checkbox', { name: 'Group chat · Operations', exact: true }).check()
 await sheet.getByLabel('Recipient name oc_demo_private', { exact: true }).fill('Admin')
 await sheet.getByLabel('Recipient name oc_demo_group', { exact: true }).fill('Ops team')
 await sheet.getByRole('combobox', { name: 'Test recipient' }).click()
 await page.getByRole('option', { name: 'Ops team', exact: true }).click()
 await sheet.getByRole('button', { name: 'Send test message', exact: true }).click()
 await expect(sheet.getByText('Ops team · Test message sent', { exact: true })).toBeVisible()
 await sheet.getByRole('combobox', { name: 'Test recipient' }).click(); await page.getByRole('option', { name: 'Admin', exact: true }).click()
 await expect(sheet.getByText('Admin · Test message sent', { exact: true })).toHaveCount(0)
 await expect(sheet.getByText(/AI chat|identity binding|card.action.trigger/)).toHaveCount(0)
 await sheet.getByRole('button', { name: 'Save channel', exact: true }).click()
 await sheet.getByRole('button', { name: 'Choose subscriptions', exact: true }).click()
 const rule = page.getByRole('dialog', { name: 'Notification rule' })
 await rule.getByLabel('Rule name', { exact: true }).fill('Security events')
 await rule.getByRole('combobox', { name: 'Use preset' }).click(); await page.getByRole('option', { name: 'Account security', exact: true }).click()
 await expect(rule.getByRole('checkbox', { name: 'Ops notifications', exact: true })).toBeChecked()
 await expect(rule.getByRole('checkbox', { name: 'Admin', exact: true })).toBeChecked()
 await rule.getByRole('checkbox', { name: 'Ops team', exact: true }).uncheck()
 await rule.getByRole('button', { name: 'Save rule', exact: true }).click(); await expect(rule).toBeHidden(); await expect(page.getByRole('button', { name: 'Security events', exact: true })).toBeVisible()
 const snapshot = await page.evaluate(() => JSON.parse(sessionStorage.getItem('suma-demo-notifications-v1') || '{}'))
 expect(snapshot.channels).toHaveLength(1); expect(snapshot.channels[0].config.auto_discover).toBe(false)
 expect(snapshot.channels[0].config.targets).toHaveLength(2); expect(snapshot.deliveries).toHaveLength(1)
 expect(snapshot.deliveries[0].chat_id).toBe('oc_demo_group')
 expect(snapshot.rules[0].config.channel_targets[snapshot.channels[0].id]).toEqual(['oc_demo_private'])
 await page.getByRole('tab', { name: 'Deliveries', exact: true }).click()
 await expect(page.getByText('sent', { exact: true })).toBeVisible(); await expect(page.getByText(/Ops team/, { exact: false })).toBeVisible()
 await page.getByRole('tab', { name: 'Channels', exact: true }).click(); await page.getByRole('button', { name: 'Ops notifications', exact: true }).click()
 await expect(sheet.getByLabel('App Secret', { exact: true })).toHaveValue('')
 await sheet.getByRole('button', { name: 'Remove Admin', exact: true }).click()
 await sheet.getByRole('button', { name: 'Save channel', exact: true }).click(); await sheet.getByRole('button', { name: 'Done', exact: true }).click()
 await page.getByRole('tab', { name: 'Rules', exact: true }).click()
 await expect(page.getByText('A recipient was removed. Edit this rule.', { exact: true })).toBeVisible()
 await page.getByRole('button', { name: 'Security events', exact: true }).click()
 await expect(rule.getByRole('button', { name: 'Save rule', exact: true })).toBeDisabled()
 await rule.getByRole('checkbox', { name: 'Missing recipient: oc_demo_private', exact: true }).click(); await expect(rule.getByRole('checkbox', { name: 'Missing recipient: oc_demo_private', exact: true })).toHaveCount(0)
 await rule.getByRole('checkbox', { name: 'Ops team', exact: true }).check()
 await rule.getByRole('button', { name: 'Save rule', exact: true }).click(); await expect(rule).toBeHidden()
 await expect(page.getByText('A recipient was removed. Edit this rule.', { exact: true })).toHaveCount(0)
})

test('failed credential save preserves editable draft and does not test or create duplicates', async ({ page }) => {
 await setup(page); await page.goto('/settings#notifications'); await page.getByRole('button', { name: 'Add channel', exact: true }).click()
 const sheet = page.getByRole('dialog', { name: 'Configure channel' })
 await sheet.getByLabel('App ID', { exact: true }).fill('cli_unique'); await sheet.getByLabel('App Secret', { exact: true }).fill('demo-secret')
 await sheet.getByRole('button', { name: 'Save channel', exact: true }).click(); await sheet.getByRole('button', { name: 'Done', exact: true }).click()
 await page.getByRole('button', { name: 'Add channel', exact: true }).click()
 await sheet.getByLabel('App ID', { exact: true }).fill('cli_unique'); await sheet.getByLabel('App Secret', { exact: true }).fill('demo-secret')
 await sheet.getByRole('button', { name: 'Check credentials', exact: true }).click()
 await expect(sheet.getByRole('alert')).toContainText('One channel per Feishu application')
 await expect(sheet.getByLabel('App ID', { exact: true })).toHaveValue('cli_unique')
 await expect(sheet.getByText('Credentials verified.', { exact: false })).toHaveCount(0)
 await sheet.getByLabel('App ID', { exact: true }).fill('cli_corrected')
 await sheet.getByRole('button', { name: 'Check credentials', exact: true }).click()
 await expect(sheet.getByText('Credentials verified.', { exact: false })).toBeVisible()
 const snapshot = await page.evaluate(() => JSON.parse(sessionStorage.getItem('suma-demo-notifications-v1') || '{}'))
 expect(snapshot.channels).toHaveLength(2); expect(snapshot.deliveries).toHaveLength(0)
})

test('global audit links open node and control-plane task details', async ({ page }) => {
 await setup(page); await page.goto('/audit-logs')
 await page.getByRole('row').filter({ has: page.getByText('image.pull', { exact: true }) }).getByRole('link', { name: 'View task', exact: true }).click()
 const linked = page.getByRole('region', { name: 'Linked task', exact: true })
 await expect(linked.getByRole('heading', { name: 'Pull ghcr.io/afteryuwei/gateway:1.8.2', exact: true })).toBeVisible(); await expect(linked.getByText('Docker operation completed successfully', { exact: true })).toBeVisible()
 await page.getByRole('button', { name: 'Close task details', exact: true }).click(); await expect(linked).toHaveCount(0)
 await page.goto('/audit-logs'); await page.getByRole('row').filter({ has: page.getByText('project.deploy', { exact: true }) }).getByRole('link', { name: 'View task', exact: true }).click()
 await expect(page.getByRole('tab', { name: 'Current node', exact: true })).toHaveAttribute('aria-selected', 'true'); await expect(linked.getByRole('heading', { name: 'Deploy gateway-prod release #184', exact: true })).toBeVisible(); await expect(linked.getByText('Control plane', { exact: false })).toBeVisible(); await expect(linked.getByText('Docker operation completed successfully', { exact: true })).toBeVisible()
})

test('Telegram recipient discovery is an independent opt-in and does not subscribe automatically', async ({ page }) => {
 await setup(page); await page.goto('/settings#notifications'); await page.getByRole('button', { name: 'Add channel', exact: true }).click()
 const sheet = page.getByRole('dialog', { name: 'Configure channel', exact: true })
 await sheet.getByRole('combobox', { name: 'Platform', exact: true }).click(); await page.getByRole('option', { name: 'Telegram', exact: true }).click()
 const discovery = sheet.getByRole('checkbox', { name: 'Automatically discover recipient chats', exact: true })
 await expect(discovery).not.toBeChecked()
 await sheet.getByLabel('Bot Token', { exact: true }).fill('123:demo-only-token')
 await sheet.getByRole('button', { name: 'Save channel', exact: true }).click()
 await expect(sheet.getByRole('button', { name: 'Admin · 123456', exact: true })).toHaveCount(0)
 await discovery.check(); await sheet.getByRole('button', { name: 'Save channel', exact: true }).click()
 await expect(sheet.getByRole('button', { name: 'Admin · 123456', exact: true })).toBeVisible()
 await expect(sheet.getByLabel('Notification chat ID', { exact: true })).toHaveValue('')
 await sheet.getByRole('button', { name: 'Admin · 123456', exact: true }).click()
 await sheet.getByRole('button', { name: 'Save channel', exact: true }).click()
 await sheet.getByRole('button', { name: 'Send test message', exact: true }).click()
 await expect(sheet.getByText('Test message sent', { exact: true })).toBeVisible()
 await discovery.uncheck(); await sheet.getByRole('button', { name: 'Save channel', exact: true }).click()
 await sheet.getByRole('button', { name: 'Done', exact: true }).click()
 await page.getByRole('button', { name: 'Telegram', exact: true }).click()
 await expect(discovery).not.toBeChecked(); await expect(sheet.getByLabel('Notification chat ID', { exact: true })).toHaveValue('123456')
})

for (const width of [390, 1440]) for (const language of ['en-US', 'zh-CN']) for (const theme of ['dark', 'light']) {
 test(`notification-only responsive ${language} ${theme} ${width}`, async ({ page }) => {
  await setup(page, language, theme); await page.setViewportSize({ width, height: 900 })
  const zh = language === 'zh-CN', errors: string[] = [], removedRequests: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => { if (/\/(?:api\/v1\/ai|api\/v1\/notification-bindings|ws\/ai)\//.test(request.url())) removedRequests.push(request.url()) })
  for (const path of ['/settings#notifications', '/settings#ai', '/audit-logs', '/tasks#task-pull-183', '/notifications', '/containers', '/images', '/projects/compose/gateway-prod']) {
   await page.goto(path)
   if (path === '/settings#notifications') await expect(page.getByRole('button', { name: zh ? '添加通知渠道' : 'Add channel', exact: true })).toBeVisible()
   else if (path === '/settings#ai') await expect(page.getByRole('tab', { name: zh ? '常规设置' : 'General settings', exact: true })).toHaveAttribute('aria-selected', 'true')
   else if (path === '/audit-logs') await expect(page.getByRole('tab', { name: zh ? '全部' : 'All', exact: true })).toHaveAttribute('aria-selected', 'true')
   else if (path === '/tasks#task-pull-183') await expect(page.getByRole('region', { name: zh ? '关联任务' : 'Linked task', exact: true }).getByRole('heading', { name: 'Pull ghcr.io/afteryuwei/gateway:1.8.2', exact: true })).toBeVisible()
   else if (path === '/notifications') {
    await expect(page.getByText('Container OOM', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: zh ? '标为已读' : 'Mark read', exact: true }).click()
    await expect(page.getByRole('button', { name: zh ? '标为已读' : 'Mark read', exact: true })).toHaveCount(0)
    await page.reload()
    await expect(page.getByRole('heading', { name: zh ? '站内消息' : 'Inbox', exact: true })).toBeVisible()
    await expect(page.getByText('Container OOM', { exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: zh ? '标为已读' : 'Mark read', exact: true })).toHaveCount(0)
    await page.screenshot({ path: `/tmp/suma-notifications-${language}-${theme}-${width}.png`, fullPage: true })
   }
   else if (path === '/containers') await expect(page.getByRole('heading', { name: zh ? '容器' : 'Containers', exact: true })).toBeVisible()
   else if (path === '/images') await expect(page.getByRole('button', { name: zh ? '检查镜像更新' : 'Check image updates', exact: true }).first()).toBeVisible()
   else if (path === '/projects/compose/gateway-prod') await expect(page.getByRole('heading', { name: 'gateway-prod', exact: true })).toBeVisible()
   await expect(page.getByRole('link', { name: /AI|待审核|Pending approvals/ })).toHaveCount(0)
   await expect(page.getByRole('button', { name: /交给 AI|Analyze with AI/ })).toHaveCount(0)
   await expect(page.locator('a[href*="ai-operations"]')).toHaveCount(0)
   await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  await page.goto('/settings#notifications')
  await page.getByRole('button', { name: zh ? '添加通知渠道' : 'Add channel', exact: true }).click()
  const sheet = page.getByRole('dialog', { name: zh ? '配置通知渠道' : 'Configure channel', exact: true })
  await sheet.getByText(zh ? '飞书平台配置说明' : 'Feishu platform setup', { exact: true }).click()
  await expect(sheet.locator('pre').first()).not.toContainText('cardkit:card:write')
  await expect(sheet.locator('pre').first()).not.toContainText('im:message:update')
  await expect(sheet.getByText('card.action.trigger', { exact: true })).toHaveCount(0)
  await page.keyboard.press('Escape'); await expect(sheet).toBeHidden()
  await page.keyboard.press('Control+k')
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('dialog').getByText(/AI 诊断|AI diagnosis|待审核操作|pending approvals/)).toHaveCount(0)
  expect(errors).toEqual([]); expect(removedRequests).toEqual([])
 })
}
