import { expect, test, type Page } from '@playwright/test'
async function setup(page: Page, language = 'en-US', theme = 'dark') { await page.addInitScript(({ language, theme }) => { sessionStorage.setItem('suma-demo-session', '1'); localStorage.setItem('suma-language', language); localStorage.setItem('suma-theme', theme); localStorage.setItem('suma-node', 'local') }, { language, theme }) }
test('channel wizard explains Feishu permissions and configures a notification rule', async ({ page }) => {
 await setup(page); await page.goto('/settings#notifications'); await page.getByRole('button', { name: 'Add channel', exact: true }).click()
 const sheet = page.getByRole('dialog', { name: 'Configure channel' }); await sheet.getByRole('combobox', { name: 'Platform' }).click(); await page.getByRole('option', { name: '飞书 / Feishu App', exact: true }).click(); await sheet.getByRole('button', { name: 'Next', exact: true }).click()
 await expect(sheet.getByText('Other users can query safe status and counts only.', { exact: false })).toBeVisible(); await expect(sheet.getByText('im:message:send_as_bot', { exact: true })).toBeVisible(); await expect(sheet.getByText('im:message.p2p_msg:readonly', { exact: true })).toBeVisible(); await expect(sheet.getByText('Events & callbacks', { exact: false })).toContainText('card.action.trigger')
 await sheet.getByLabel('Channel name', { exact: true }).fill('Ops notifications'); await sheet.getByLabel('App ID', { exact: true }).fill('cli_demo'); await sheet.getByLabel('App Secret', { exact: true }).fill('demo-only-secret'); await sheet.getByLabel('Notification chat ID', { exact: true }).fill('demo-chat'); await sheet.getByRole('button', { name: 'Save and test' }).click(); await sheet.getByRole('button', { name: 'Check credentials' }).click(); await expect(sheet.getByRole('status')).toContainText('Credentials verified'); await sheet.getByRole('button', { name: 'Send test message' }).click(); await expect(sheet.getByRole('status')).toContainText('Test message sent'); await sheet.getByRole('button', { name: 'Choose subscriptions' }).click()
 const rule = page.getByRole('dialog', { name: 'Notification rule' }); await rule.getByLabel('Rule name', { exact: true }).fill('Security events'); await rule.getByRole('combobox', { name: 'Use preset' }).click(); await page.getByRole('option', { name: 'Account security', exact: true }).click(); await rule.getByRole('checkbox', { name: 'Ops notifications', exact: true }).check(); await rule.getByRole('button', { name: 'Save rule' }).click(); await expect(page.getByRole('button', { name: 'Security events', exact: true })).toBeVisible()
 await page.getByRole('tab', { name: 'Deliveries', exact: true }).click(); await expect(page.getByText('sent', { exact: true })).toBeVisible(); await page.goto('/settings#notifications?tab=rules'); await expect(page.getByRole('tab', { name: 'Rules', exact: true })).toHaveAttribute('aria-selected', 'true'); await expect(page.getByRole('button', { name: 'Security events', exact: true })).toBeVisible()
})
test('AI diagnosis requires a full individual preview before execution and preserves audit', async ({ page }) => {
 await setup(page); await page.goto('/settings#ai'); await page.getByRole('switch', { name: 'Enable AI operations', exact: true }).check(); await page.getByRole('button', { name: 'Configure models', exact: true }).click(); const models = page.getByRole('dialog', { name: 'Configure models', exact: true }); await models.getByLabel('Add model IDs manually', { exact: true }).fill('demo-model'); await models.getByRole('button', { name: 'Add', exact: true }).click(); await models.getByRole('button', { name: 'Apply', exact: true }).click(); await page.getByRole('checkbox', { name: 'homelab-01', exact: true }).check(); await page.getByRole('button', { name: 'Save AI settings' }).click(); await page.getByRole('button', { name: 'Test connection' }).click(); await expect(page.getByText('Text and tool calling verified', { exact: true })).toBeVisible()
 await page.goto('/ai-operations'); await page.getByRole('textbox').fill('Why is redis restarting?'); await page.getByRole('button', { name: 'Start diagnosis', exact: true }).click(); await expect(page.getByText('Evidence suggests', { exact: false })).toBeVisible(); await page.getByRole('button', { name: /Restart redis-main/ }).click()
 const preview = page.getByRole('dialog', { name: 'Full operation preview' }); const operationID = await preview.locator('dl dd').first().textContent(); const approve = preview.getByRole('button', { name: 'Approve this operation', exact: true }); await expect(approve).toBeDisabled(); await expect(preview.getByText('Interrupts service.', { exact: false })).toBeVisible(); await preview.getByRole('checkbox', { name: 'I have read the full preview', exact: false }).check(); await approve.click(); await expect(preview.getByText('Completed: container restart verified', { exact: true })).toBeVisible(); await expect(approve).toHaveCount(0); await preview.getByRole('button', { name: 'Close', exact: true }).click(); await page.getByRole('tab', { name: 'Audit history', exact: true }).click(); await expect(page.getByText('approved · redis-main', { exact: false })).toBeVisible(); await page.getByRole('link', { name: 'View all audit logs', exact: true }).click(); await expect(page.getByRole('tab', { name: 'All', exact: true })).toHaveAttribute('aria-selected', 'true'); await expect(page.getByText('ai.approved', { exact: true })).toBeVisible(); await expect(page.getByRole('link', { name: 'View AI record', exact: true })).toBeVisible(); await page.getByRole('tab', { name: 'Control plane', exact: true }).click(); await expect(page.getByText('ai.approved', { exact: true })).toHaveCount(0); await page.getByRole('tab', { name: 'Current node', exact: true }).click(); await expect(page.getByText('ai.approved', { exact: true })).toBeVisible(); await page.getByRole('link', { name: 'View AI record', exact: true }).click(); await expect(page.getByRole('dialog', { name: 'Full operation preview' })).toBeVisible()
 await page.goto(`/ai-operations#${operationID}`); await expect(page.getByRole('dialog', { name: 'Full operation preview' }).getByText('Completed: container restart verified', { exact: true })).toBeVisible(); await page.goto('/notifications'); await expect(page.getByText('Container OOM', { exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Mark read', exact: true }).last().click(); await page.getByRole('link', { name: 'Diagnosis and review timeline', exact: true }).first().click(); await expect(page.getByText('Evidence suggests', { exact: false })).toBeVisible()
})
test('global audit links open node and control-plane task details', async ({ page }) => {
 await setup(page); await page.goto('/audit-logs')
 await page.getByRole('row').filter({ has: page.getByText('image.pull', { exact: true }) }).getByRole('link', { name: 'View task', exact: true }).click()
 const linked = page.getByRole('region', { name: 'Linked task', exact: true })
 await expect(linked.getByRole('heading', { name: 'Pull ghcr.io/afteryuwei/gateway:1.8.2', exact: true })).toBeVisible(); await expect(linked.getByText('Docker operation completed successfully', { exact: true })).toBeVisible()
 await page.getByRole('button', { name: 'Close task details', exact: true }).click(); await expect(linked).toHaveCount(0)
 await page.goto('/audit-logs'); await page.getByRole('row').filter({ has: page.getByText('project.deploy', { exact: true }) }).getByRole('link', { name: 'View task', exact: true }).click()
 await expect(page.getByRole('tab', { name: 'Current node', exact: true })).toHaveAttribute('aria-selected', 'true'); await expect(linked.getByRole('heading', { name: 'Deploy gateway-prod release #184', exact: true })).toBeVisible(); await expect(linked.getByText('Control plane', { exact: false })).toBeVisible(); await expect(linked.getByText('Docker operation completed successfully', { exact: true })).toBeVisible()
})
for (const width of [390, 1440]) for (const language of ['en-US', 'zh-CN']) for (const theme of ['dark', 'light']) {
 test(`notification AI responsive ${language} ${theme} ${width}`, async ({ page }) => { await setup(page, language, theme); await page.setViewportSize({ width, height: 900 }); for (const path of ['/settings#notifications', '/settings#ai', '/ai-operations', '/audit-logs', '/tasks#task-pull-183', '/notifications']) { await page.goto(path); const zh = language === 'zh-CN'; if (path === '/settings#notifications') await expect(page.getByRole('button', { name: zh ? '添加通知渠道' : 'Add channel', exact: true })).toBeVisible(); else if (path === '/settings#ai') { await expect(page.getByRole('switch', { name: zh ? '启用 AI 运维' : 'Enable AI operations', exact: true })).toBeVisible(); await expect(page.getByRole('heading', { name: zh ? '聊天账号绑定与操作白名单' : 'Chat identity binding & operator allowlist', exact: true })).toBeVisible(); await expect(page.getByText(zh ? '非白名单账号只能查询授权节点的状态和数量摘要' : 'Other identities can query status and counts on authorized nodes only.', { exact: false })).toBeVisible() } else if (path === '/ai-operations') await expect(page.getByRole('button', { name: zh ? '发起诊断' : 'Start diagnosis', exact: true })).toBeVisible(); else if (path === '/audit-logs') { await expect(page.getByRole('tab', { name: zh ? '全部' : 'All', exact: true })).toHaveAttribute('aria-selected', 'true'); await expect(page.getByText('container.restart', { exact: true })).toBeVisible() } else if (path === '/tasks#task-pull-183') await expect(page.getByRole('region', { name: zh ? '关联任务' : 'Linked task', exact: true }).getByRole('heading', { name: 'Pull ghcr.io/afteryuwei/gateway:1.8.2', exact: true })).toBeVisible(); else await expect(page.getByText('Container OOM', { exact: true })).toBeVisible(); await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true) } await page.screenshot({ path: `/tmp/suma-notification-ai-${language}-${theme}-${width}.png`, fullPage: true })
})
}
