import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { GitBranch, KeyRound, Pencil, Plus, Search, Server, ShieldCheck, Trash2, X } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import type { GitAuthType, GitCredential, GitCredentialInput } from '../features/delivery/types'
import { api } from '../lib/api'
import { useI18n } from '../lib/i18n'
import { confirmDialog } from '../stores/dialog'
import { ResourceFrame } from './images'
import { Select } from '../components/ui/select'
import type { DockerNode } from '../lib/nodes'

type Tab = 'git' | 'registries' | 'docker-tls'
type RegistryAuthType = 'basic' | 'token'
interface RegistryCredential { id: number; name: string; server_address: string; auth_type: RegistryAuthType; username?: string; fingerprint?: string; created_at: string; updated_at: string; last_used_at?: string; authorized_node_ids: string[] }
interface RegistryInput { name: string; server_address: string; auth_type: RegistryAuthType; username: string; secret: string; authorized_node_ids: string[] }
interface TLSCredential { id: number; name: string; fingerprint: string; authorized_node_ids: string[]; created_at: string; updated_at: string }
interface TLSInput { name: string; ca: string; certificate: string; private_key: string; authorized_node_ids: string[] }

const inputClass = 'h-10 w-full rounded-xl border border-border bg-background px-3 text-xs outline-none transition-colors focus:border-accent'
const areaClass = 'min-h-28 w-full resize-y rounded-xl border border-border bg-background px-3 py-2 font-mono text-[11px] leading-5 outline-none focus:border-accent'
const emptyGit = (): GitCredentialInput => ({ name: '', auth_type: 'http_token', username: '', secret: '', private_key: '', passphrase: '', known_hosts: '', custom_ca: '', authorized_node_ids: [] })
const emptyRegistry = (): RegistryInput => ({ name: '', server_address: '', auth_type: 'basic', username: '', secret: '', authorized_node_ids: [] })
const emptyTLS = (): TLSInput => ({ name: '', ca: '', certificate: '', private_key: '', authorized_node_ids: [] })

export function AuthenticationPage() {
  const { language } = useI18n(); const zh = language === 'zh-CN'
  const client = useQueryClient(); const [tab, setTab] = useState<Tab>('git'); const [search, setSearch] = useState('')
  const [editingGit, setEditingGit] = useState<GitCredential | null>(null); const [gitInput, setGitInput] = useState<GitCredentialInput>(emptyGit); const [gitOpen, setGitOpen] = useState(false)
  const [editingRegistry, setEditingRegistry] = useState<RegistryCredential | null>(null); const [registryInput, setRegistryInput] = useState<RegistryInput>(emptyRegistry); const [registryOpen, setRegistryOpen] = useState(false)
  const [editingTLS, setEditingTLS] = useState<TLSCredential | null>(null); const [tlsInput, setTLSInput] = useState<TLSInput>(emptyTLS); const [tlsOpen, setTLSOpen] = useState(false)
  const git = useQuery({ queryKey: ['git-credentials'], queryFn: () => api<GitCredential[]>('/credentials/git') })
  const registries = useQuery({ queryKey: ['registry-credentials'], queryFn: () => api<RegistryCredential[]>('/credentials/registries') })
  const tls = useQuery({ queryKey: ['docker-tls-credentials'], queryFn: () => api<TLSCredential[]>('/credentials/docker-tls') })
  const nodes = useQuery({ queryKey: ['nodes'], queryFn: () => api<DockerNode[]>('/nodes') })
  const saveGit = useMutation({ mutationFn: (value: GitCredentialInput) => api<GitCredential>(editingGit ? `/credentials/git/${editingGit.id}` : '/credentials/git', { method: editingGit ? 'PUT' : 'POST', body: JSON.stringify(value) }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['git-credentials'] }); setGitOpen(false) } })
  const saveRegistry = useMutation({ mutationFn: (value: RegistryInput) => api<RegistryCredential>(editingRegistry ? `/credentials/registries/${editingRegistry.id}` : '/credentials/registries', { method: editingRegistry ? 'PUT' : 'POST', body: JSON.stringify(value) }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['registry-credentials'] }); setRegistryOpen(false) } })
  const saveTLS = useMutation({ mutationFn: (value: TLSInput) => api<TLSCredential>(editingTLS ? `/credentials/docker-tls/${editingTLS.id}` : '/credentials/docker-tls', { method: editingTLS ? 'PUT' : 'POST', body: JSON.stringify(value) }), onSuccess: () => { void client.invalidateQueries({ queryKey: ['docker-tls-credentials'] }); setTLSOpen(false) } })
  const term = search.trim().toLowerCase()
  const filteredGit = useMemo(() => git.data?.filter((row) => `${row.name} ${row.auth_type} ${row.username || ''} ${row.fingerprint || ''}`.toLowerCase().includes(term)) || [], [git.data, term])
  const filteredRegistries = useMemo(() => registries.data?.filter((row) => `${row.name} ${row.server_address} ${row.auth_type} ${row.username || ''}`.toLowerCase().includes(term)) || [], [registries.data, term])
  const filteredTLS = useMemo(() => tls.data?.filter((row) => `${row.name} ${row.fingerprint}`.toLowerCase().includes(term)) || [], [tls.data, term])
  const create = () => tab === 'git' ? (setEditingGit(null), setGitInput(emptyGit()), setGitOpen(true)) : tab === 'registries' ? (setEditingRegistry(null), setRegistryInput(emptyRegistry()), setRegistryOpen(true)) : (setEditingTLS(null), setTLSInput(emptyTLS()), setTLSOpen(true))
  const removeGit = async (row: GitCredential) => { if (row.used_by) { await confirmDialog({ title: zh ? '凭据正在使用' : 'Credential in use', description: zh ? `“${row.name}”正被 ${row.used_by} 个项目使用，请先在项目中更换认证来源。` : `“${row.name}” is used by ${row.used_by} project(s). Change those projects first.`, confirmLabel: zh ? '知道了' : 'Got it' }); return } if (!await confirmDialog({ title: zh ? '删除 Git 凭据？' : 'Delete Git credential?', description: zh ? `将永久删除“${row.name}”。` : `Permanently delete “${row.name}”.`, confirmLabel: zh ? '删除' : 'Delete', danger: true })) return; await api(`/credentials/git/${row.id}`, { method: 'DELETE' }); await client.invalidateQueries({ queryKey: ['git-credentials'] }) }
  const removeRegistry = async (row: RegistryCredential) => { if (!await confirmDialog({ title: zh ? '删除镜像仓库凭据？' : 'Delete registry credential?', description: zh ? `将永久删除“${row.name}”。` : `Permanently delete “${row.name}”.`, confirmLabel: zh ? '删除' : 'Delete', danger: true })) return; await api(`/credentials/registries/${row.id}`, { method: 'DELETE' }); await client.invalidateQueries({ queryKey: ['registry-credentials'] }) }
  const removeTLS = async (row: TLSCredential) => { if (!await confirmDialog({ title: zh ? '删除 Docker TLS 凭据？' : 'Delete Docker TLS credential?', description: zh ? '请先取消节点引用和全部授权。' : 'Detach node references and grants first.', confirmLabel: zh ? '删除' : 'Delete', danger: true })) return; await api(`/credentials/docker-tls/${row.id}`, { method: 'DELETE' }); await client.invalidateQueries({ queryKey: ['docker-tls-credentials'] }) }

  return <ResourceFrame title={zh ? '认证中心' : 'Authentication Center'} detail={zh ? '集中保存 Git、镜像仓库与 Docker TLS 凭据，并按节点授权。' : 'Store Git, registry, and Docker TLS credentials with per-node grants.'} action={<button onClick={create} className="flex h-9 items-center gap-2 rounded-xl bg-accent px-4 text-xs font-semibold text-accent-foreground"><Plus className="size-3.5" />{zh ? '新增凭据' : 'New credential'}</button>}>
    <div className="mb-5 flex flex-wrap items-center gap-3 border-b border-border"><div className="flex">{([['git', zh ? 'Git 凭据' : 'Git credentials', GitBranch], ['registries', zh ? '镜像仓库' : 'Registries', Server], ['docker-tls', 'Docker TLS', ShieldCheck]] as const).map(([value, label, Icon]) => <button key={value} onClick={() => setTab(value)} className={`flex h-11 items-center gap-2 border-b-2 px-4 text-xs ${tab === value ? 'border-accent text-text' : 'border-transparent text-text-muted hover:text-text'}`}><Icon className="size-3.5" />{label}</button>)}</div><label className="relative ml-auto mb-2"><Search className="absolute left-3 top-2.5 size-3.5 text-text-subtle" /><input value={search} onChange={(event) => setSearch(event.target.value)} className="h-9 w-64 rounded-xl border border-border bg-surface pl-9 pr-3 text-xs outline-none focus:border-accent" placeholder={zh ? '搜索凭据' : 'Search credentials'} /></label></div>
    {tab === 'git' && <CredentialList empty={filteredGit.length === 0} zh={zh}>{filteredGit.map((row) => <CredentialRow key={row.id} icon={<KeyRound className="size-4" />} title={row.name} detail={`${gitAuthLabel(row.auth_type, zh)}${row.username ? ` · ${row.username}` : ''}${row.fingerprint ? ` · ${row.fingerprint}` : ''}`} meta={zh ? `授权 ${row.authorized_node_ids?.length || 0} 个节点` : `${row.authorized_node_ids?.length || 0} node grants`} onEdit={() => { setEditingGit(row); setGitInput({ ...emptyGit(), name: row.name, auth_type: row.auth_type, username: row.username || '', authorized_node_ids: row.authorized_node_ids || [] }); setGitOpen(true) }} onRemove={() => void removeGit(row)} />)}</CredentialList>}
    {tab === 'registries' && <CredentialList empty={filteredRegistries.length === 0} zh={zh}>{filteredRegistries.map((row) => <CredentialRow key={row.id} icon={<Server className="size-4" />} title={row.name} detail={`${row.server_address} · ${row.auth_type === 'basic' ? (zh ? '账号密码' : 'Username/password') : 'Token'}`} meta={zh ? `授权 ${row.authorized_node_ids?.length || 0} 个节点` : `${row.authorized_node_ids?.length || 0} node grants`} onEdit={() => { setEditingRegistry(row); setRegistryInput({ ...emptyRegistry(), name: row.name, server_address: row.server_address, auth_type: row.auth_type, username: row.username || '', authorized_node_ids: row.authorized_node_ids || [] }); setRegistryOpen(true) }} onRemove={() => void removeRegistry(row)} />)}</CredentialList>}
    {tab === 'docker-tls' && <CredentialList empty={filteredTLS.length === 0} zh={zh}>{filteredTLS.map((row) => <CredentialRow key={row.id} icon={<ShieldCheck className="size-4" />} title={row.name} detail={row.fingerprint} meta={zh ? `授权 ${row.authorized_node_ids.length} 个节点` : `${row.authorized_node_ids.length} node grants`} onEdit={() => { setEditingTLS(row); setTLSInput({ ...emptyTLS(), name: row.name, authorized_node_ids: row.authorized_node_ids }); setTLSOpen(true) }} onRemove={() => void removeTLS(row)} />)}</CredentialList>}
    {gitOpen && <GitEditor zh={zh} nodes={nodes.data || []} editing={editingGit} input={gitInput} setInput={setGitInput} close={() => setGitOpen(false)} submit={(event) => { event.preventDefault(); saveGit.mutate(gitInput) }} error={saveGit.error?.message} pending={saveGit.isPending} />}
    {registryOpen && <RegistryEditor zh={zh} nodes={nodes.data || []} editing={editingRegistry} input={registryInput} setInput={setRegistryInput} close={() => setRegistryOpen(false)} submit={(event) => { event.preventDefault(); saveRegistry.mutate(registryInput) }} error={saveRegistry.error?.message} pending={saveRegistry.isPending} />}
    {tlsOpen && <TLSEditor zh={zh} nodes={nodes.data || []} editing={editingTLS} input={tlsInput} setInput={setTLSInput} close={() => setTLSOpen(false)} submit={(event) => { event.preventDefault(); saveTLS.mutate(tlsInput) }} error={saveTLS.error?.message} pending={saveTLS.isPending} />}
  </ResourceFrame>
}

function CredentialList({ empty, zh, children }: { empty: boolean; zh: boolean; children: React.ReactNode }) { return empty ? <div className="grid min-h-64 place-items-center border-y border-border text-center"><div><ShieldCheck className="mx-auto size-6 text-text-subtle" /><p className="mt-3 text-sm">{zh ? '暂无匹配的凭据' : 'No matching credentials'}</p></div></div> : <div className="divide-y divide-border border-y border-border">{children}</div> }
function CredentialRow({ icon, title, detail, meta, onEdit, onRemove }: { icon: React.ReactNode; title: string; detail: string; meta: string; onEdit: () => void; onRemove: () => void }) { return <div className="group grid min-h-16 grid-cols-[minmax(0,1fr)_180px_72px] items-center gap-4 px-3 hover:bg-surface/60"><div className="flex min-w-0 items-center gap-3 text-text-subtle">{icon}<div className="min-w-0"><p className="truncate text-sm font-medium text-text">{title}</p><p className="mt-0.5 truncate font-mono text-[10px]">{detail}</p></div></div><p className="truncate text-right text-[10px] text-text-subtle">{meta}</p><div className="flex opacity-0 group-hover:opacity-100"><button onClick={onEdit} className="grid size-8 place-items-center rounded-lg hover:bg-surface-hover"><Pencil className="size-3.5" /></button><button onClick={onRemove} className="grid size-8 place-items-center rounded-lg text-danger hover:bg-danger-subtle"><Trash2 className="size-3.5" /></button></div></div> }
function Field({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1.5 flex justify-between gap-3 text-xs text-text-muted"><span>{label}</span>{hint && <span className="text-[10px] text-text-subtle">{hint}</span>}</span>{children}</label> }
function EditorShell({ title, close, submit, error, pending, children }: { title: string; close: () => void; submit: (event: FormEvent) => void; error?: string; pending: boolean; children: React.ReactNode }) { const saveLabel = /[\u4e00-\u9fff]/.test(title) ? '保存' : 'Save'; return <><button className="fixed inset-0 z-30 bg-black/35" onClick={close} aria-label="Close" /><aside className="fixed inset-y-0 right-0 z-40 w-full max-w-lg overflow-y-auto border-l border-border bg-elevated p-6 shadow-2xl"><button onClick={close} className="absolute right-5 top-5 grid size-8 place-items-center rounded-lg hover:bg-surface-hover"><X className="size-4" /></button><h2 className="text-lg font-semibold">{title}</h2><form onSubmit={submit} className="mt-7 space-y-5">{children}{error && <p className="text-xs text-danger">{error}</p>}<button disabled={pending} className="h-10 w-full rounded-xl bg-accent text-xs font-semibold text-accent-foreground disabled:opacity-50">{pending ? '…' : saveLabel}</button></form></aside></> }
function GitEditor({ zh, nodes, editing, input, setInput, close, submit, error, pending }: { zh: boolean; nodes: DockerNode[]; editing: GitCredential | null; input: GitCredentialInput; setInput: React.Dispatch<React.SetStateAction<GitCredentialInput>>; close: () => void; submit: (event: FormEvent) => void; error?: string; pending: boolean }) {
  const set = <K extends keyof GitCredentialInput>(key: K, value: GitCredentialInput[K]) => setInput((current) => ({ ...current, [key]: value }))
  return <EditorShell title={editing ? (zh ? '编辑 Git 凭据' : 'Edit Git credential') : (zh ? '新增 Git 凭据' : 'New Git credential')} close={close} submit={submit} error={error} pending={pending}>
    <Field label={zh ? '名称' : 'Name'}><input required value={input.name} onChange={(e) => set('name', e.target.value)} className={inputClass} /></Field>
    <Field label={zh ? '认证类型' : 'Authentication type'}><Select value={input.auth_type} onValueChange={(authType) => set('auth_type', authType)} options={[{ value: 'http_token', label: 'HTTPS token' }, { value: 'http_basic', label: 'HTTPS basic' }, { value: 'ssh_key', label: 'SSH key' }, { value: 'none', label: 'None' }]} /></Field>
    {(input.auth_type === 'http_token' || input.auth_type === 'http_basic') && <><Field label={input.auth_type === 'http_basic' ? (zh ? '用户名' : 'Username') : (zh ? '用户名（可选）' : 'Username (optional)')}><input value={input.username} onChange={(e) => set('username', e.target.value)} className={inputClass} /></Field><Field label={input.auth_type === 'http_token' ? 'Token' : (zh ? '密码' : 'Password')} hint={editing ? (zh ? '留空保留原值' : 'Leave empty to preserve') : undefined}><input type="password" value={input.secret} onChange={(e) => set('secret', e.target.value)} className={inputClass} /></Field></>}
    {input.auth_type === 'ssh_key' && <><Field label={zh ? 'SSH 私钥' : 'SSH private key'} hint={editing ? (zh ? '留空保留原值' : 'Leave empty to preserve') : undefined}><textarea value={input.private_key} onChange={(e) => set('private_key', e.target.value)} className={areaClass} /></Field><Field label="known_hosts"><textarea value={input.known_hosts} onChange={(e) => set('known_hosts', e.target.value)} className={areaClass} /></Field><Field label={zh ? '私钥密码（可选）' : 'Passphrase (optional)'}><input type="password" value={input.passphrase} onChange={(e) => set('passphrase', e.target.value)} className={inputClass} /></Field></>}
    <Field label={zh ? '自定义 CA（可选）' : 'Custom CA (optional)'}><textarea value={input.custom_ca} onChange={(e) => set('custom_ca', e.target.value)} className={areaClass} /></Field>
    <NodeGrantSelector zh={zh} nodes={nodes} value={input.authorized_node_ids || []} onChange={(value) => set('authorized_node_ids', value)} />
  </EditorShell>
}

function RegistryEditor({ zh, nodes, editing, input, setInput, close, submit, error, pending }: { zh: boolean; nodes: DockerNode[]; editing: RegistryCredential | null; input: RegistryInput; setInput: React.Dispatch<React.SetStateAction<RegistryInput>>; close: () => void; submit: (event: FormEvent) => void; error?: string; pending: boolean }) {
  const set = <K extends keyof RegistryInput>(key: K, value: RegistryInput[K]) => setInput((current) => ({ ...current, [key]: value }))
  return <EditorShell title={editing ? (zh ? '编辑镜像仓库凭据' : 'Edit registry credential') : (zh ? '新增镜像仓库凭据' : 'New registry credential')} close={close} submit={submit} error={error} pending={pending}>
    <Field label={zh ? '名称' : 'Name'}><input required value={input.name} onChange={(e) => set('name', e.target.value)} className={inputClass} /></Field>
    <Field label={zh ? '仓库地址' : 'Registry address'} hint="host[:port]"><input required value={input.server_address} onChange={(e) => set('server_address', e.target.value)} className={`${inputClass} font-mono`} placeholder="registry.example.com:5000" /></Field>
    <Field label={zh ? '认证类型' : 'Authentication type'}><Select value={input.auth_type} onValueChange={(authType) => set('auth_type', authType)} options={[{ value: 'basic', label: zh ? '账号密码' : 'Username/password' }, { value: 'token', label: 'Token' }]} /></Field>
    {input.auth_type === 'basic' && <Field label={zh ? '用户名' : 'Username'}><input value={input.username} onChange={(e) => set('username', e.target.value)} className={inputClass} /></Field>}
    <Field label={input.auth_type === 'basic' ? (zh ? '密码' : 'Password') : 'Token'} hint={editing ? (zh ? '留空保留原值' : 'Leave empty to preserve') : undefined}><input type="password" value={input.secret} onChange={(e) => set('secret', e.target.value)} className={inputClass} /></Field>
    <NodeGrantSelector zh={zh} nodes={nodes} value={input.authorized_node_ids} onChange={(value) => set('authorized_node_ids', value)} />
  </EditorShell>
}

function TLSEditor({ zh, nodes, editing, input, setInput, close, submit, error, pending }: { zh: boolean; nodes: DockerNode[]; editing: TLSCredential | null; input: TLSInput; setInput: React.Dispatch<React.SetStateAction<TLSInput>>; close: () => void; submit: (event: FormEvent) => void; error?: string; pending: boolean }) {
  const set = <K extends keyof TLSInput>(key: K, value: TLSInput[K]) => setInput((current) => ({ ...current, [key]: value }))
  const preserve = editing ? (zh ? '留空保留原值' : 'Leave all empty to preserve') : undefined
  return <EditorShell title={editing ? (zh ? '编辑 Docker TLS 凭据' : 'Edit Docker TLS credential') : (zh ? '新增 Docker TLS 凭据' : 'New Docker TLS credential')} close={close} submit={submit} error={error} pending={pending}>
    <Field label={zh ? '名称' : 'Name'}><input required value={input.name} onChange={(e) => set('name', e.target.value)} className={inputClass} /></Field>
    <Field label="CA PEM" hint={preserve}><textarea value={input.ca} onChange={(e) => set('ca', e.target.value)} className={areaClass} /></Field>
    <Field label={zh ? '客户端证书 PEM' : 'Client certificate PEM'} hint={preserve}><textarea value={input.certificate} onChange={(e) => set('certificate', e.target.value)} className={areaClass} /></Field>
    <Field label={zh ? '客户端私钥 PEM' : 'Client private key PEM'} hint={preserve}><textarea value={input.private_key} onChange={(e) => set('private_key', e.target.value)} className={areaClass} /></Field>
    <NodeGrantSelector zh={zh} nodes={nodes} value={input.authorized_node_ids} onChange={(value) => set('authorized_node_ids', value)} />
  </EditorShell>
}

function NodeGrantSelector({ zh, nodes, value, onChange }: { zh: boolean; nodes: DockerNode[]; value: string[]; onChange: (value: string[]) => void }) {
  const toggle = (id: string) => onChange(value.includes(id) ? value.filter((item) => item !== id) : [...value, id])
  return <fieldset><legend className="mb-2 text-xs text-text-muted">{zh ? '节点授权（默认不授权）' : 'Node grants (none by default)'}</legend><div className="space-y-2 rounded-xl border border-border p-3">{nodes.length === 0 ? <p className="text-[11px] text-text-subtle">{zh ? '暂无节点' : 'No nodes'}</p> : nodes.map((node) => <label key={node.id} className="flex items-center gap-3 text-xs"><input type="checkbox" checked={value.includes(node.id)} onChange={() => toggle(node.id)} /><span className="min-w-0 flex-1 truncate">{node.name}</span><span className="font-mono text-[10px] text-text-subtle">{node.connection_type}</span></label>)}</div></fieldset>
}
function gitAuthLabel(value: GitAuthType, zh: boolean) { if (value === 'http_token') return 'HTTPS token'; if (value === 'http_basic') return zh ? 'HTTPS 用户名/密码' : 'HTTPS basic'; if (value === 'ssh_key') return 'SSH key'; return zh ? '无需认证' : 'No authentication' }
