import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Download, Tag, Trash2, X } from 'lucide-react'
import { type ReactNode, useState } from 'react'
import { LoadingState } from '../components/ui/loading-state'
import { api } from '../lib/api'
import { useI18n } from '../lib/i18n'
import { confirmDialog, promptDialog } from '../stores/dialog'

interface Image { id: string; tags: string[]; digests: string[]; size: number; created: string; containers: number; architecture?: string; os?: string; author?: string; docker_version?: string; layers?: string[] }

export function ImagesPage() {
  const client = useQueryClient(); const [reference, setReference] = useState(''); const [selected, setSelected] = useState(''); const { t, language } = useI18n()
  const query = useQuery({ queryKey: ['images'], queryFn: () => api<Image[]>('/images') }); const detail = useQuery({ queryKey: ['image', selected], queryFn: () => api<Image>(`/images/${encodeURIComponent(selected)}`), enabled: !!selected })
  const pull = useMutation({ mutationFn: () => api('/images/pull', { method: 'POST', body: JSON.stringify({ reference }) }), onSuccess: () => { setReference(''); client.invalidateQueries({ queryKey: ['tasks'] }) } })
  const remove = useMutation({ mutationFn: (id: string) => api(`/images/${encodeURIComponent(id)}?force=false`, { method: 'DELETE' }), onSuccess: () => { setSelected(''); client.invalidateQueries({ queryKey: ['images'] }) } })
  const tag = async (row: Image) => { const value = await promptDialog({ title: t('newImageTag'), description: t('tagDescription'), confirmLabel: t('tag'), input: { label: t('newImageTag'), initialValue: row.tags?.[0] || 'repository:tag' } }); if (!value) return; await api(`/images/${encodeURIComponent(row.id)}/tag`, { method: 'POST', body: JSON.stringify({ reference: value }) }); await client.invalidateQueries({ queryKey: ['images'] }) }
  const removeImage = async (row: Image) => { const name = row.tags?.[0] || row.id; if (await confirmDialog({ title: t('removeImage'), description: t('removeImageDescription', { name }), confirmLabel: t('remove'), danger: true })) remove.mutate(row.id) }
  const size = (bytes: number) => `${(bytes / 1024 ** 2).toFixed(1)} MB`

  return <ResourceFrame eyebrow="Docker" title={t('images')} detail={language === 'zh-CN' ? `${query.data?.length ?? 0} 个本地镜像` : `${query.data?.length ?? 0} local images`} action={<form onSubmit={(event) => { event.preventDefault(); if (reference) pull.mutate() }} className="flex gap-2"><input value={reference} onChange={(event) => setReference(event.target.value)} className="h-8 w-60 rounded-md border border-border bg-surface px-2.5 text-xs outline-none" placeholder="nginx:latest" /><button className="flex h-8 items-center gap-2 rounded-md bg-accent px-3 text-xs font-semibold text-accent-foreground"><Download className="size-3.5" />Pull</button></form>}>
    {query.isPending ? <LoadingState label={language === 'zh-CN' ? '正在加载镜像' : 'Loading images'} /> : <div className="divide-y divide-border border-y border-border">{query.data?.map((row) => <div key={row.id} className="group grid min-h-16 grid-cols-[minmax(0,1fr)_100px_80px_72px] items-center gap-4 px-2 hover:bg-surface/60"><button onClick={() => setSelected(row.id)} className="min-w-0 text-left"><p className="truncate text-sm font-medium">{row.tags?.[0] || '<none>:<none>'}</p><p className="truncate font-mono text-[10px] text-text-subtle">{row.id.replace('sha256:', '').slice(0, 12)}</p></button><p className="text-xs tabular-nums text-text-muted">{size(row.size)}</p><p className="text-xs text-text-muted">{row.containers < 0 ? '—' : language === 'zh-CN' ? `${row.containers} 个引用` : `${row.containers} used`}</p><div className="flex opacity-0 group-hover:opacity-100"><button onClick={() => void tag(row)} className="grid size-7 place-items-center rounded hover:bg-surface-hover" title={t('tag')}><Tag className="size-3.5" /></button><button onClick={() => void removeImage(row)} className="grid size-7 place-items-center rounded hover:bg-surface-hover" title={t('removeImage')}><Trash2 className="size-3.5" /></button></div></div>)}</div>}
    {selected && <aside className="fixed inset-y-0 right-0 z-40 w-full max-w-md border-l border-border bg-elevated p-6 shadow-2xl"><button onClick={() => setSelected('')} className="absolute right-5 top-5 grid size-8 place-items-center rounded-md hover:bg-surface-hover"><X className="size-4" /></button><p className="text-xs uppercase tracking-wider text-text-subtle">{language === 'zh-CN' ? '镜像详情' : 'Image inspect'}</p><h2 className="mt-2 max-w-[80%] truncate text-lg font-semibold">{detail.data?.tags?.[0] || selected.slice(0, 19)}</h2>{detail.isPending ? <div className="mt-7"><LoadingState compact rows={5} label={language === 'zh-CN' ? '正在加载镜像详情' : 'Loading image details'} /></div> : <dl className="mt-7 divide-y divide-border border-y border-border">{[['ID', detail.data?.id], [language === 'zh-CN' ? '大小' : 'Size', detail.data ? size(detail.data.size) : '—'], [language === 'zh-CN' ? '平台' : 'Platform', `${detail.data?.os || '—'} / ${detail.data?.architecture || '—'}`], [language === 'zh-CN' ? '创建时间' : 'Created', detail.data?.created ? new Date(detail.data.created).toLocaleString(language) : '—'], [language === 'zh-CN' ? '层数' : 'Layers', detail.data?.layers?.length ?? 0]].map(([label, value]) => <div key={label} className="grid min-h-11 grid-cols-[100px_1fr] items-center text-xs"><dt className="text-text-muted">{label}</dt><dd className="truncate font-mono">{value}</dd></div>)}</dl>}</aside>}
  </ResourceFrame>
}

export function ResourceFrame({ title, detail, action, children }: { eyebrow?: string; title: string; detail: string; action?: ReactNode; children: ReactNode }) { return <div><header className="mb-7 flex items-end"><div><h1 className="text-xl font-semibold tracking-tight">{title}</h1><p className="mt-1 text-xs text-text-muted">{detail}</p></div><div className="ml-auto">{action}</div></header>{children}</div> }
